- .gitmodules
We had these via git@ because they were private, now that they're
public, let's use the more usual URL.
> Update submodules to use https

- doc/ipc.adoc
Thanks to a friend for pointing this out, who is unattributed because
the message was sent in private.
> Fix wording around closed receive

- build/xtask/src/license.rs
In #270, I thought I was checking for licenses, but I had the condition
inverted. In my hurry to get things landed since everyone found out
about Hubris before I got the licenses in, I mistook green CI for
everything working correctly.
This fixes the bug *and* updates the submodules with license changes.
> Actually check for licenses.

- doc/ipc.adoc
- doc/syscalls.adoc
I got confused about the fact that RecvMessage doesn't contain any way
to actually tell the receiver about the loaned memory. I believe this
additional cross-reference should greatly help with understanding this
section.
> doc/ipc: Explain that borrows are accessed separately by the receiver

- README.mkdn
> Fix typos for flashing nucleo boards

- Cargo.lock
- app/lpc55xpresso/app-a0.toml
- app/lpc55xpresso/wipecmpa.gdb
- drv/lpc55-romapi/Cargo.toml
- drv/lpc55-romapi/src/lib.rs
- stage0/Cargo.toml
- stage0/src/main.rs
- test/tests-lpc55xpresso/app-a0.toml
The ROM API was intentionally written to only support lpc55
hardware rev 1B. It's still useful to be able to do basic verification
on 0A hardware. Add appropriate support iin the ROM API.
> Add support for A0 hardware

- doc/ipc.adoc
- doc/timers.adoc
The protocol uses leases, the Rust code uses borrows.
> doc/ipc: copyedits

- README.mkdn
While working through initial set up, I found myself in the place where the REAMDE suggested needing v0.11, the package manager (Ubuntu 20.04 LTS) having an 0.10.x version, and needing to build myself. Going through this, it wasn't clear what features we were relying on and so I guessed mostly that the defaults of `./configure` were correct.
I've added a bit more prose to try and help make this a little smoother for the next person. We may want something similar for how to set up pyocd at some point.
> Provide additional details for manual OpenOCD install

- README.mkdn
xtask build was replaced by xtask check, like, decades ago in
Hubris-time.
Fixed #310.
> README: fix references to xtask build

- README.mkdn
* Overwrite existing firmware so the new bootloader doesn't accidentally
try to boot an old main firmware
* Remove instruction to setup three terminals (pyocd gdbserver, telnet
for semihosting, gdb) as multiple folks have run into problems following
that bit.  Once RickLink and pyocd is installed, `cargo xtask flash` and
`humility itm` just work without running a gdb server.  Semihosting
isn't enabled in the lpc55s69xpresso app so no need to run a terminal
for it.  Running a pyocd gdbserver is necessary if you want to run
`cargo xtask gdb` but we don't tell people to do that.
> README: clarify RickLink instructions on lpc55s69xpresso

- app/demo-stm32f4-discovery/app-f3.toml
- app/demo-stm32f4-discovery/app.toml
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/demo-stm32h7-nucleo/app-h7b3.toml
- app/gemini-bu-rot/app.toml
- app/gemini-bu/app.toml
- app/gimlet-rot/app.toml
- app/gimlet/app.toml
- app/gimletlet/app.toml
- app/lpc55xpresso/app-a0.toml
- app/lpc55xpresso/app.toml
- app/sidecar/app.toml
- build/xtask/src/main.rs
- test/tests-gemini-bu-rot/app.toml
- test/tests-gemini-bu/app.toml
- test/tests-lpc55xpresso/app-a0.toml
- test/tests-lpc55xpresso/app.toml
- test/tests-stm32fx/app-f3.toml
- test/tests-stm32fx/app.toml
- test/tests-stm32h7/app-h743.toml
- test/tests-stm32h7/app-h753.toml
- test/tests-stm32h7/app-h7b3.toml
This reduces duplication of task slots in `app.toml` in the common case, but keeps them explicit and preserves the option to do generic slot-to-task mapping.
I don't _think_ this will break Humility, but am not totally sure – @bcantrill, any idea?
> Simple task slots

- README.mkdn
Now that the Hubris repo is public PRs should come from forks.
Fixes issue identified here: https://github.com/oxidecomputer/hubris/pull/324#issuecomment-991720140
> README: Remove PR submission instructions handling private repo quirks.

- README.mkdn
- drv/stm32h7-i2c/src/lib.rs
The cargo install command ignores the Cargo.lock by default, we need to
explicitly pass `--locked` to cargo install to avoid changes to git
dependencies breaking hubris install.
See https://github.com/oxidecomputer/humility/issues/57 for details.
Also fixed two typos in comments.
> Update humility install instructions in README.md

- Cargo.lock
- app/demo-stm32f4-discovery/app.toml
- task/hiffy/Cargo.toml
That's a binary, not a library, so it's not useful as a dependency. This
was producing a warning.
> hiffy: remove errant drv-stm32fx-rcc dep

- drv/lpc55-usart/src/main.rs
- sys/userlib/src/hl.rs
- sys/userlib/src/lib.rs
- test/test-suite/src/main.rs
This is factored out of the IDL work.
- Changed return type of sys_borrow_info to be more useful and less
error prone.
- Added named Lease constructors to make Lease construction more obvious
and allow creation of write_only leases.
> userlib: some usability enhancements

- Cargo.lock
- Cargo.toml
- app/gemini-bu-rot/app.toml
- app/gimlet-rot/app.toml
- app/lpc55xpresso/app.toml
- drv/lpc55-spi-server/Cargo.toml
- drv/lpc55-spi-server/src/main.rs
- drv/lpc55-spi/src/lib.rs
- task/spi-loopback/Cargo.toml
- task/spi-loopback/README.mkdn
- task/spi-loopback/src/main.rs
Add as simple loopback task for testing SPI. This stores 8 bytes of what was previously sent and sends it back next time a request comes in.
```
[labbott@labbott-the-desktop humility]$ ./target/debug/humility -a ~/hubristic-sketching/target/gemini-bu/dist/build-gemini-bu.zip -p usb-1 spi -p 4 --write 1,2,3,4,5,6,7,8 --read --nbytes 8
humility: attached via ST-Link
humility: SPI master is spi4_driver
\/  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0x00000000 | 00 00 00 00 00 00 00 00                         | ........        
[labbott@labbott-the-desktop humility]$ ./target/debug/humility -a ~/hubristic-sketching/target/gemini-bu/dist/build-gemini-bu.zip -p usb-1 spi -p 4 --write 8,7,6,5,4,3,2,1 --read --nbytes 8
humility: attached via ST-Link
humility: SPI master is spi4_driver
\/  1  2 …
```
> Add SPI Loopback for the RoT

- Cargo.lock
- build/xtask/Cargo.toml
- build/xtask/src/dist.rs
This uses `--remap-path-prefix` to shorten the paths embedded in panic messages.  Since we're limited to 128 bytes, this could make the difference between seeing and not seeing the full path + line number.
In particular, it remaps `git` dependencies from `/Users/mjk/.cargo/git/checkouts/...` to just `git/...` (the original will vary depending on OS and username), and crates within the same checkout from `/Users/mjk/oxide/hubris/...` to `hubris/...`.
As far as I can tell, this doesn't affect Humility's backtracing, since that's all baked into the ELF files.
However, [the docs](https://doc.rust-lang.org/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output) say this also affects "debug information, macro expansions, etc" – @steveklabnik , any idea if this is …
> Shorten panic messages

- build/xtask/src/dist.rs
(otherwise, you'll end up with spurious rebuilds because `rustc` flag order will change)
> Use a BTreeMap to make remap-path order deterministic

- build/xtask/src/dist.rs
Before:
```
flash = 8000000..8100000
ram = 20000000..20020000
Used:
flash: 0x5e100
ram: 0x13500
```
After:
```
flash = 0x08000000..0x08100000
ram   = 0x20000000..0x20020000
Used:
flash: 0x5e100 (36%)
ram:   0x13500 (60%)
```
> More informative size info

- sys/kern/src/arch/arm_m.rs
Off-by-one error in DefaultHandler() meant IRQ0 would result in an
unknown exception panic instead of looking for a task to dispatch to.
Fixes #367
> kern/arm_m: properly dispatch to irq0 handler

- drv/stm32h7-spi-server/build.rs
> stm32h7-spi-server: add remaining IO ports.

- Cargo.lock
- Cargo.toml
- lib/unwrap-lite/Cargo.toml
- lib/unwrap-lite/src/lib.rs
- sys/kern/Cargo.toml
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/syscalls.rs
- sys/userlib/Cargo.toml
- sys/userlib/src/kipc.rs
This provides a syntactically-convenient equivalent to unwrap() on
Result/Option that is _significantly_ cheaper from a code generation
perspective, because it doesn't invoke any type's formatting routines.
This knocked like 5 kiB off one incarnation of the kernel.
> Introduce UnwrapLite.

- Cargo.lock
- build/xtask/Cargo.toml
- build/xtask/src/dist.rs
- build/xtask/src/main.rs
- build/xtask/src/sizes.rs
Sample output for `cargo xtask sizes app/sidecar/app.toml`:
```
jefe
flash:  7148 bytes (43%)
ram:    1620 bytes (79%)
rcc_driver
flash:  4156 bytes (50%)
ram:    1024 bytes (100%)
gpio_driver
flash:  5400 bytes (65%)
ram:    1024 bytes (100%)
spi2_driver
flash:  9256 bytes (56%)
ram:    2036 bytes (49%)
spi5_driver
flash:  9276 bytes (56%)
ram:    2036 bytes (49%)
i2c_driver
flash:  8756 bytes (53%)
ram:    2008 bytes (98%)
hiffy
flash: 15456 bytes (47%)
ram:    8752 bytes (26%)
sensor
flash:  4372 bytes (26%)
ram:    2000 bytes (97%)
sidecar_seq
flash: 19296 bytes (58%)
ram:    2316 bytes (56%)
idle
flash:    88 bytes (34%)
ram:     256 bytes (100%)
kernel
flash: 31732 bytes (96%)
ram:    1072 bytes (26%)
========== Suggested changes ==========
jefe:
flash: 8192 (from 16384) …
```
> Add cargo xtask sizes, to print sizes and suggest improvements

- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- drv/stm32h7-spi-server/build.rs
- drv/stm32h7-spi-server/src/main.rs
- drv/stm32h7-spi/src/lib.rs
This also changes the clock rate on stm32h7 nucleo to demonstrate that it works.
> Add per-device SPI clock divisors.

- .github/workflows/dist.yml
We were trying to do this ourselves, but it has always been a bit...
suboptimal. https://matklad.github.io/2021/09/04/fast-rust-builds.html
recently points towards this Action, and it should do a better job than
we were doing, and is easier to use, to boot!
This is not ready to merge yet, I would like to verify that it actually works, which of course means running the jobs which means opening a PR.
> Improve caching via Swatinem/rust-cache

- sys/userlib/src/lib.rs
Subtle typo in range computation here meant we never started writing
because we always saw zero bytes remaining.
> userlib: fix panic messages

- app/demo-stm32h7-nucleo/app-h743.toml
- drv/stm32h7-spi-server/build.rs
- drv/stm32h7-spi-server/src/main.rs
- drv/stm32h7-spi/src/lib.rs
My last round of fixes left things in a sort of mostly-working state, but I didn't like that very much, so I revisited the state machine.
I have also included a fix for SPI4/5/6 on STM32H7, which have shallower FIFOs.
> Redo stm32h7 SPI state machine

- Cargo.lock
- Cargo.toml
- drv/stm32g0-sys-api/Cargo.toml
- drv/stm32g0-sys-api/src/lib.rs
- drv/stm32g0-sys/Cargo.toml
- drv/stm32g0-sys/src/main.rs
- drv/stm32h7-gpio-api/Cargo.toml
- drv/stm32h7-gpio-api/src/lib.rs
- drv/stm32h7-gpio/Cargo.toml
- drv/stm32h7-gpio/src/main.rs
- drv/stm32xx-gpio-common/Cargo.toml
- drv/stm32xx-gpio-common/src/lib.rs
- drv/stm32xx-gpio-common/src/server.rs
This is a step toward reducing the overall high level of code
duplication between stm32 targets. It exploits some traits that the PACs
started generating circa 0.14, which are unfortunately not put into a
common crate, but, hey, at least they exist now.
Knocks some bytes (100+) off GPIO servers by reducing macro-driven code
duplication and giving the compiler an easier task.
This is sort of a HAL, but unlike most HALs it's very careful to allow
static monomorphization on properties you know at compile time (like
your SoC model target) and only use dynamic dispatch for things you vary
at runtime (like which gpio port you're poking).
Scary bits are mostly hidden in the server.rs file.
> Factor common GPIO code out of stm32{g0,h7}

- app/demo-stm32f4-discovery/app-f3.toml
- app/demo-stm32f4-discovery/app.toml
- app/demo-stm32g0-nucleo/app-g031.toml
- app/demo-stm32g0-nucleo/app-g070.toml
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gemini-bu-rot/app.toml
- app/gemini-bu/app.toml
- app/gimlet-rot/app.toml
- app/gimlet/app.toml
- app/gimletlet/app.toml
- app/lpc55xpresso/app-a0.toml
- app/lpc55xpresso/app.toml
- app/sidecar/app.toml
- build/xtask/src/dist.rs
- build/xtask/src/flash.rs
- build/xtask/src/gdb.rs
- build/xtask/src/humility.rs
- build/xtask/src/main.rs
- build/xtask/src/sizes.rs
- build/xtask/src/test.rs
- chips/lpc55.toml
- chips/stm32f3.toml
- chips/stm32f4.toml
- chips/stm32g0.toml
- chips/stm32h7.toml
- test/tests-gemini-bu-rot/app.toml
- test/tests-lpc55xpresso/app-a0.toml
- test/tests-lpc55xpresso/app.toml
This PR adds a new `chip` field to `app.toml` which specifies a file from which to load peripheral addresses.
It's still backwards-compatible, but I've gone through and changed all of the `app.toml`s that I could lay my hands on.
Having peripheral addresses in one place reduces copy-pasta, and will make it easier to switch to named interrupts consistently through all of our `app.toml`'s.
> Move chip peripherals into a separate file

- app/gimlet/app.toml
#423 broke `humility manifest` because the IRQ names are no longer part of the `app.toml` file.  This fixes it temporarily, until our bright future of named IRQs arrives (in #424).
> Fix broken IRQ by using numbers instead of name

- Cargo.lock
- Cargo.toml
- build/net/Cargo.toml
- build/net/src/lib.rs
- idl/net.idol
- task/net-api/Cargo.toml
- task/net-api/build.rs
- task/net-api/src/lib.rs
- task/net/Cargo.toml
- task/net/build.rs
- task/net/src/server.rs
- task/udpecho/src/main.rs
Previously they were named by index in the API, which was a result of me
being in a hurry. It meant that code could accidentally try to use the
wrong socket pretty easily, which results in a crash.
This starts generating an enum of all socket names, and using it in the
API, so that names are stable.
Note that this does _not_ provide a task-slot-style late-binding
mechanism for sockets, which we might want to do eventually.
> net: specify sockets by name

- build/xtask/src/dist.rs
`cargo_output_dir` always maps to `target`, but takes a significant number of milliseconds per invocation.  This speeds up a no-op build by about 40%.
> Don't run Cargo twice per task

- build/xtask/src/dist.rs
- build/xtask/src/flash.rs
Draft commit message:
```
This work adds two bits to the archive:  the final binaries that we
actually flashed, and some metadata to explain how that can be
reproduced via a flashing program (i.e., OpenOCD or pyOCD depending on
the target).
```
> add support for "humility flash"

- sys/kern/build.rs
@mkeeter observed that he had images that we quite clearly very different that had the same `HUBRIS_IMAGE_ID`:
[archive-1.zip](https://github.com/oxidecomputer/hubris/files/8128553/archive-1.zip)
[archive-2.zip](https://github.com/oxidecomputer/hubris/files/8128554/archive-2.zip)
The problem is that while we calculate the `HUBRIS_IMAGE_ID` correctly, we don't rebuild the kernel if/when that changes, resulting in a stale image ID being captured.  The fix, fortunately, is trivial: we need to indicate in the `build.rs` to rerun if the `HUBRIS_IMAGE_ID` environment variable changes.
> different images can have the same HUBRIS_IMAGE_ID

- Cargo.lock
This fixes errors like
```
humility hiffy failed: HIF version mismatch: target has 0.2; ours is 0.3
```
on Humility builds after [this commit](https://github.com/oxidecomputer/humility/commit/7fe74bdcd8ce89b27075f59389219e35e8cc3dca)
> Bump HIF for compatibility with new Humility

- Cargo.lock
- Cargo.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gemini-bu/app.toml
- app/gimlet/app.toml
- chips/stm32h7.toml
- drv/gimlet-hf-server/src/main.rs
- drv/hash-api/Cargo.toml
- drv/hash-api/build.rs
- drv/hash-api/src/lib.rs
- drv/stm32h7-hash-server/Cargo.toml
- drv/stm32h7-hash-server/build.rs
- drv/stm32h7-hash-server/src/main.rs
- drv/stm32h7-hash/Cargo.toml
- drv/stm32h7-hash/src/lib.rs
- drv/stm32h7-qspi/src/lib.rs
- idl/gimlet-hf.idol
- idl/hash.idol
- task/hiffy/Cargo.toml
- task/hiffy/src/common.rs
- task/hiffy/src/stm32h7.rs
Add STM32 HASH block driver.
Add QSPI function to call HASH on region and return SHA256 value.
Enable hash and qspi on Gemini and Nucleo 753
- removed U801, testing not succesful.)
- SI was not good on dupont-wired QSPI flash on Nucleo.
Testing on Nucleo shows that the software is probably correct.
Standard SHA256 test vectors pass.
TODO: Suspend/Resume HASH state if we have use cases for multiple client tasks.
TODO: Use 4x mode instead of 1x mode on QSPI to improve throughput.
TODO: HASH DMA of flash contents if performance requirements dictate its use.
TODO: Use HMAC from HASH block if there are use cases.
TODO: Resolve ambiguity about when NBLW must be set, either at the
begining of a hash data block or before the last word of a block is fed
to the hash DIN register.
TODO: Some …
> Add STM32H7 HASH block driver and QSPI API to hash regions of flash.

- build/xtask/src/dist.rs
> Stop with an error if cargo xtask build has an invalid task

- .github/workflows/dist.yml
- app/gimlet/rev-a.toml
- app/gimlet/rev-b.toml
- build/xtask/src/flash.rs
- drv/gimlet-hf-server/src/main.rs
- drv/gimlet-seq-server/src/main.rs
- drv/i2c-devices/src/isl68224.rs
- task/hiffy/src/main.rs
- task/power/src/main.rs
- task/spd/src/main.rs
- task/thermal/src/main.rs
This also renames `gimlet-1` to `gimlet-a`.  Here is the `humility manifest` for `gimlet-a`:
```
version => hubris build archive v1.0.0
git rev => 0b79f4805dd8fa6be21f1eaf5740253a63fc1052-dirty
image id => [3f, e4, ec, be, ab, 4, 14, aa]
board => gimlet-a
target => thumbv7em-none-eabihf
features => itm
total size => 214K
kernel size => 23K
tasks => 13
ID TASK                SIZE FEATURES
0 hiffy              44.0K h753, stm32h7, itm, i2c, gpio, spi, qspi
1 gimlet_seq         52.5K h753
2 spi4_driver        11.1K spi4, h753
3 spi2_driver        11.6K spi2, h753
4 i2c_driver         11.8K h753, itm
5 spd                19.5K h753, itm
6 power              11.5K itm, h753
7 hf                  8.2K h753
8 jefe                7.0K itm
9 thermal             7.6K itm, h753
10 sensor …
```
> add TOML for Gimlet Rev B

- README.mkdn
The update to `cargo install... humility` is required to avoid an error from cargo in which it doesn't know whether you want to install `humility` or `xtask`.
The updates to the package names are for ubuntu.
> Minor README installation fixes

- Cargo.lock
- build/xtask/Cargo.toml
- build/xtask/src/main.rs
structopt is still in Cargo.lock thanks to lpc55_support, cc https://github.com/oxidecomputer/lpc55_support/pull/15
> port from structopt to clap v3

- Cargo.lock
- drv/gimlet-hf-api/Cargo.toml
- drv/gimlet-seq-api/Cargo.toml
- drv/hash-api/Cargo.toml
- drv/sidecar-seq-api/Cargo.toml
- drv/spi-api/Cargo.toml
- drv/user-leds-api/Cargo.toml
- drv/user-leds-api/src/lib.rs
- drv/user-leds/Cargo.toml
- drv/user-leds/src/main.rs
- task/sensor-api/Cargo.toml
- task/thermal-api/Cargo.toml
Now that we're using Idol, we don't need to depend on `abi` explicitly.
In passing, I also consolidated the `LedError`, which was defined in two places instead of just in the `drv-user-leds-api` crate.
> Remove unused `abi` dep and duplicate `LedError`

- .github/workflows/dist.yml
- build/kernel-link.x
While this contains a number of small formatting/layout changes to try
and reduce the diff, the critical change is the re-insertion of the
PreResetTrampoline section and its accompanying comment. Removing these
broke the build on M0, where branches have very limited range.
> Reduce kernel-link deltas relative to cortex-m-rt

- Cargo.lock
- Cargo.toml
- app/gimletlet/app-vsc7448.toml
- drv/gimlet-hf-api/Cargo.toml
- drv/gimlet-hf-api/src/lib.rs
- drv/gimlet-seq-api/Cargo.toml
- drv/gimlet-seq-api/src/lib.rs
- drv/hash-api/Cargo.toml
- drv/hash-api/src/lib.rs
- drv/sidecar-seq-api/Cargo.toml
- drv/sidecar-seq-api/src/lib.rs
- drv/spi-api/Cargo.toml
- drv/spi-api/src/lib.rs
- drv/stm32xx-sys-api/Cargo.toml
- drv/stm32xx-sys-api/src/lib.rs
- drv/user-leds-api/Cargo.toml
- drv/user-leds-api/src/lib.rs
- lib/derive-idol-err/Cargo.toml
- lib/derive-idol-err/src/lib.rs
- task/net-api/Cargo.toml
- task/net-api/src/lib.rs
- task/sensor-api/Cargo.toml
- task/sensor-api/src/lib.rs
- task/thermal-api/Cargo.toml
- task/thermal-api/src/lib.rs
This removes a bunch of boilerplate for error types which are used in Idol / Hiffy.
(I also removed an unused task from `gimletlet/app-vsc7448`, since it was complaining about being oversized)
> Add derive macro for Idol errors

- Cargo.lock
- app/demo-stm32h7-nucleo/Cargo.toml
- app/gemini-bu/Cargo.toml
- app/gimlet/Cargo.toml
- app/gimletlet/Cargo.toml
- app/psc/Cargo.toml
- app/sidecar/Cargo.toml
- drv/gimlet-hf-server/Cargo.toml
- drv/lpc55-rng/Cargo.toml
- drv/stm32h7-eth/Cargo.toml
- drv/stm32h7-hash-server/Cargo.toml
- drv/stm32h7-hash/Cargo.toml
- drv/stm32h7-i2c-server/Cargo.toml
- drv/stm32h7-i2c/Cargo.toml
- drv/stm32h7-i2c/src/lib.rs
- drv/stm32h7-qspi/Cargo.toml
- drv/stm32h7-spi-server/Cargo.toml
- drv/stm32h7-spi/Cargo.toml
- drv/stm32h7-startup/Cargo.toml
- drv/stm32h7-usart/Cargo.toml
- drv/stm32h7-usart/src/main.rs
- task/net/Cargo.toml
- task/spd/Cargo.toml
- test/tests-gemini-bu/Cargo.toml
- test/tests-stm32h7/Cargo.toml
This commit upgrades crates using stm32h7 version 0.13 to 0.14. The only
code changes required were:
stm32h7-usart - removed an unsafe block that's no longer required
stm32h7-spi - update use of 'is_match_' function to 'is_match'
this resolves #463
> stm32h7: upgrade from 0.13 to 0.14

- Cargo.lock
- app/gemini-bu-rot/src/main.rs
- app/gimlet-rot/src/main.rs
- app/lpc55xpresso/src/main.rs
- stage0/src/main.rs
- task/ping/build.rs
- task/ping/src/main.rs
- test/test-assist/src/main.rs
- test/test-suite/Cargo.toml
- test/test-suite/build.rs
- test/test-suite/src/main.rs
- test/tests-gemini-bu-rot/app.toml
- test/tests-lpc55xpresso/app.toml
Fix some unexpected fallout from recent LPC55 changes. Main changes:
- Fix SWO to run at the same rate as the CPU clock
- Route all interrupts to the non secure world
- Fix some of our testing to use addresses that will not trigger secure faults
> Fix LPC55 fallout

- test/test-idol-api/src/lib.rs
- test/test-suite/src/main.rs
`test_restart`: 420 bytes
`test_borrow_info`: 440 bytes
`main`: 532 bytes
`float_to_decimal_common_shortest`: 8.2 KB
someone please help me budget this, my microcontroller is dying
(fixes the `test/tests-stm32g0/app-g070.toml` build)
> Remove `assert_eq` to avoid float formatting in test suite

- build/util/src/lib.rs
- build/xtask/src/dist.rs
This is a first crack at resolving #482. It improves the error reporting in `toml_from_env` when a config section is missing. It exposes the task's toml key basename (i.e `tasks.spi` exposes `spi`) for tasks to aid with the error hints. The two error cases I mentioned in #482 now result in these errors that tell you what you're probably missing:
Missing task config:
```
error: failed to run custom build command for `drv-stm32h7-spi-server v0.1.0 (/home/artemis/z/hubris/drv/stm32h7-spi-server)`
Caused by:
process didn't exit successfully: `/home/artemis/z/hubris/target/release/build/drv-stm32h7-spi-server-9f4f9b676721a4da/build-script-build` (exit status: 1)
--- stdout
cargo:rustc-cfg=target_board="nucleo-h743zi2"
cargo:rerun-if-env-changed=HUBRIS_BOARD
--- stderr
Error: HUBRIS_TASK_CONFIG …
```
> improve errors for missing config sections

- task/net/src/bsp/gimlet_1.rs
- task/net/src/bsp/sidecar_1.rs
- task/vsc7448/src/bsp/sidecar_1.rs
Otherwise, the `net` and `vsc7448` tasks will crash if the sequencer task reboots.
> Avoid unwrapping while waiting for clock config

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/gimletlet/app.toml
- chips/stm32h7.toml
- drv/stm32h7-usart/src/lib.rs
- task/uartecho/Cargo.toml
- task/uartecho/src/main.rs
Also adds the `uartecho` task to `gimletlet`.
Builds on #475; I pointed this PR to that branch to show only the new changes. Should merge the other first.
> Expand list of uarts/usarts in `chips/stm32h7.toml`

- app/gimletlet/app-vsc7448.toml
- app/gimletlet/app.toml
- drv/ksz8463/src/lib.rs
- drv/stm32xx-sys-api/src/lib.rs
- task/net/Cargo.toml
- task/net/src/bsp.rs
- task/net/src/bsp/gimletlet_mgmt.rs
- task/net/src/bsp/gimletlet_nic.rs
- task/net/src/main.rs
- task/net/src/mgmt.rs
- task/vsc7448/src/bsp/sidecar_1.rs
This PR implements the BSP for the Gimletlet NIC, which breaks out a KSZ8463.
There are also a few drive-by changes:
- Adding `gpio_init_reset_pulse`, to combine a common series of GPIO operations
- Adding a dedicated error type for KSZ8463 errors (and then using it in the driver)
> Implement Gimletlet NIC BSP

- build/xtask/src/clippy.rs
- build/xtask/src/main.rs
This lets you pass extra options to Clippy, e.g.
`cargo xtask clippy --target thumbv7em-none-eabihf -p drv-i2c-devices -- -A clippy::unusual_byte_groupings`
which can be useful in development.
> Allow Clippy to accept extra options after --

- app/gimletlet/app-vsc7448.toml
- app/gimletlet/app.toml
- build/i2c/src/lib.rs
- drv/stm32h7-i2c-server/Cargo.toml
Consider this code in `app/gimlet/rev-b.toml`:
```toml
[[config.i2c.devices]]
bus = "m2"
mux = 1
segment = 4
address = 0x4c
device = "tmp451"
sensors = { temperature = 1 }
description = "T6 temperature sensorrrrr"
refdes = "U491"
```
This generates code that's missing the mux / segment:
```rust
mod i2c_config {
pub mod devices {
...
#[allow(dead_code)]
pub fn tmp451(task: TaskId) -> [I2cDevice; 1] {
[
// T6 temperature sensorrrrr
I2cDevice::new(task,
Controller::I2C2,
PortIndex(0),
None,
0x4c
),
]
}
```
After this PR, the mux and segment are populated:
```rust
#[allow(dead_code)]
pub fn tmp451(task: TaskId) -> [I2cDevice; 1] {
[
// T6 temperature sensorrrrr
I2cDevice::new(task,
Controller::I2C2,
PortIndex(0),
Some((drv_i2c_api::Mux::M1, drv_i2c_api::Segment::S4)),
0x4c
),
]
}
```
(I also …
> Clean up I2C codegen

- drv/gimlet-seq-api/Cargo.toml
- drv/sidecar-seq-api/Cargo.toml
- task/net/Cargo.toml
This was removed back in 8e0b13b86564fc7316428943dfe5fde88bb60ef4, but lingered in a few Cargo.toml files.
> Delete leftover `standalone` feature

- task/net/src/main.rs
Works around https://github.com/smoltcp-rs/smoltcp/issues/599 (not yet
released, but handy if we're going to try to make any updates to smoltcp
based on its current master branch).
> Bind to our specific address, not just a port

- .github/workflows/dist.yml
Apparently https://github.com/dsaltares/fetch-gh-release-asset/pull/36 broke our builds, by saying that "nightly" is a "malformed version." Let's pin it to a known good one, and I'll report upstream.
> pin fetch-gh-release-asset to 0.0.8

- Cargo.lock
- test/test-idol-api/api.idol
- test/test-idol-api/src/lib.rs
- test/test-idol-server/src/main.rs
- test/test-suite/src/main.rs
- test/tests-gemini-bu-rot/app.toml
- test/tests-gemini-bu/app.toml
- test/tests-gimletlet/app.toml
- test/tests-lpc55xpresso/app-a0.toml
- test/tests-lpc55xpresso/app.toml
- test/tests-stm32fx/app-f3.toml
- test/tests-stm32fx/app.toml
- test/tests-stm32g0/app-g070.toml
- test/tests-stm32h7/app-h743.toml
- test/tests-stm32h7/app-h753.toml
This bumps Idolatry to include https://github.com/oxidecomputer/idolatry/pull/15 , and adds unit tests which fail before the bump.
> Add tests and fix for Idolatry multiarg + ssmarshal bug

- Cargo.lock
- Cargo.toml
- app/gemini-bu-rot/app.toml
- app/gimlet-rot/app.toml
- app/lpc55xpresso/app.toml
- build/lpc55pins/Cargo.toml
- build/lpc55pins/src/lib.rs
- drv/lpc55-spi-server/Cargo.toml
- drv/lpc55-spi-server/build.rs
- drv/lpc55-spi-server/src/main.rs
- drv/lpc55-usart/Cargo.toml
- drv/lpc55-usart/build.rs
- drv/lpc55-usart/src/main.rs
Hubris now supports TOML based configuration. Move the settings
for UART and SPI.
> Move pin configuration for lpc55 targets into TOML

- drv/gimlet-hf-api/src/lib.rs
- drv/gimlet-hf-server/src/bsp.rs
- drv/gimlet-hf-server/src/bsp/gemini_bu_1.rs
- drv/gimlet-hf-server/src/bsp/gimlet_a.rs
- drv/gimlet-hf-server/src/bsp/gimlet_b.rs
- drv/gimlet-hf-server/src/bsp/gimletlet_2.rs
- drv/gimlet-hf-server/src/bsp/nucleo_h7x.rs
- drv/gimlet-hf-server/src/main.rs
- idl/gimlet-hf.idol
This updates the host flash server for Gimlet rev B, which includes two separate flashes (see RFDs 163 and 241 for the details).
Specifically:
- Adds a new Idol API to control which of the two flash chips is selected
- Moves per-board configuration from `main.rs` to a `bsp` module / folder, which makes the main code more readable
(I'm not sure if any changes need to be made to `gimlet-seq`)
> Update host flash mux for Gimlet rev B

- .github/workflows/dist.yml
- app/gimlet/rev-a.toml
- app/gimlet/rev-b.toml
- drv/gimlet-seq-server/build.rs
- drv/gimlet-seq-server/src/main.rs
- drv/gimlet-seq-server/src/seq_spi.rs
- The FPGA image filename is no longer hardcoded and is now set in the configuration, which allows rev A and B to reference different bitstreams.
- Same for the register layout JSON file, so they can diverge _if they need to._
- Build output is now called `gimlet-a` or `gimlet-b` instead of just `gimlet` because the latter was hella confusing.
> Gimlet build ergonomics improvements for Rev B

- drv/ksz8463/src/lib.rs
- task/net/src/bsp/gimletlet_mgmt.rs
- task/net/src/bsp/gimletlet_nic.rs
This prevents a crash if the MAC entry is invalid and specifies a port that doesn't exist
> Return early if the MAC entry is empty

- app/gimlet/src/main.rs
- drv/stm32h7-startup/src/lib.rs
This can now distinguish Rev A from Rev B, and (with any luck) both from
any future revs.
- gimlet-a firmware will now refuse to boot on rev B or C+
- gimlet-b firmware will now refuse to boot on rev A or C+
- Board mismatch is detected while all pins are still tristate, not even
the crystal is started.
> gimlet: implement board rev detection.

- app/gimlet/rev-b.toml
This fixes the address of the `V3P3_SYS_A0` rail in the Gimlet Rev B
TOML to match the address specified in RFD 160.
> fix V3P3_SYS_A0 rail to match RFD 160

- README.mkdn
- build/xtask/src/flash.rs
- build/xtask/src/humility.rs
- build/xtask/src/test.rs
I don't have Humility installed on my `$PATH` at the moment, and I anticipate needing to iterate on both Hubris and Humility at the same time, so I added a way to configure the path! I made it so if you provide `HUMILITY_PATH` in the environment, the `cargo xtask humility` command will use that as the path to the Humility binary instead of just `"humility"`.
> Allow humility xtask to set the humility path via HUMILITY_PATH

- drv/gimlet-seq-server/src/main.rs
The ident check we were doing is not sufficient to distinguish the FPGA
images that are flying around -- they all have the same ident. Thus we
run the real risk of the firmware booting with the wrong FPGA image
still configured on the FPGA. This disables (temporarily!) the check
while we build a proper mechanism for distinguishing images.
> gimlet: always reprogram FPGA

- drv/i2c-devices/src/lib.rs
- drv/i2c-devices/src/tmp451.rs
- task/thermal/src/main.rs
This implements a small driver for the TMP451 and adds it to the `task-thermal` sensor list
> Add TMP451 driver

- app/gimlet/rev-a.toml
- app/gimlet/rev-b.toml
- drv/i2c-devices/src/lib.rs
- drv/i2c-devices/src/tse2004av.rs
- task/thermal/src/main.rs
This adds temperature sensing for all of the DIMMs in Gimlet, based on the TSE2004av standard.
(this is orthogonal to the existing `spd` task, because the temperature sensors have their own addresses and register sets, and are actively polled during operation)
> Add temperature sensing to DIMMs

- task/net/src/mgmt.rs
This makes it easier to tell when packets are making it through!
> Add MAC address logging to Gimlet netstack

- app/gimlet-rot/app.toml
RoT does not yet know when to let go of SWD lines to SP, so it needs to
be disabled for now.
> gimlet-rot: fix RoT SWD config but also disable it

- build/xtask/src/dist.rs
- build/xtask/src/flash.rs
As of fairly recently, you need to provide a full flash configuration to
be able to even build an archive for a board. This makes it annoying to
bring up new chips.
This change makes the build system tolerate this condition, and simply
doesn't include flashing instructions in the archive.
> xtask: don't require flashing instructions to build

- build/xtask/src/dist.rs
Noticed that Humility was saying I already had an image flashed when I
changed the start flag on a task. This fixes that.
The main thing left out of image ID generation now is the kernel build
itself, because we have a causality problem (the kernel build includes
the image ID). I'll fix this later.
> xtask: include kernel config in image ID

- sys/userlib/src/units.rs
Derive `PartialOrd` for units to allow expressions such as `if some_value < Volts(0.8)...`. This was suggested in https://github.com/oxidecomputer/hubris/pull/453.
> Derive PartialOrd for userlib units

- build/i2c/src/lib.rs
This fixes warnings when the `validate` task has no targets.
> Add annotations to suppress warnings

- app/psc/app.toml
This fixes the broken PSC build
> Remove unused 'hf' task slot

- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gemini-bu-rot/app.toml
- app/gemini-bu/app.toml
- app/gimlet-rot/app.toml
- app/gimlet/rev-a.toml
- app/gimlet/rev-b.toml
- app/gimletlet/app-mgmt.toml
- app/gimletlet/app.toml
- app/lpc55xpresso/app.toml
- app/psc/app.toml
- app/sidecar/app.toml
- build/xtask/src/dist.rs
This fixes _nearly_ all priority inversions, with the exception that `spd` still messages the lower-priority `i2c_driver` on Gimlet images.
> Fix priority inversions in existing code

- build/phash-gen/src/lib.rs
- lib/phash/src/lib.rs
- sys/abi/src/lib.rs
- sys/kern/build.rs
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/startup.rs
- sys/kern/src/syscalls.rs
This PR improves on IRQ perfect hashing in a few ways:
- Moves the choice of using a perfect hash table or a flat list to the build
system, to reduce the amount of chip-specific logic in the kernel.
- Modifies the flat IRQ list to use binary search instead of iteration.
- Adds a fallback to two-level perfect hash tables if we fail to generate
a single-level table.  This happens with large numbers of IRQs (> 50), which
we may reach!
- Adds abstractions for invalid `InteruptNum` and `InteruptOwner`, then uses
those abstractions instead of checking manually.
- Fixes a potential kernel crash if a task asks to reset an interrupt but the
tables are completely empty.
> Improvements to IRQ tables

- build/xtask/Cargo.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- sys/abi/src/lib.rs
- sys/kern/build.rs
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/syscalls.rs
- sys/kern/src/task.rs
This cleans up some cruft in the abi crate, but the biggest part of the change is best summarized by the message of the top commit:
---
kern: add task index to TaskDesc instead of computing
From time immemorial, the kernel has computed the task index of the
current task during the syscall/ISR entry sequences using a subtraction
and a division. This is problematic on ARMv6-M, where hardware division
is unavailable.
This commit applies mkeeter's idea of just stashing a task index in the
TaskDesc. By adjusting the size of some existing fields that had room to
spare, this doesn't even make the TaskDesc larger.
This knocks 6% or 600+ bytes off the STM32G0 kernel by removing the last
use of division, and should take hundreds of cycles off the Cortex-M0
syscall and interrupt latency. …
> Clean up taskdesc and index handling

- build/xtask/src/main.rs
- build/xtask/src/sizes.rs
I talked with @mkeeter about this yesterday; rather than wait until I've figured out the actions stuff, here's a PR for just the code that calculates the sizes. The gist of it is:
This PR adds two new flags to `cargo xtask sizes`:
* --save, which writes out the sizes to a file
* --compare, which calculates sizes and then compares to a previously
saved file
These files are named after the app, for example,
`demo-stm32f4-discovery.json`, and are written to the project root.
I am open to any and all suggestions about this code. I think it's... fine. I'm not sure what I don't like about it. Also happy to revise the overall strategy.
And one open question: should I put `*.json` in the `.gitignore`, or maybe include something a bit more recognizable in the filename so we could glob it?
> Some work towards a sizing action

- sys/abi/src/lib.rs
- sys/kern/build.rs
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/kipc.rs
- sys/kern/src/profiling.rs
- sys/kern/src/syscalls.rs
- sys/kern/src/task.rs
- sys/kern/src/umem.rs
This makes the kernel (and abi crate) clippy-clean on armv6/7/8m.
> Kernel klippy

- build/i2c/src/lib.rs
- build/xtask/src/clippy.rs
- build/xtask/src/main.rs
- drv/i2c-api/src/lib.rs
- drv/stm32g0-usart/src/main.rs
- drv/stm32h7-eth/src/ring.rs
- drv/stm32h7-i2c-server/src/main.rs
- drv/stm32h7-i2c/src/lib.rs
- drv/stm32h7-i2c/src/ltc4306.rs
- drv/stm32h7-i2c/src/max7358.rs
- drv/stm32h7-spi-server/src/main.rs
- drv/stm32h7-spi/src/lib.rs
- drv/stm32h7-startup/src/lib.rs
- lib/fixedmap/src/lib.rs
- sys/num-tasks/build.rs
- sys/userlib/src/hl.rs
- sys/userlib/src/kipc.rs
- task/hiffy/src/common.rs
- task/hiffy/src/stm32g0.rs
- task/hiffy/src/stm32h7.rs
- task/jefe/src/external.rs
- task/net/build.rs
- task/net/src/server.rs
- task/pong/src/main.rs
Been inspecting Clippy warnings as a background task. This PR gets the stm32g0 and stm32h743-nucleo builds to be Clippy clean, except for some warnings on h7 from Idol generated code.
None of the warnings seemed to signal lurking bugs, but there were a lot of good cleanup suggestions (and a few I suppressed).
> Pseudorandom clippy fixes

- Cargo.lock
- Cargo.toml
- app/demo-stm32h7-nucleo/app-h743.toml
- app/gimlet/rev-a.toml
- app/gimlet/rev-b.toml
- build/util/src/lib.rs
- drv/gimlet-seq-api/Cargo.toml
- drv/gimlet-seq-api/src/lib.rs
- drv/gimlet-seq-server/Cargo.toml
- drv/gimlet-seq-server/src/main.rs
- drv/gimlet-state/Cargo.toml
- drv/gimlet-state/src/lib.rs
- idl/gimlet-seq.idol
- idl/jefe.idol
- task/jefe-api/Cargo.toml
- task/jefe-api/build.rs
- task/jefe-api/src/lib.rs
- task/jefe/Cargo.toml
- task/jefe/build.rs
- task/jefe/src/main.rs
- task/net/Cargo.toml
- task/net/src/bsp/gimlet_1.rs
This adds a system state tracking API to Jefe. Currently the only things that can be done with that API are:
- Read the current state
- Alter the state
- Get notified if someone alters the state.
In support of that third one, Jefe now has configuration: it can be asked to poke tasks when the state changes.
This PR also includes `gimlet-seq-server` support for posting sequencing state to Jefe, and corresponding client code in `net` to use Jefe's state instead of directly contacting the sequencer task.
> jefe system state API

- build/i2c/src/lib.rs
- build/lpc55pins/src/lib.rs
- build/net/src/lib.rs
- drv/gimlet-seq-server/build.rs
- drv/lpc55-spi-server/build.rs
- drv/lpc55-swd/build.rs
- drv/lpc55-usart/build.rs
- drv/stm32h7-spi-server/build.rs
- task/jefe/build.rs
serde+toml by default will tolerate arbitrary unknown fields, producing
ground fertile for errors such as typos or pasting in the wrong section.
While fixing serde+toml to not do this by default is _awfully tempting_
this change instead goes through and decorates all of our config structs
with annotations to suppress the behavior.
While I was at it, I have applied rename_all = kebab-case to all config
structs that (1) were missing it and (2) don't have underscores in any
field names, so it's a no-op. This is to prepare for the addition of
other field names in the future. I'll be going through and kebabing the
rest in a bit.
> Apply serde(deny_unknown_fields) to all config structs

- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
The `ping` task crashes (intentionally).  If it's a higher priority than other tasks, it can preempt them forever (which is unintentional).
> Reduce priority of ping

- Cargo.lock
- drv/vsc-err/Cargo.toml
- drv/vsc-err/src/lib.rs
- drv/vsc7448/Cargo.toml
- drv/vsc85xx/Cargo.toml
- idl/net.idol
- task/net-api/Cargo.toml
- task/net/Cargo.toml
- task/net/src/server.rs
- task/net/src/vlan.rs
- task/vsc7448/Cargo.toml
This simplifies the return type of the (infallible) `smi_read/write` functions. Once they're no longer returning a `NetError`, we can simplify the `VscError` type as well, then prune unused features!
> Clean net features

- Cargo.lock
- build/xtask/Cargo.toml
- build/xtask/src/dist.rs
- build/xtask/src/sizes.rs
This is a minor QoL improvement: it turns out that `colored` already checks whether the output should have colors enabled, so we can remove a bunch of boilerplate.
> Simplify color printing

- drv/i2c-devices/src/lib.rs
- drv/i2c-devices/src/pca9538.rs
A minimal driver for the PCA9538 GPIO expander. The API is modeled on the `sys-gpio` API we use elsewhere.
> Add driver for PCA9538 GPIO expander

- drv/fpga-api/Cargo.toml
- drv/fpga-server/Cargo.toml
- drv/gimlet-seq-api/Cargo.toml
- drv/sidecar-mainboard-controller-api/Cargo.toml
- drv/sidecar-mainboard-i2c-emulator/Cargo.toml
- drv/sidecar-seq-api/Cargo.toml
- drv/sidecar-seq-server/Cargo.toml
- drv/update-api/Cargo.toml
`cargo xtask check` does not exist, so we don't need special metadata to support it.
> Remove unused build metadata

- Cargo.lock
- app/sidecar/app.toml
- drv/fpga-api/src/lib.rs
- drv/fpga-devices/Cargo.toml
- drv/fpga-devices/src/ecp5_spi_mux_pca9538.rs
- drv/fpga-devices/src/lib.rs
- drv/fpga-server/Cargo.toml
- drv/fpga-server/build.rs
- drv/fpga-server/src/main.rs
- drv/sidecar-mainboard-controller-api/src/lib.rs
- drv/sidecar-mainboard-controller-api/src/tofino2.rs
- idl/fpga.idol
This diff implements the following:
- Allow a `fpga-server` task to server requests for multiple FPGA devices
- Add a driver for hardware found on the QSFP x32 board, where multiple ECP5
devices are controlled using a mux'd SPI link and an I2C GPIO expander
> QSFP x32 FPGA driver, server multiple device from fpga-server

- build/xtask/src/config.rs
This flag creates an allowlist of nightly features. By adding this to
the build, we'll get a failure if someone adds a new one, which gives us
the opportunity to really consider if we should be doing that.
Example output:
```
Caused by:
the feature `foo_bar` is not in the list of allowed features:
["not_a_real_feature", "baz"]
Error: failed to build jefe
```
Fixes #311
I only tried building one app here so we'll see if this breaks, if so I can push more commits.
> Use -Zallow-features to ensure we don't add more

- drv/fpga-devices/src/ecp5_spi_mux_pca9538.rs
Calling `SpiDevice::lock` asserts the chip select line.  Because the chip select line is passed through the SPI mux, we need to configure the mux beforehand; otherwise, the CS line will be pulsed for the _other_ FPGA when changing targets.
This fixes [hardware-qsfp-x32#36](https://github.com/oxidecomputer/hardware-qsfp-x32/issues/36) and [humility#191](https://github.com/oxidecomputer/humility/issues/191), tested on the `niles` Sidecar.
> Configure mux before locking the SPI device

- Cargo.lock
- test/tests-gimletlet/Cargo.toml
Noticed this was added as a side effect of https://github.com/oxidecomputer/hubris/pull/659#discussion_r930337746 (`tests-gimletlet` wasn't previously in the manifest, so `stm32h7 0.13.0` wasn't in `Cargo.lock`).
> Bump straggler still on stm32h7 0.13.0 to 0.14.0

- Cargo.lock
- app/demo-stm32f4-discovery/app-f3.toml
- app/demo-stm32f4-discovery/app.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gemini-bu/app.toml
- app/gimlet/rev-b.toml
- app/gimletlet/app.toml
- app/sidecar/app.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- drv/lpc55-romapi/src/lib.rs
- drv/sidecar-seq-server/src/main.rs
- drv/stm32g0-usart/Cargo.toml
- drv/stm32xx-sys/src/main.rs
- rust-toolchain.toml
- stage0/src/main.rs
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/lib.rs
- sys/userlib/src/lib.rs
- sys/userlib/src/macros.rs
- task/jefe/Cargo.toml
- task/ping/src/main.rs
- task/uartecho/src/main.rs
- test/test-assist/Cargo.toml
- test/test-runner/Cargo.toml
The decision to re-purpose the `asm` feature flag [was changed](https://github.com/rust-lang/rust/issues/72016#issuecomment-1021679663), which is great. Let's get us on a version of the toolchain that uses the new flags.
~~This won't be quite ready just yet; I tested using the f4 demo; gonna use one CI run to show me what else breaks so I can fix it up.~~ Now ready!
> bump toolchain to last night's nightly

- drv/stm32h7-eth/src/lib.rs
- idl/net.idol
- task/monorail-server/src/server.rs
- task/net-api/src/lib.rs
- task/net/Cargo.toml
- task/net/src/bsp/gimlet_1.rs
- task/net/src/bsp/gimletlet_mgmt.rs
- task/net/src/bsp/gimletlet_nic.rs
- task/net/src/bsp/nucleo_h7.rs
- task/net/src/bsp/psc_1.rs
- task/net/src/bsp/sidecar_1.rs
- task/net/src/main.rs
- task/net/src/mgmt.rs
- task/net/src/server.rs
- task/net/src/server_basic.rs
- task/net/src/server_vlan.rs
- task/udpecho/src/main.rs
This is initial infrastructure for a `humility net` subcommand, to query the SP's perspective on the management network.
These functions are distinct from the `smi_read/write` commands, since we need to
- change the page
- do a read/write
without anything else interrupting us.
In passing, I refactored the "VLAN Server" vs "Basic Server" distinction, moving them into better-named files, then added `server.rs` for a common trait.  This removes duplicate code from the two Idol implementations.  Unfortunately, moving `server.rs -> server_basic.rs`, then re-adding `server.rs` makes the diff unhappy; sorry about that!
In addition, the new API uses register types from the `vsc7448_pac` crates, so that crate is now non-optional.  This means I finally removed the `enum SmiClause22Register`, which …
> Add `net` PHY read/write API

- app/gimletlet/app.toml
- idl/net.idol
- task/mgmt-gateway/src/main.rs
- task/net-api/src/lib.rs
- task/net/src/main.rs
- task/net/src/server.rs
- task/net/src/server_basic.rs
- task/net/src/server_vlan.rs
- task/udpecho/src/main.rs
This fixes the ability of an external UDP source crashing `net` clients with `ClientError::BadLease` by sending packets in between their lease size and the max size allowed by the `net` task.
Unfortunately it continues to pour fuel on the fire of `server.rs` + `vlan.rs`.
> Add `large_payload_behavior` arg to `net::recv_packet()`

- Cargo.lock
This lets us do `humility monorail dump`, which needs `Expand32` and `Collect32`
> Bump HIF to 0.3.1 for new opcodes

- task/mgmt-gateway/src/main.rs
- task/net-api/src/lib.rs
- task/net/src/server_basic.rs
- task/net/src/server_vlan.rs
- task/udpecho/src/main.rs
This fixes the bug (or at least undocumented, surprising behavior) that
if a caller passed `LargePayloadBehavior::Fail` and the net task
returned `RecvError::PayloadTooLarge`, the overlarge packet was
_discarded_ in the process, and the caller could not retry with a larger
buffer.
> Remove `LargePayloadBehavior::Fail`

- app/sidecar/app.toml
- drv/sidecar-front-io/src/phy_smi.rs
- drv/vsc-err/src/lib.rs
- drv/vsc7448/src/lib.rs
- drv/vsc7448/src/miim_phy.rs
- drv/vsc7448/src/spi.rs
- drv/vsc85xx/src/lib.rs
- drv/vsc85xx/src/viper.rs
- lib/unwrap-lite/src/lib.rs
- task/monorail-server/src/bsp/sidecar_1.rs
- task/net/src/bsp/nucleo_h7.rs
- task/net/src/miim_bridge.rs
These changes, all together, free up
- 133,248 bytes of Flash
- 1,280 bytes of RAM
The bulk of the savings is from the monomorphization-control pattern I applied to the vsc crates, a change which should be stable across compiler revs and reduce the rate of code growth as more logic is added.
> Sidecar flash image size improvements

- app/sidecar/app.toml
- chips/stm32h7-nonredundant/chip.toml
- chips/stm32h7-nonredundant/memory.toml
- chips/stm32h7-nonredundant/openocd.cfg
- chips/stm32h7-nonredundant/openocd.gdb
This allows sidecar to use both banks of the STM32H7 flash for its
images, which in turn allows the use of FPGA bitstreams that are larger
than ~100kiB. I've tested this with up to 512 kiB of bitstreams and
there's space to spare.
Note that this destroys sidecar's ability to do online updates or have
redundant firmware images. So, this is explicitly intended as a
short-term hack to unblock bringup while we get the external flash
online.
> sidecar: hack to allow larger bitstreams for now

- task/idle/Cargo.toml
- task/idle/src/main.rs
This avoids using WFI to enter a lower power state. This appears to be important to be able to debug the stm32g030.
> idle: add insomniac mode

- app/gimletlet/app.toml
- chips/stm32h7-nonredundant/chip.toml
- chips/stm32h7/chip.toml
- drv/stm32h7-update-server/src/main.rs
After switching from `cr.write(..)` to `cr.modify(..)` to get interrupts working, I noticed bank erasing was significantly faster. That doesn't make sense if the only change were switching from polling to an interrupt; after some poking at the cr register, I realized the previous `cr.write(..)` was clobbering the `psize()` field, setting the flash parallelism to 8 bits (as opposed to the value of `0b11`, 64 bits, when update server starts). 
With that realization, I changed the `cr.write(..)` call in `write_word(..)` to set `psize(0b11)` explicitly. Maybe changing that call to `.modify(..)` would be better? I'm not sure.
Prior to this change, my times to perform an update over UDP were ~13s for bank erase and then ~2.3s to write the new image. As of this branch, those times drop to ~5s …
> update-server bank erase: Wait for interrupt instead of polling

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gimlet/rev-b.toml
- app/gimletlet/app-mgmt.toml
- app/gimletlet/app.toml
- app/psc/app.toml
- app/sidecar/app.toml
- lib/mutable-statics/Cargo.toml
- lib/mutable-statics/src/lib.rs
- task/net/Cargo.toml
- task/net/src/buf.rs
- task/net/src/main.rs
- task/net/src/server_basic.rs
- task/net/src/server_vlan.rs
Eliminates `ServerStorage`, moving its buffers to `static` storage.
As a drive-by, also moves the `mutable_statics` macro to its own crate.
> Reduce stack usage in `net` task

- build/kernel-link.x
- stage0/build.rs
- stage0/src/main.rs
While not a true 'hubris' image, adding a hubris ID to stage0 lets
it be used with some humility commands.
> Add Hubris ID to stage0

- drv/gimlet-seq-server/Cargo.toml
- drv/gimlet-seq-server/build.rs
- drv/sidecar-front-io/Cargo.toml
- drv/sidecar-front-io/build.rs
- drv/sidecar-mainboard-controller/Cargo.toml
- drv/sidecar-mainboard-controller/build.rs
- lib/gnarle/Cargo.toml
- lib/gnarle/src/lib.rs
This removes a bit of duplicate code from FPGA `build.rs` files.
Closes #630
> Add `compress_to_vec` to Gnarle

- task/udpbroadcast/src/main.rs
This task is only used for network debugging, so might as well make it robust against errors.
> Don't panic on UDP broadcast failure

- README.mkdn
Just a tiny thing, but since it is first command documented after flashing it takes 5 minutes too long to figure out why it's not working :smile:
> README: Fix humility tasks example

- Cargo.lock
- drv/ksz8463/Cargo.toml
- drv/ksz8463/src/lib.rs
- drv/ksz8463/src/registers.rs
- drv/monorail-api/Cargo.toml
- drv/monorail-api/src/lib.rs
- drv/vsc85xx/src/vsc85x2.rs
- idl/monorail.idol
- idl/net.idol
- task/net-api/Cargo.toml
- task/net-api/src/lib.rs
- task/net/Cargo.toml
- task/net/src/bsp/gimlet_1.rs
- task/net/src/bsp/gimletlet_mgmt.rs
- task/net/src/bsp/gimletlet_nic.rs
- task/net/src/bsp/nucleo_h7.rs
- task/net/src/bsp/psc_1.rs
- task/net/src/bsp/sidecar_1.rs
- task/net/src/main.rs
- task/net/src/mgmt.rs
- task/net/src/server.rs
- task/net/src/server_basic.rs
- task/net/src/server_vlan.rs
This PR implements a set of new APIs for the `net` task, which allow us to
- Read the KSZ8463 MAC table
- Read registers on the KSZ8463
- Get the system's MAC address (from which the IP address can be inferred)
- Get the management network link status (when applicable)
- Read management network counters status (when applicable)
This is all infrastructure for the upcoming `humility net` subcommand.
> New `net` APIs

- Cargo.lock
- app/demo-stm32g0-nucleo/app-g031.toml
- app/demo-stm32g0-nucleo/app-g070.toml
- app/demo-stm32g0-nucleo/app-g0b1.toml.noworky
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gemini-bu/app.toml
- app/gimlet/rev-b.toml
- app/gimletlet/app-meanwell.toml
- app/gimletlet/app-mgmt.toml
- app/gimletlet/app-sidecar-emulator.toml
- app/gimletlet/app-vsc7448.toml
- app/gimletlet/app.toml
- app/psc/app.toml
- app/sidecar/app.toml
- drv/stm32xx-sys/Cargo.toml
- drv/stm32xx-sys/src/main.rs
- idl/jefe.idol
- task/jefe-api/Cargo.toml
- task/jefe-api/src/lib.rs
- task/jefe/Cargo.toml
- task/jefe/build.rs
- task/jefe/src/main.rs
The stm32h7 branch is fully implemented. stm32g0 has primitive support (the raw reset register is reported, but it is not mapped to one of the logical `ResetReason`s).
`set_reset_reason` is (optionally) restricted to a single task using the same style as `Jefe.set_state()`, until something like #710 is available.
> Add "reason for most recent reset"

- app/gemini-bu-rot/app.toml
- app/gimlet-rot/app.toml
- drv/lpc55-gpio-api/src/lib.rs
- drv/lpc55-swd/build.rs
- drv/lpc55-swd/src/main.rs
- drv/lpc55-syscon/src/main.rs
Drastically improved from ~10 minutes to closer to 30 seconds
Ticks before:
```
0   68        1        1 Start(0xc)
1  130        1        1 End(0x9cb18)
```
Ticks after
```
0   68        1        1 Start(0x3)
1  130        1        1 End(0x54ae)
```
> Improve RoT -> SP SWD performance

- Cargo.lock
- sys/userlib/Cargo.toml
We were rebuilding PACs twice for most applications, once for tasks
where the inline-asm feature is set somewhere in their dependency graph,
and once for tasks where it isn't. The inline-asm feature is thankfully
going away in cortex-m 0.8 (it should be a build-time capability
detection rather than a user-visible feature), but for now, we'll just
force it on in the one library that all tasks include: userlib.
This knocks a minute or more off a clean build for stm32h7, where the
PAC is particularly expensive.
> userlib: add cortex-m dep to force inline-asm feature.

- Cargo.lock
- build/xtask/Cargo.toml
We have some API changes to the lpc55_support repo pending that require
coordinated changes in xtask. To keep from breaking hubris during the
merge this commit pins xtask to the current HEAD. After the API changes
are merged into lpc55_support, another PR will go into hubris to use the
new API & update the pinned git commit accordingly.
> xtask: Pin to Cargo.toml to current HEAD of lpc55_support repo.

- app/gimlet/rev-b.toml
- chips/stm32h7/memory-large.toml
By default, apps on stm32h7 are mapped into a 128 kiB RAM on the
processor's local bus. This is great because it's zero-wait-state.
However, there are a lot more RAMs than that. This adds an alternate
memory file for mapping all of an application into the 512 kiB AXI SRAM,
which has more wait states (though not many more) but is 4x larger.
This is in lieu of a smarter memory allocator that can distribute across
RAMs based on their properties, which we'll want to do eventually.
> stm32h7: allow optional mapping into AXI SRAM

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gimlet/rev-b.toml
- app/psc/app.toml
- app/sidecar/app.toml
- build/xtask/src/config.rs
- chips/stm32h7-nonredundant/memory-large.toml
- sys/userlib/src/kipc.rs
- task/udpbroadcast/Cargo.toml
- task/udpbroadcast/src/main.rs
- task/udprpc/Cargo.toml
- task/udprpc/src/main.rs
This PR adds a relatively minimal `task-udprpc`, which accepts specially-constructed UDP packets and executes them as Hiffy calls.
It still needs some clean-up, so I'm marking it as a draft for now.
The Humility side is implemented in [humility#216](https://github.com/oxidecomputer/humility/pull/216)
> UDP RPC task

- task/net/src/mgmt.rs
It turns out the "Tx = input, Rx = output" MAC signal naming conventional also applies to these counters.
Closes #667
> Fix VSC8562 Tx/Rx counters

- Cargo.lock
- app/gimletlet/app.toml
- drv/stm32h7-update-server/src/main.rs
- drv/update-api/src/lib.rs
- task/mgmt-gateway/Cargo.toml
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_handler.rs
This also includes a change to move the update server block size into `update_api` (underneath a chip-specific module). I did not remove the `block_size` runtime API call, although it's no longer necessary for clients, since they can grab the constant directly from `update_api`.
> mgmt-gateway: add support for update and reset

- build/xtask/src/dist.rs
By default, objcopy will fill gaps in sections with `0x00`. The flash
programming sequence on the STM32 will not program the gaps and will
leave them in the default state of `0xff`. This results in a mismatch
between the generated binary and flash. From a running program
perspective this is fine but it results in incorrect calculations of
expected values in flash. Fix this by filling the gap with `0xff`.
> Fill gaps in binaries with `0xff`

- Cargo.lock
- app/gemini-bu-rot/stage0.toml
- app/gimlet-rot/stage0.toml
- app/lpc55xpresso/stage0.toml
- build/xtask/Cargo.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
Names of variables / parameters have been kept as similar to those from
the spec as possible. These names are pretty awkward but we preserve
them as best we can for consistency.
NOTE: This PR depends on API changes in the lpc55_support repo. There's an open PR with the required changes in lpc55_support that must be merged first: https://github.com/oxidecomputer/lpc55_support/pull/19
I've marked this PR as an RFC since it configures xtask to use a topic branch from my fork of the lpc55_support repo with the API changes required to set these bits. It should not be merged until the associated changes in lpc55_support have been reviewed & merged.
> xtask: Add dice configuration options to 'Signing' table.

- app/demo-stm32h7-nucleo/src/main.rs
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/profiling.rs
It's now possible, if somewhat involved, to keep track of which task is
making syscalls / using the CPU.
> kern: add context switch hook to profiling support.

- drv/stm32h7-update-server/src/main.rs
- drv/update-api/src/lib.rs
- idl/update.idol
- task/hiffy/src/common.rs
- task/mgmt-gateway/src/mgs_handler.rs
- Prep now requires an image type to indicate which image is being
updated.
- Add an `abort_update` function if the calling task decides they
need to stop an update.
- Added a few more error types to better specify exactly what may have
gone wrong.
> Extend the update API

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gemini-bu/app.toml
- app/gimlet/rev-b.toml
- app/gimletlet/app-meanwell.toml
- app/gimletlet/app-mgmt.toml
- app/gimletlet/app-sidecar-emulator.toml
- app/gimletlet/app-vsc7448.toml
- app/gimletlet/app.toml
- app/psc/app.toml
- app/sidecar/app.toml
- build/util/src/lib.rs
- task/jefe/build.rs
- task/jefe/src/main.rs
This allows us to remove the by-hand check for `state-owner` and `reset-reason-owner` in jefe's config and server implementation, in favor of passing the list of allowed callers to idolatry and letting it put the check in the generated code (via https://github.com/oxidecomputer/idolatry/pull/22).
While I was in here, I added restrictions on `request-reset` (to `hiffy`/`mgmt-gateway`), fixing #699.
Callers that attempt to perform operations that they aren't allowed to will now see `AccessViolation` errors instead of `UnknownOperation`.
> Restrict operation callers in app.toml

- Cargo.lock
- app/gimletlet/app.toml
- task/mgmt-gateway/Cargo.toml
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_handler.rs
Update payloads and serial console packets are now serialized as raw
data _after_ a hubpack-encoded message, instead of the data being
embedded as part of the hubpack message. Formerly we were required to
allocate several moderately-sized arrays on the stack and copy data
unnecessarily; now the raw data is borrowed from the receive buffer we
pass to `net`, which requires no extra copies or stack allocation of
large arrays.
This is the hubris half of https://github.com/oxidecomputer/omicron/pull/1645, which did the MGS side of this work.
We get significant improvements in flash and stack, and a modest improvement in ram (although it doesn't look like it at first glance). Before this PR:
```
PROGRAM        REGION  USED   SIZE   LIMIT
mgmt_gateway   flash   26764  32768  32768
ram     6444 …
```
> mgmt-gateway: Update to new MGS serialization of large messages

- Cargo.lock
- task/mgmt-gateway/Cargo.toml
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_handler.rs
This is the hubris half to https://github.com/oxidecomputer/omicron/pull/1651 that lets us address a few lingering TODOs:
1. Attaching and detaching an MGS instance to a particular SP's proxied serial console are now explicit messages; previously attaching was implicit when MGS sent data, and detaching was implicit when a new MGS instance attached, neither of which was ideal.
2. MGS -> SP serial console data packets now include an offset, allowing the SP to detect and ignore any resent UDP packets. Previously if MGS resent a serial console data packet because it missed an ack, the SP had no way to know it had already seen it, and it would forward it along the uart a second time.
3. SP -> MGS serial console data packets now include an offset. We do not ack SP -> MGS messages, both because …
> mgmt-gateway: Refine serial console messages

- Cargo.lock
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_handler.rs
Builds on #737. No functional changes. Moves usart logic out of main and into `mgs_handler` (which will become the gimlet-specific MGS handler in a subsequent PR), and renames a few methods. Review can be light.
> Refactor in prep for gimlet/sidecar/psc variants of mgmt-gateway

- app/gimlet/rev-b.toml
- app/gimletlet/app.toml
- app/psc/app.toml
- app/sidecar/app.toml
- task/mgmt-gateway/Cargo.toml
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_common.rs
- task/mgmt-gateway/src/mgs_gimlet.rs
- task/mgmt-gateway/src/mgs_psc.rs
- task/mgmt-gateway/src/mgs_sidecar.rs
Builds on #738. The bulk of the code changes here are to break `mgs_handler.rs` up into gimlet-specific parts (serial console proxying) and common parts (updating the SP, etc.); the latter have moved to `mgs_common.rs`. What was `mgs_handler` is now `mgs_gimlet`, and this PR adds new `mgs_sidecar` and `mgs_psc` submodules (that only support the functionality provided by `mgs_common`). Exactly one of the three modules must be selected via the appropriate cargo feature. Failing to enable one feature (or enabling more than one) will result in a compilation error.
> Add mgmt-gateway to gimlet/sidecar/psc builds

- Cargo.lock
- task/mgmt-gateway/Cargo.toml
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_common.rs
- task/uartecho/Cargo.toml
- task/uartecho/src/main.rs
Because `heapless` data structures' `::new()` methods are const, we can
put them into statics directly. This allows us to reduce all our
`mutable_statics!` usage to plain `[u8; N]` arrays, avoiding any stack
issues related to https://github.com/oxidecomputer/hubris/issues/741.
> Replace tinyvec::ArrayVec with heapless::{Vec,Deque}.

- task/hiffy/src/common.rs
- task/hiffy/src/generic.rs
- task/hiffy/src/lpc55.rs
- task/hiffy/src/stm32h7.rs
This is infrastructure for allowing `humility` to make _generic_ calls that require a lease, rather than having to special-case them (e.g. `qspi_page_program`).
> Add `SendLeaseRead/Write` functions

- Cargo.lock
- drv/gimlet-hf-api/Cargo.toml
- drv/gimlet-hf-api/src/lib.rs
- drv/gimlet-hf-server/src/main.rs
- drv/qspi-api/Cargo.toml
- drv/qspi-api/src/lib.rs
- drv/stm32h7-qspi/Cargo.toml
- drv/stm32h7-qspi/src/lib.rs
- idl/gimlet-hf.idol
Also adds a couple constants to its API describing the sizes of `page_program()` and `sector_erase()` operations.
All of these additions will be used by `mgmt-gateway` shortly in updating the host boot flash.
> Add `capacity()` idol call to gimlet-hf-server.

- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_common.rs
- task/mgmt-gateway/src/mgs_gimlet.rs
- task/mgmt-gateway/src/mgs_psc.rs
- task/mgmt-gateway/src/mgs_sidecar.rs
- task/mgmt-gateway/src/update_buffer.rs
This PR extracts `UpdateBuffer` from `mgs_common.rs` (where it's used to buffer incoming an incoming SP image) and makes it generic over:
* the block size
* the function to write a single block
* the function to finalize after the last block is written
which will allow it to be used for both SP updates (in this PR) and host boot flash updates (in a subsequent PR), and hopefully other update components in the future.
One design choice that I'm not sure about - carving it out like this assumes separate buffers for every component we want to update. That theoretically allows multiple component updates to be streamed in simultaneously, but it also may end up being prohibitive in memory usage, because it means we set a side a component-update-block-sized buffer for each one. If we end up …
> mgmt-gateway refactor: extract generic `UpdateBuffer`

- Cargo.lock
- lib/dice/Cargo.toml
- stage0/Cargo.toml
This can be reverted once upstream merges & releases https://github.com/ycrypto/salty/pull/26 or something similar.
> Change the Salty library we use to an oxide fork with zeroize.

- app/rot-carrier/stage0.toml
This change was overlooked in the initial push of the self signed DeviceId commit & is required to use DICE on the rot-carrier.
> rot-carrier: Enable DICE feature.

- Cargo.lock
- app/sidecar/app.toml
- build/xtask/Cargo.toml
- build/xtask/src/auxflash.rs
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- build/xtask/src/main.rs
- drv/auxflash-api/Cargo.toml
- drv/auxflash-api/build.rs
- drv/auxflash-api/src/lib.rs
- drv/auxflash-server/Cargo.toml
- drv/auxflash-server/README.mkdn
- drv/auxflash-server/build.rs
- drv/auxflash-server/src/main.rs
- idl/auxflash.idol
This is the first step of implementing RFD 311.  It does two things:
- Adds a small `auxflash` task to the Sidecar image, which can read, write, and validate checksums of slots in the auxiliary flash chip
- Inserts `[[auxflash.blobs]]` into the config file, which specifies files to be packed into `auxi.tlvc` in the resulting Hubris archive
> Add `auxflash` task and blob generation

- Cargo.lock
- build/fpga-regmap/src/lib.rs
Addresses are flattened with increasingly long prefixes (based on `addrmap`'s `inst_name`); the register map itself is split into nested modules.
Fixes #768
> Add support for `Addrmap` to `fpga-regmap`

- lib/dice/src/handoff.rs
- stage0/src/dice.rs
This is intended as a more robust mechanism for the task consuming the DICE artifacts to identify valid values.
> lib-dice: Add magic value to handoff structure.

- Cargo.lock
- lib/dice/Cargo.toml
- lib/dice/src/alias_cert_tmpl.rs
- lib/dice/src/cert.rs
- lib/dice/src/deviceid_cert_tmpl.rs
- lib/dice/src/lib.rs
- stage0/src/dice.rs
This simplifies the get / set functions in the Cert trait. This resolves #747
> lib-dice: Replace START / END with Range in cert templates.

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimletlet/app.toml
- task/mgmt-gateway/Cargo.toml
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_common.rs
- task/mgmt-gateway/src/mgs_gimlet.rs
- task/mgmt-gateway/src/mgs_psc.rs
- task/mgmt-gateway/src/mgs_sidecar.rs
- task/mgmt-gateway/src/update_buffer.rs
This tracks the corresponding changes to MGS messaging merged in https://github.com/oxidecomputer/omicron/pull/1684:
1. `UpdateStart` has been broken into `UpdatePrepare` and `UpdatePrepareStatus` (which MGS will continue to send periodically until we respond that preparation is done), allowing for updates that have a potentially-long running prep step (like updating host flash, which can take up to several minutes to erase!).
2. Update messages now include a stream-id that we use to correlate related messages; we reject update messages that don't match our current stream ID.
3. Add handling for the new `UpdateAbort` abort message to cancel an in-progress update.
By far the most complex bit of this is 1: I've moved setting the system timer out of `mgs_gimlet` (which previously set it only …
> mgmt-gateway: update host flash

- Cargo.lock
- drv/auxflash-server/Cargo.toml
- drv/auxflash-server/src/main.rs
- idl/auxflash.idol
The RFD had a mix of 1 MiB and 2 MiB.  This standardizes on 2 MiB, but makes it board-dependent (and adds an API to query it!)
> Fix auxflash slot size

- Cargo.lock
This makes Idolatry-generated APIs Clippy clean (hopefully)
> Bump Idolatry

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimletlet/app.toml
- task/mgmt-gateway/Cargo.toml
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_common.rs
- task/mgmt-gateway/src/mgs_gimlet.rs
- task/mgmt-gateway/src/mgs_psc.rs
- task/mgmt-gateway/src/mgs_sidecar.rs
- task/mgmt-gateway/src/update_buffer.rs
This is the companion to the larger MGS change in https://github.com/oxidecomputer/omicron/pull/1714. From the SP's side,
the changes are relatively minor:
1. We removed "update prepare status" in favor of the more general "update status"
2. Update messages now always include an update ID, and for "update abort" we only abort if the ID matches our current in-progress update.
> mgmt-gateway: Add update status and update IDs

- Cargo.lock
- app/gimlet-rot/Cargo.toml
- app/lpc55xpresso/Cargo.toml
- app/rot-carrier/Cargo.toml
- drv/lpc55-gpio/Cargo.toml
- drv/lpc55-i2c/Cargo.toml
- drv/lpc55-rng/Cargo.toml
- drv/lpc55-romapi/Cargo.toml
- drv/lpc55-spi-server/Cargo.toml
- drv/lpc55-spi/Cargo.toml
- drv/lpc55-swd/Cargo.toml
- drv/lpc55-syscon/Cargo.toml
- drv/lpc55-usart/Cargo.toml
- drv/user-leds/Cargo.toml
- lib/dice/Cargo.toml
- lib/lpc55-usart/Cargo.toml
- stage0/Cargo.toml
- test/tests-gemini-bu-rot/Cargo.toml
- test/tests-lpc55xpresso/Cargo.toml
After sending a patch upstream to the lpc55-pac adding a missing feature yesterday I took a swing at upgrading to the latest version of this crate. This was an attempt to determine how painful an upgrade will be if lpc55-pac merges my PR and we then upgrade to benefit. Going from 0.3 to 0.4 was thankfully trivial.
> lpc55-pac: Bump version from 0.3.0 to 0.4.

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimletlet/app.toml
- app/sidecar/rev-a.toml
- drv/mock-gimlet-seq-server/Cargo.toml
- drv/mock-gimlet-seq-server/build.rs
- drv/mock-gimlet-seq-server/src/main.rs
- idl/gimlet-seq.idol
- task/mgmt-gateway/Cargo.toml
- task/mgmt-gateway/src/main.rs
- task/mgmt-gateway/src/mgs_common.rs
- task/mgmt-gateway/src/mgs_gimlet.rs
- task/mgmt-gateway/src/mgs_psc.rs
- task/mgmt-gateway/src/mgs_sidecar.rs
The main change in this is that the `SpHandler` trait now has `power_state()` and `set_power_state()` methods, and our gimlet/sidecar handlers attempt to implement them faithfully. (The psc handler implements them trivially.)
Other changes that came along for the ride (the first is not related, but is a tiny cleanup):
1. Removed the `Sys...` prefix in a handful of places we were still referring to `SysReset`
2. Added a `mock-gimlet-seq-server` task and added it to gimletlet's app.toml to allow test work of the power state APIs on gimletlet
> mgmt-gateway: Handle requests to get/set power state

- Cargo.lock
This pulls in https://github.com/oxidecomputer/idolatry/pull/27
> Bump Idol version to allow non-u8 leases

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimletlet/app.toml
- drv/mock-gimlet-seq-server/Cargo.toml
- drv/mock-gimlet-seq-server/src/main.rs
- lib/host-sp-messages/src/lib.rs
- task/host-sp-comms/Cargo.toml
- task/host-sp-comms/src/main.rs
- task/jefe/build.rs
We reboot the host in response to a reboot request, and we power off the host in response to a power off request. In both cases, we do _not_ send a response on the uart.
The diff looks larger than it actually is because some things moved around and `git diff` doesn't handle it particularly well; it might be clearer to step through the commits individually.
This builds on #795 and should be merged after it.
A general comment - I'm not in love with the way the sequencer presents `PowerState` (and in particular the additive states beyond A0/A2). I asked about this in the hubris channel some, and am curious if we'd be better served if we modeled it more like
```rust
enum PowerState {
A0(A0AdditiveState),
A1,
A2(A2AdditiveState),
}
```
where `AxAdditiveState` could be an enum or a bit mask? …
> host-sp-comms: implement rebooting the host

- drv/vsc85xx/src/lib.rs
This lets us enable [`faster-mdio`](https://github.com/oxidecomputer/hubris/compare/faster-mdio), which speeds up Sidecar initialization.
> Use correct timeout for PHY command

- Cargo.lock
- drv/auxflash-api/Cargo.toml
- drv/auxflash-api/src/lib.rs
- drv/auxflash-server/Cargo.toml
- drv/auxflash-server/src/main.rs
- idl/auxflash.idol
* Re-export page/sector size from `auxflash-api`
* Refuse to write to the currently-active slot
* Only scan for the active slot once on task start
- Add new `get_active_slot()` idl function
- `scan_and_get_active_slot()` is documented as deprecated; it no longer scans and now just calls `get_active_slot()`
> Minor auxflash API updates

- Cargo.lock
- app/sidecar/rev-a.toml
- drv/auxflash-api/Cargo.toml
- drv/auxflash-api/build.rs
- drv/auxflash-api/src/lib.rs
- drv/auxflash-server/Cargo.toml
- drv/auxflash-server/build.rs
- drv/auxflash-server/src/main.rs
Allows clients to know the number and size of auxflash slots statically via constants exported from the API crate.
> Move aux flash sizes to app.toml

- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gimlet/rev-b.toml
- app/gimletlet/app-mgmt.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/sidecar/rev-a.toml
- chips/stm32h7/chip.toml
- drv/stm32h7-eth/src/lib.rs
- task/net/src/main.rs
This switches MDIO to using a timer-based wait for sub-millisecond delays, bringing the VSC7448 boot sequence from 8 to 4 seconds!
> Faster MDIO!

- app/rot-carrier/app.toml
- build/lpc55pins/src/lib.rs
- drv/lpc55-spi-server/src/main.rs
Used for ROT_IRQ and SP_RESET in later PRs.
> Allow for naming individual LPC55 GPIO pins.

- README.mkdn
It took me a while to figure out what `idl/` was about, so I decided to document it. I added `chip/` and `website/` mostly for completion's sake
> Document additional directories for the Hubris repo

- Cargo.lock
- app/donglet/app-g030.toml
- build/xtask/src/dist.rs
- drv/gimlet-hf-server/Cargo.toml
- drv/gimlet-hf-server/src/bsp.rs
- drv/gimlet-hf-server/src/main.rs
- task/mgmt-gateway/src/main.rs
- task/monorail-server/src/bsp.rs
- task/monorail-server/src/bsp/sidecar_1.rs
- task/monorail-server/src/main.rs
- task/net/Cargo.toml
- task/net/src/bsp.rs
- task/net/src/main.rs
- task/net/src/miim_bridge.rs
- task/thermal/Cargo.toml
- task/thermal/src/bsp.rs
- task/thermal/src/main.rs
Also includes two drive-by fixes:
- Missing task slot in G030
- Warning about unused function in `gimlet/app.toml`
> Use path attr instead of giant cfg_if trees for BSPs

- app/gimlet/rev-b.toml
- build/i2c/src/lib.rs
- drv/i2c-devices/src/tmp451.rs
- task/thermal/src/bsp/gimlet_b.rs
- task/thermal/src/bsp/sidecar_a.rs
- task/thermal/src/control.rs
- task/thermal/src/main.rs
This brings the `thermal` task from 18648 to 17720 bytes of flash (a small improvement)
More importantly, it drops the stack usage from 7392 to 3560, meaning we can shrink the RAM usage by 8192!
> Move the thermal config from RAM into flash

- build/util/src/lib.rs
- drv/sidecar-front-io/build.rs
- drv/sidecar-mainboard-controller/build.rs
- stage0/build.rs
- sys/kern/build.rs
If the build script decides the env var is missing, you still want to be re-run if it should change!
> Always emit rerun-if-env-changed *before* reading var

- Cargo.lock
- build/i2c/src/lib.rs
- build/lpc55pins/Cargo.toml
- build/lpc55pins/src/lib.rs
- build/util/src/lib.rs
- drv/auxflash-api/build.rs
- drv/auxflash-server/Cargo.toml
- drv/auxflash-server/build.rs
- drv/gimlet-seq-server/build.rs
- drv/lpc55-spi-server/src/main.rs
- drv/lpc55-swd/build.rs
- drv/sidecar-front-io/build.rs
- drv/sidecar-mainboard-controller/build.rs
- drv/stm32h7-spi-server/build.rs
- stage0/Cargo.toml
- stage0/build.rs
- sys/kern/build.rs
- sys/num-tasks/Cargo.toml
- sys/num-tasks/build.rs
- sys/userlib/build.rs
- task/jefe/build.rs
- task/net-api/Cargo.toml
- task/net-api/build.rs
- task/net/build.rs
- task/ping/build.rs
- task/sp_measure/build.rs
- test/test-suite/build.rs
This switches all uses of `std::env::var` to `build_env::env_var`, which ensures that Cargo will rebuild if the environment variable changes.
In addition, I added `build_util::out_dir`, which is a very common case.
> Standardize on a safe wrapper around std::env::var

- sys/userlib/src/hl.rs
This operation was popular for a period of time between the creation of Hubris and the adoption of Idol. All uses of it have vanished from the repo over time. This is relevant because it contains a UB issue, so I'm removing the code.
Fixes #277.
> userlib: remove hl::send facility

- sys/userlib/src/hl.rs
Without this fix, `hl::sleep_for` will (confusingly) wipe out pending deadlines.
> Save and restore timer deadline in sleep_until

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- lib/mutable-statics/src/lib.rs
- task/control-plane-agent/src/main.rs
- task/host-sp-comms/src/main.rs
- task/net/src/buf.rs
- task/net/src/server_basic.rs
- task/net/src/server_vlan.rs
- task/power/Cargo.toml
- task/power/src/main.rs
Same basic idea as #830 , except that many power devices have a local state cache, so we keep the devices in RAM (moving the configuration to flash).
It's not _as big_ of a win, but is still non-trivial:
- Flash goes from 17804 -> 16588 bytes
- Stack depth goes from 4160 -> 3880
Alas, neither of these changes pushes us below a power of two, but they're still probably worthwhile.
> Reduce stack and flash usage of `power` task

- Cargo.lock
- task/net/Cargo.toml
- task/net/build.rs
- task/net/src/bsp/gimlet_bc.rs
- task/net/src/bsp/gimletlet_mgmt.rs
- task/net/src/bsp/gimletlet_nic.rs
- task/net/src/bsp/nucleo_h7.rs
- task/net/src/bsp/psc_a.rs
- task/net/src/bsp/psc_b.rs
- task/net/src/bsp/sidecar_a.rs
- task/net/src/bsp/sidecar_b.rs
- task/net/src/bsp_support.rs
- task/net/src/main.rs
- task/net/src/server.rs
- task/net/src/server_basic.rs
- task/net/src/server_vlan.rs
These commits...
- Formalize the relationship of the BSP modules with the rest of the netstack by defining a `Bsp` trait
- Simplify the `server_vlan` setup code to do less parallel array iteration and asserting
- Make the `server_vlan` implementation the sole implementation, by treating the VLAN-less case as a degenerate single-network case of the VLAN server.
This reduces code duplication and opportunities for divergence, and makes it easier to reason about whether non-target-specific code (like `src/main.rs`) will work with all the various platform-specific bits (since it only needs to be checked against traits and concrete implementations now).
> netstack refactoring

- Cargo.lock
- build/kconfig/Cargo.toml
- build/kconfig/README.mkdn
- build/kconfig/src/lib.rs
- build/xtask/Cargo.toml
- build/xtask/src/dist.rs
- lib/phash/src/lib.rs
- sys/kern/Cargo.toml
- sys/kern/build.rs
This insulates xtask dist from a bunch of kernel implementation decisions, removing (for example) the region table construction code from xtask and moving it into kern/build.rs. This should let us iterate on the kernel's internal representations more easily.
> Redesign build system kernel config structs.

- app/rot-carrier/app.toml
- lib/lpc55-romapi/src/lib.rs
On targets with TrustZone, the secure world has access to the entire address space. On targets without TrustZone we have to explicitly give access. Since the ROM programming APIs already require access to syscon switch to calculating the clock speed using syscon instead.
> Change how the LPC55 calcuates the clock speed

- README.mkdn
- app/gimletlet/app-sidecar-emulator.toml
- build/xtask/src/dist.rs
- build/xtask/src/graph.rs
- build/xtask/src/main.rs
A graph of tasks is created. Each task is labeled with its name and priority in a box. Task slot relationships are represented by arrows. Priority inversions are noted with a red arrow. Normal dependencies are green arrows.
Use:
cargo xtask dist --graph priority.dot $APP
sudo apt install graphviz xdg-utils eog
dot -Tsvg priority.got
xdg-open priority.svg
> Add graph module to xtask to create task priority graphs

- task/host-sp-comms/src/main.rs
Here's a proposed PR to fix #890 by configuring the SP-to-host GPIO as open drain.
> host-sp-comms interrupt line to SP3 should be open drain

- sys/kern/build.rs
- sys/kern/src/arch/arm_m.rs
Now that we're Rust 2021 we can do this!
> kern: use captured identifiers in format strings

- idl/thermal.idol
- task/thermal/src/bsp/gimlet_bc.rs
- task/thermal/src/bsp/sidecar_ab.rs
- task/thermal/src/control.rs
- task/thermal/src/main.rs
When output value is used as fan duty cycle directly, only positive error values are meaningful.  This prevents the PID loop from engaging until the set point is already reached.  By offsetting the output values, negative errors are meaningful and the PID loop can engage control during the initial rise toward the set point.
> thermal: add PID term to apply offset to output values

- Cargo.lock
- app/gemini-bu/app.toml
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- task/spd/Cargo.toml
- task/spd/src/main.rs
Previously, the spd proxy would treat it as "good enough" if it could
read at least one SPD EEPROM in a given pass. I believe this was causing
issue https://github.com/oxidecomputer/hubris/issues/657, where occasionally a board would come up missing a DIMM or
two.
This commit has the SPD task wait patiently until the power sequencing
task has declared A2, which should imply that the DIMM SPD EEPROMs are
ready to go.
> SPD power interlock

- drv/i2c-devices/src/tmp451.rs
- drv/sidecar-seq-server/src/main.rs
- task/thermal/src/control.rs
In the discussions at https://github.com/oxidecomputer/quartz/issues/24, Arjen suggested configuring the TMP451 to a lower cutoff point so that the sequencer can cut power if the Tofino overheats.  This PR does that configuration as part of Sidecar sequencer setup.
> Add startup code to configure TMP451 THERM limit

- task/thermal/src/control.rs
When b568a1ddb4d5c2b45114e3544f0dc1e2966fd87c added an offset to the PID, the integral clamping code wasn't updated to account for it.  This led to the integral having large swings when error changed from positive to negative.
> thermal: fix integral clamping

- build/util/src/lib.rs
- drv/auxflash-server/build.rs
Hey I found another case where we were leaking the crappy default env var lookup failure message.
> build/util: make env var lookup failure message better

- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- drv/i2c-devices/src/lib.rs
- drv/i2c-devices/src/m2_hp_only.rs
- drv/i2c-devices/src/nvme_bmc.rs
- drv/i2c-devices/src/nvme_bmc_bad_mux.rs
- task/thermal/src/bsp/gimlet_bc.rs
Due to https://github.com/oxidecomputer/hardware-gimlet/issues/1804, we can't talk to M.2s when they are unpowered.  We work around this in the `thermal` task by asking the `MAX5970` for its status; however, `humility validate` doesn't have any support for that kind of special-casing.
This PR adds a new `nvme_bmc_bad_mux`, which is ignored during `humility validate`.
In addition, it renames `nvmebmc` -> `nvme_bmc` so that the existing driver is used for `humility validate` (on good devices).
> Support NVME BMC devices with bad mux

- sys/abi/src/lib.rs
- sys/kern/build.rs
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/descs.rs
- sys/kern/src/lib.rs
- sys/kern/src/startup.rs
- sys/kern/src/task.rs
Since the Early Days, we've had these `TaskDesc`/`RegionDesc` structs in the `abi` crate, giving the static definition of tasks in a Hubris application. Originally this was because they got deposited, by a separate tool, into an array at a predictable location in Flash; the kernel would then interpret them at runtime to set things up. This made it almost impossible to notice when you were running out of kernel RAM, since it depended on the results of that interpretation, rather than (say) the linker.
So about a year ago I fixed that.
The fact that the structs were still public has been gnawing at me, and recently I ran into some cases where I wanted to make changes to the structs that simply wouldn't work if they were in abi. This is because the remaining out-of-kernel use of the structs …
> Make TaskDesc/RegionDesc kernel implementation details

- task/thermal/src/bsp/gimlet_bc.rs
With integral clamping working properly, previous PID terms seem to create oscillations when tracking the set point under load tests.  While these new PID terms don't completely resolve that problem, they do seem to tame the variations to be less annoying.
> thermal: more gimlet PID tuning

- task/thermal/src/control.rs
(this is why we were seeing a non-zero `thermal` generation on `igor`)
> Do subtraction in the correct order

- build/xtask/src/config.rs
Rather than a wrapped string constant that doesn't allow any internal whitespace, the features are now listed in arrays and assembled into a string when needed. This (IMO) makes it way easier to scan and add/remove features.
> xtask: make allowed-features list easier to maintain

- Cargo.lock
- idl/control-plane-agent.idol
- idl/host-sp-comms.idol
- lib/host-sp-messages/Cargo.toml
- lib/host-sp-messages/src/lib.rs
- task/control-plane-agent-api/Cargo.toml
- task/control-plane-agent-api/src/lib.rs
- task/control-plane-agent/Cargo.toml
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/host-sp-comms-api/src/lib.rs
- task/host-sp-comms/src/main.rs
This allows them to be read and written by MGS.
Builds on #922 and should be merged after it.
> Move host startup options to control-plane-agent

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app.toml
- idl/control-plane-agent.idol
- idl/host-sp-comms.idol
- lib/host-sp-messages/Cargo.toml
- lib/host-sp-messages/src/lib.rs
- task/control-plane-agent-api/Cargo.toml
- task/control-plane-agent-api/src/lib.rs
- task/control-plane-agent/Cargo.toml
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_gimlet/host_phase2.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/host-sp-comms-api/src/lib.rs
- task/host-sp-comms/Cargo.toml
- task/host-sp-comms/src/main.rs
The bulk of this PR is in the new `host_phase2` module, which is responsible for sending requests to MGS (potentially on both ports) to ask for phase 2 data in response to `host-sp-comms` asking `control-plane-agent` to do so. There are a handful of minor changes to `host-sp-messages` to track the latest RFD 316 updates (some of which may be so new to have not even landed yet!).
> Fetch host phase2 blocks from MGS

- Cargo.lock
- Cargo.toml
Previously salty used an explicit git rev in the Cargo.toml. This isn't great practice since it prevents easy updating and allows you to reference a commit that isn't on a branch, and is thus subject to being arbitrarily GC'd by Github at any time, breaking the build.
The conversion to workspace dependencies dropped the rev with the rationale that it appeared in the Cargo.lock. This was true, but, the rev was also not on salty's default branch. Cargo only checks out the branch you request. So, on machines that hadn't previously built the explicit-rev version and still had a salty checkout cached, the build now fails because the locked commit is absent.
This switches the dependency to name the branch in our fork where our desired commits live. This ensures that we can cargo update to …
> Fix salty dep by adding branch.

- Cargo.toml
- drv/ignition-api/src/lib.rs
- drv/monorail-api/src/lib.rs
- lib/derive-idol-err/src/lib.rs
- task/net-api/src/lib.rs
Error values of 0 are mistaken for "no error" by Hiffy IPC.
> Fix errors starting at 0

- Cargo.lock
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
- drv/monorail-api/Cargo.toml
- drv/monorail-api/build.rs
- drv/monorail-api/src/lib.rs
- drv/vsc85xx/src/tesla.rs
- drv/vsc85xx/src/vsc8562.rs
- task/control-plane-agent/Cargo.toml
- task/control-plane-agent/src/inventory.rs
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/control-plane-agent/src/mgs_sidecar/monorail_port_status.rs
- task/monorail-server/Cargo.toml
- task/monorail-server/src/server.rs
Adds handlers for a new "component details" message type from MGS. Currently the only meaningful component that can return details is the vsc7448 on a sidecar, but in the future we can slot in other components that have status (or sensor measurements, etc.) in this same handler.
This PR is smaller than it appears: the bulk of it is converting between the (nearly identical) monorail types and the corresponding `gateway-messages` types. It also includes some minor shuffling around of `monorail-api` (including adding generation of an idol client).
> Allow MGS to query for VSC7448 port status 

- Cargo.lock
- drv/i2c-api/src/lib.rs
- lib/derive-idol-err/Cargo.toml
- lib/derive-idol-err/src/lib.rs
This now prints nice compile error messages highlighting any invalid discriminants, and also catches attempts to use non-C-style enums.
> lib/derive-idol-error: improve compile errors

- Cargo.lock
- Cargo.toml
- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
Calls to return the SpState of a given SP now return the PowerState as well. This is to minimize calls from MGS when interacting with wicketd.
Individual `SpHandler::power_state` methods had the logic put into `power_state_impl` methods directly on the MgsHandler to prevent logging an extra `RingBuf` entry and the need to pass unused parameters.
This change depends upon
https://github.com/oxidecomputer/management-gateway-service/pull/15 and must be merged after that, once the cargo changes in here are also fixed.
> control-plane-agent: Report PowerState from `sp_state`

- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- build/xtask/src/main.rs
- build/xtask/src/print.rs
This command can print out information about the build. Currently, it only supports one option, --archive, which prints out the final build archive. This is useful in scripting.
Example:
```
〉cargo xtask print .\app\demo-stm32f4-discovery\app.toml --archive
Finished dev [optimized + debuginfo] target(s) in 1.68s
Running `target\debug\xtask.exe print .\app\demo-stm32f4-discovery\app.toml --archive`
target\demo-stm32f4-discovery\dist\default\build-demo-stm32f4-discovery.zip
```
Additonally, I wanted to make the errors nice for this, and so I ended up adding some contexts inside of the other commands, which will also make them slightly better. Example:
```
〉cargo xtask print .\app\demo-stm32f4-discovery\app.tom --archive
Finished dev [optimized + debuginfo] target(s) in 1.52s
Running …
```
> Introduce new command, xtask print

- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
- task/hiffy/src/main.rs
This will speed up auxflash on Sidecar (pending https://github.com/oxidecomputer/humility/pull/265) and QSPI on Gimlet rev C.
> Use larger HIFFY_DATA for Sidecar A/B and Gimlet C

- drv/transceivers-server/src/udp.rs
This fixes an issue where we falsely return `WrongDataSize`, because we passed in the _entire_ rx buffer instead of just the packet.
> Slice RX buffer based on packet length

- drv/monorail-api/src/lib.rs
- task/monorail-server/src/server.rs
The 1G and 10G ports are quite different; this is best "lowest common denominator" I can figure out
(and even now, it's got some semantic subtleties that differ between 1G and 10G ports)
> Add 'link down' sticky bit to `PortCounters`

- app/gimlet/rev-b-lab.toml
- app/gimlet/rev-c-lab.toml
- app/sidecar/rev-a-lab.toml
- app/sidecar/rev-b-lab.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- drv/gimlet-seq-server/Cargo.toml
- drv/gimlet-seq-server/src/main.rs
- drv/sidecar-seq-server/Cargo.toml
- drv/sidecar-seq-server/src/main.rs
This PR enables automatic power-on in the stock Gimlet and Sidecar images.
Gimlet comes up to `A0`; Sidecar to `LatchOffOnFault`.
In addition, I add `gimlet-{b,c}-lab.toml` and `sidecar-{a,b}-lab.toml` app files, which preserve the previous behavior of staying in A2.
To minimize TOML copypasta, I implemented _very minimal_ TOML inheritance, where you can specify a base file then enable task features.  For the `*-lab.toml` images, I enabled `stay-in-a2`, which is a new feature on the Gimlet and Sidecar sequencer tasks.
This somewhat complicates the build archive.  I ship the **base** `app.toml` file, then a separate `patches.toml` that describes patches applied during inheritance.  This maintains backwards-compatibility with Humility, which expects `app.toml` to include everything that it …
> Power up automatically

- drv/transceivers-server/src/udp.rs
So I found this while investigating https://github.com/oxidecomputer/transceiver-control/pull/26 . There is no need to multiple this size by the number of ports here since write data gets broadcast into each port by the FPGA, not over SPI. This is unlike reads, which will return the read size **per port**.
> fix transceiver udp write size comparison

- .github/workflows/dist.yml
I would like to be able to pull these images directly from CI jobs for the manufacturing stuff, so I have whacked them into the workflow file.  Hopefully correctly!
> add Gimlet rev B/C lab images, and donglet images, to CI

- app/psc/rev-a.toml
- app/psc/rev-b.toml
- build/i2c/src/lib.rs
- build/xtask/src/dist.rs
- drv/i2c-devices/src/lib.rs
- drv/i2c-devices/src/mwocp68.rs
- task/control-plane-agent/src/inventory.rs
- task/power/src/main.rs
- task/validate-api/src/lib.rs
This adds new sensor types (`InputCurrent`, `InputVoltage`), implements them for the mwocp68, and requires a corresponding humility change (https://github.com/oxidecomputer/humility/pull/266).
> Add input current and voltage sensors on MWOCP68

- drv/monorail-api/src/lib.rs
- drv/vsc7448/src/config.rs
- drv/vsc7448/src/lib.rs
- drv/vsc85xx/src/vsc8504.rs
- drv/vsc85xx/src/vsc8522.rs
- drv/vsc85xx/src/vsc8552.rs
- drv/vsc85xx/src/vsc8562.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/monorail-server/src/server.rs
In some cases, the VSC7448 link is going to a PHY, so link status is less meaningful.  This is mostly relevant for Sidecar ports 40-43, which use a VSC8504 as a QSGMII → 4x SGMII converter before going off-board; the link between the VSC7448 and VSC8504 should _always be up_, because they're on the same board.
This PR adds a separate `phy_link_down_sticky: bool` to the `struct PortCounters`, which returns the **PHY's** opinion on whether the link has gone done.  We want this to be stateless (i.e. explicitly cleared by `reset_port_counters`), but the PHY registers are self-clearing; to work around this, we add a separate cache in the Monorail `ServerImpl`.
(this cache will be lost if the `monorail` task restarts, but it would reconfigure the PHYs anyways in that case, so that seems fine)
> Add separate monitoring for PHY link flapping

- Cargo.lock
- drv/lpc55-sprot-server/src/handler.rs
- drv/lpc55-sprot-server/src/main.rs
- drv/sprot-api/Cargo.toml
- drv/sprot-api/src/lib.rs
- drv/stm32h7-sprot-server/src/main.rs
- drv/update-api/src/lib.rs
- idl/sprot.idol
- task/control-plane-agent/src/mgs_common.rs
Overall, the behavior of the protocol should not have changed!
The overriding goal of this commit is to simplify error handling while
making it more idiomatic. The primary methodology used was "parse, don't
validate", meaning encoding knowledge about what was already discovered
in the type system, so that we don't have to redo checks about length,
or reparse the `MsgHeader`. The mechanisms to implement this methodology
are the two types: `RxMsg` and `TxMsg`, and the corresponding types
`VerifiedRxMsg` and `VerifiedTxMsg`, which ensure that a complete
message with a valid `MsgHeader` has been read into `rx_buf` or a valid
message  has been serialized into `tx_buf`, respectively.
The above changes rippled through the rest of the code, and allowed
removing some extra checks around …
> [sprot] Try to make error handling more idiomatic

- Cargo.lock
- Cargo.toml
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
- drv/ignition-api/src/lib.rs
- task/control-plane-agent/Cargo.toml
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/control-plane-agent/src/mgs_sidecar/ignition.rs
This PR fleshes out the existing control-plane-agent ignition placeholders (getting ignition state and sending ignition commands) and adds a few new methods (getting and clearing ignition link events). As of this PR and https://github.com/oxidecomputer/management-gateway-service/pull/22 on which it depends, we can interact with ignition over the management network. The most interesting of these is fetching the state of all targets:
```
john@jeeves ~ $ ./faux-mgs --interface axf0 ignition all
Nov 28 22:09:13.053 INFO binding to [::]:22222 on axf0, component: faux-mgs
target 0: IgnitionState { receiver_status: ReceiverStatus { aligned: false, locked: false, polarity_inverted: false }, target: None }
...snip...
target 7: IgnitionState { receiver_status: ReceiverStatus { aligned: false, …
```
> Integrate ignition and control-plane-agent

- Cargo.lock
- Cargo.toml
- task/control-plane-agent/src/inventory.rs
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/control-plane-agent/src/mgs_sidecar/monorail_port_status.rs
This tracks updates made in https://github.com/oxidecomputer/management-gateway-service/pull/24:
* Renames `SpComponent::VSC7448` -> `SpComponent::MONORAIL`
* Adds two link flap bools to `PortCounters`
* Adds a "clear component status" MGS message, which for `SpComponent::MONORAIL` resets counters on all ports. No other component is valid for this message (for now).
> Add monorail link flap bools and resetting counters to control-plane-agent

- drv/sidecar-front-io/src/leds.rs
As mentioned in the source comment, this PR is meant as a hotfix to mainline Hubris until we arrive at our product solution for how bright these LEDs should be. With this adjustment, we will not overtemp fault by default.
> leds hotfix to not overtemp the PCA9956Bs

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- idl/control-plane-agent.idol
- lib/host-sp-messages/src/lib.rs
- task/control-plane-agent-api/Cargo.toml
- task/control-plane-agent-api/src/lib.rs
- task/control-plane-agent/Cargo.toml
- task/control-plane-agent/src/main.rs
- task/host-sp-comms/src/main.rs
Adds an idol call in `control-plane-agent` that reports the sled's identity from reading it out of the FRUID EEPROM. `host-sp-comms` reports that identity to the host when it asks for it, instead of the placeholder identity it was using previously.
I put the VPD reading in `control-plane-agent` because we will also want to report this info up to MGS, although that is not done as a part of this PR (and may need tweaking to handle sidecar/psc, if those don't use the same barcode format?).
> Report real host identity via local VPD

- Cargo.lock
- lib/derive-idol-err/Cargo.toml
- lib/derive-idol-err/src/lib.rs
- task/thermal-api/src/lib.rs
This will help eliminate the Fault Amplifier, where callers to a server that restarted will try to unwrap a dead code and crash themselves.
> Add support for #[idol(server_death)] attribute

- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app.toml
- task/host-sp-comms/src/main.rs
- task/host-sp-comms/src/tx_buf.rs
This PR removes the low-level uart ringbuf tracing (we have sufficient mileage that this has outlived its usefulness) in favor of tracing full messages. It also stashes the messages sent as part of a host boot fail or panic into static vars that we can pull out (if someone painfully) via humility.
Ringbuf from a gimlet boot that (intentionally) ended in failure:
```
john@igor ~ $ pfexec humility -t sn6 -a ./build-gimlet-b.zip ringbuf host_sp_comms
humility: WARNING: archive on command-line overriding archive in environment file
humility: attached to 0483:3754:0020000F4741500920383733 via ST-Link V3
humility: ring buffer task_host_sp_comms::__RINGBUF in host_sp_comms:
0  314        1        2 JefeNotification { now: 0x6f0, state: A0 }
1  585        1 …
```
> host-sp-comms: Improve ringbuf usability and remember host boot fail/panic messages

- .github/workflows/dist.yml
- app/gimlet-rot/stage0-b-lab.toml
- app/gimlet-rot/stage0-b.toml
- app/gimlet-rot/stage0-c-lab.toml
- app/gimlet-rot/stage0-c.toml
Enables DICE our gimlet b & c builds. The new lab images configure DICE to create self-signed identity certs. Non-lab images configure DICE for the manufacturing process.
> Enable DICE on Gimlet rot & create lab images

- Cargo.lock
- app/gimletlet/app.toml
- drv/mock-gimlet-hf-server/Cargo.toml
- drv/mock-gimlet-hf-server/build.rs
- drv/mock-gimlet-hf-server/src/main.rs
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/control-plane-agent/src/update/host_flash.rs
Also adds a mock `gimlet-hf` server for use on gimletlets that don't have a qspi for the real `gimlet-hf` to use.
> Allowing getting and setting the host boot flash device via control-plane-agent/MGS

- task/host-sp-comms/src/main.rs
Missed this case in #996, for which we definitely want ringbuf entries (since we have neither a request nor a response to log).
> host-sp-comms: Add ringbuf traces for parse errors

- Cargo.lock
- Cargo.toml
This needs testing, but should _hopefully_ fix #995 
The change has to be done via a Cargo `patch` (instead of changing the `smoltcp = { ... }` dependency): [`gateway-messages`](https://github.com/oxidecomputer/management-gateway-service/blob/main/gateway-messages/Cargo.toml#L18) _also_ uses `smoltcp`, and we use its types in API calls, so the versions must be identical.
> Switch smoltcp to using our patched fork, for now

- app/lpc55xpresso/app.toml
The xpressoboard doesn't actually have the hookups to be able to connect to the SP but it's more likely to do something than the old SPI driver
> Enable SPROT server on the xpressoboard

- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- task/jefe/build.rs
- task/jefe/src/main.rs
Listing task names in this configuration key will cause Jefe to, by default, leave them in a faulted state instead of automatically restarting them.
This is, obviously(?), not a thing you want to do in production, but it should be useful for catching intermittent failures on a bench.
> jefe: introduce "tasks-to-hold" config

- sys/kern/src/arch/arm_m.rs
The error stems from the RLAR value being inclusive which typically produces an off by one error. In this case the region is 32 byte aligned and so it's an off by one 32 byte chunk error instead.
This resolves #1016
> Fix off-by-one-ish error in MPU RLAR programming.

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
- task/sensor/Cargo.toml
- task/sensor/src/main.rs
This makes the task's memory usage much more visible, and means you'll get a compile error -- not a runtime stack overflow -- if you add too many sensors without increasing the RAM allocation.
> task/sensor: move sensor data off stack into static

- Cargo.lock
> Bump packages in lpc55_support

- drv/sidecar-front-io/src/transceivers.rs
A [previous FPGA change](https://github.com/oxidecomputer/quartz/issues/44) adjusted the default state of the LED controllers reset and output enable pins. The output enable used to be enabled by default, but that is no longer the case. The SP needs to enable it now.
> Set output enable for LED controller by default

- Cargo.lock
- Cargo.toml
I don't remember why we switched to using a fork of the `stm32-rs-nightlies` repo, but this appears to build fine!
It's also a significant speedup – rebuilding `app/sidecar/rev-a.toml` with no changes goes from 15 -> 9 seconds.
This is counterintuitive: `sidecar` doesn't use `stm32g0` at all.  It turns out Cargo walks the entire checkout of all dependencies searching for manifests, and the checkout for `stm32-rs-nightlies` contains _thousands_ of subfolders.
> Use stm32g0 crate, which speeds up the build significantly

- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- stage0/src/image_header.rs
It turns out we have two disjoint ways of specifying approximately the same thing w.r.t. other images. Switch to a single method.
> Be consistent with specifying images in linker script

- task/thermal/src/control.rs
Previously, this subtraction would panic if we were in the `Overheating` state and missed a sample.  I don't think this is what we're seeing in the field, but it's definitely incorrect, so let's fix it.
> Fix subtraction order

- task/jefe/src/external.rs
- task/jefe/src/main.rs
I happened to read through this code while preparing it for fault logging, and I noticed some things.
1. The dispositions were kind of redundant. If you set one to Fault the task effectively got held (in that it would not restart), but also there's Hold that causes it to get held?
2. As a side effect, issuing the "start" command would set the disposition to Start, which is a weird disposition that ... causes the task not to get restarted after faults?
3. The fault handling loop was complex.
4. There was no convenient way to restart a running task.
5. There was no way to atomically restart a task but catch it at the next fault, because the "start" and "release" commands both cleared the fault hold state.
It turns out these were all related to each other. The "External Command" facility, …
> jefe: rework fault handling and command impl

- .github/workflows/dist.yml
- Cargo.lock
- Cargo.toml
- app/gimletlet/src/main.rs
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
- drv/i2c-api/src/lib.rs
- drv/i2c-devices/Cargo.toml
- drv/i2c-devices/src/mwocp68.rs
- idl/power.idol
- task/power-api/Cargo.toml
- task/power-api/build.rs
- task/power-api/src/lib.rs
- task/power/Cargo.toml
- task/power/src/main.rs
- task/udprpc/src/main.rs
The bulk of this PR adds the `Power.pmbus_read()` operation for remote use via `humility rpc` during compliance, and the 50+ variant enum describing all the ACAN-114 pmbus commands we want to read. This command (for now?) only supports the MWOCP68.
There are a handful of other changes included as a part of this work:
1. Adds gimletlet to CI and fixes its build
2. Removes the `NReplyMismatch` error from `udprpc`: for idol calls with `encoding: Hubpack` or `encoding: Ssmarshal`, the reply size is expected to be _at most_ the reply size requested by `humility rpc`, but is not guaranteed to be exactly that value. Removing this error allows smaller replies to come through okay.
3. The `power` task is now an idol server, so its previous main loop (sleep 1 second, then read data and post it to …
> Add `Power.pmbus_read` idol operation

- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
We were holding the `thermal` task to debug a failure that we had (non-reproducibly) seen, but we now believe that that was in fact fixed in #1035; we no longer need to hold the `thermal` task on fault.
> no longer need to hold thermal

- app/gimletlet/app.toml
- task/udprpc/src/main.rs
Previously, `udprpc` assumed the target task was at generation 0.
This also adds `udprpc` and `udpbroadcast` to the Gimletlet image, and removes a vestigal constant.
> Fix `udprpc` task ID

- drv/transceivers-server/src/udp.rs
- task/net-api/src/lib.rs
- task/udpecho/src/main.rs
This prevents **mandatory crashing** (in the generated Idol code) by clients when the watchdog fires.
A client could still crash if it wasn't expecting this particular error, but that's on them.
> Add an error indicating that the `net` server restarted

- drv/fpga-devices/src/ecp5_spi.rs
- drv/fpga-devices/src/ecp5_spi_mux_pca9538.rs
- drv/spi-api/src/lib.rs
- drv/transceivers-server/src/udp.rs
- task/control-plane-agent/src/main.rs
- task/net-api/src/lib.rs
- task/net/src/server.rs
- task/udpecho/src/main.rs
- task/udprpc/src/main.rs
This is a followup to #1050; the primary change is adding `ServerRestarted` variants to the rest of the `net-api` error types. Changes that came along for the ride:
* Removed `SpiError::DataOverrun` (unused)
* Added the `#[idol(server_death)]` annotation to `SpiError::ServerRestarted`
* Removed all the transferred `SpiError` variants in `KszError`; the `read_ksz*` idol functions (only called by humility) now panic if there's a SPI error.
* Updated all the net clients that handle `RecvError` to handle `RecvError::ServerRestarted` (treating it the same as `QueueEmpty`; i.e., retry).
* Added a handler in control-plane-agent to retry sends that fail with `SendError::ServerRestarted` instead of discarding them.
> Add more net server death error codes

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
- build/i2c/src/lib.rs
- drv/transceivers-api/Cargo.toml
- drv/transceivers-api/build.rs
- drv/transceivers-api/src/lib.rs
- drv/transceivers-server/Cargo.toml
- drv/transceivers-server/src/main.rs
- idl/sensor.idol
- idl/thermal.idol
- task/control-plane-agent/src/inventory.rs
- task/power/src/main.rs
- task/sensor-api/src/lib.rs
- task/sensor-polling/src/main.rs
- task/thermal-api/src/lib.rs
- task/thermal/src/bsp/sidecar_ab.rs
- task/thermal/src/control.rs
- task/thermal/src/main.rs
This PR refactors the `thermal` task to read temperature data from the `sensors`
task.  It still **writes** (most of) the data itself, but then reads it back, to
improve support for cases where other tasks provide temperature data.
The `sequencer` task now provides data to `sensors` directly, rather than
passing values through `thermal`.
In addition, it adds new APIs to the sensors task: `post_now` and `nodata_now`
send a reading and the current timestamp.  These APIs are used to reduce code in
a few unrelated tasks, e.g. `power` and `sensor-polling`.
> Use sensors in thermal task

- stage0/src/dice.rs
- stage0/src/main.rs
Pass the peripheral to the dice module as a parameter instead.
> Fix panic cuased by taking lpc55_pac Peripheral twice w/ unwrap.

- drv/vsc7448/src/lib.rs
- task/monorail-server/src/bsp/sidecar_a.rs
- task/monorail-server/src/bsp/sidecar_b.rs
The difference between `configure_vlan_strict` and `configure_vlan_semistrict` is the handling of technician ports: in this PR, the technician ports remain able to talk to every SP.  This makes development easier, until MGS is ready to go (and booting autonomously).
I tested this on the `niles` rev B Sidecar, and confirmed that the SPs are now isolated:
```
matt@niles ~ (sidecar-b) $ h monorail mac
humility: attached to 0483:3754:002600184D4B500E20373831 via ST-Link V3
Reading 4 MAC addresses...
PORT |        MAC
------|-------------------
13 | 0e:1d:80:ba:b8:c6
15 | 0e:1d:80:ba:b8:c7
44 | 00:0e:c6:46:43:d9
48 | 0e:1d:dc:cf:27:34
matt@niles ~ (sidecar-b) $ h net mac
humility: attached to 0483:3754:002600184D4B500E20373831 via ST-Link V3
humility: Reading 3 MAC addresses...
PORT | …
```
> Enable VLANs on the management network, with one exception

- Cargo.lock
- Cargo.toml
- build/xtask/Cargo.toml
- build/xtask/src/dist.rs
- build/xtask/src/main.rs
- build/xtask/src/print.rs
- drv/lpc55-update-server/src/main.rs
- stage0/src/main.rs
On the lpc55s69, ARM trustzone is in use which was triggering a secure fault when accessing `sram3` used by the `BOOTSTATE` static variable in the lpc55-update server. This was due to the having overlapping ranges for the region defined in the SAU for this memory. Overlapping ranges cause the memory to automatically be accessible in secure mode only, when we needed it in non-secure mode.
Per the ARM v8m manual section B10.3:
> An address that matches multiple SAU regions is marked as Secure and not Not-secure callable regardless of the
attributes specified by the regions that matched the address.
@kc8apf fixed it with judicious use of rangemap.
This PR also:
* Changes stage0 to configure the MPU *before* dumping the BOOTSTATE to USB SRAM
* Removes an unnecessary reference
* Ensures the …
> Fix Update.status on RoT

- Cargo.toml
- task/dumper/src/main.rs
Draft commit message:
```
In stress testing the in situ dumping facility, a disturbing pathology
was discovered:  a significant fraction of the time (as much as 15%),
the SWD facility would fail after the target was stopped -- and it
would fail to resume.  This is Bad.  Fortunately, reinitializing SWD
and re-attempting the resume seems to always correctly resume the
target (at which point the dump will fail, but at least the SP will be
alive!).
```
> if/when resume of SP fails, reinitialize and retry

- Cargo.lock
- drv/lpc55-update-server/Cargo.toml
- drv/lpc55-update-server/src/main.rs
- drv/sprot-api/src/lib.rs
- drv/update-api/src/lib.rs
Zero out the header block in flash, cache it in the lpc55-update-server, then write it during update finish.
This strategy prevents boot loops during partial RoT updates by invalidating the header magic.
> Write header block last on lpc55

- app/rot-carrier/app-secure.toml
- app/rot-carrier/stage0-secure.toml
Currently, the rot-carrier/stage0-fixed-rom bootloader builds an image that isn't correctly configured for trustzone and won't actually boot on an LPC55S69.
This commit fixes that by harmonizing its configuration with the (working) bootloader from app/lpc55xpresso.
While debugging this, I noticed that
- rot-carrier nonsecure build produced a file called rot-carrier
- rot-carrier secure build also produced a file called rot-carrier
- rot-carrier stage0 also produced a file called rot-carrier
This seemed really error prone so I've renamed them all to be distinct.
I've also renamed "fixed-rom" to "secure" to more accurately reflect its purpose.
> Rename and rework secure rot-carrier build.

- Cargo.lock
- build/util/Cargo.toml
- build/util/src/lib.rs
- build/xtask/Cargo.toml
- build/xtask/src/config.rs
- lib/toml-task/Cargo.toml
- lib/toml-task/src/lib.rs
This will allow tasks to check their configuration more robustly – checking `interrupts`, `uses`, etc.
I'm open to suggestions about names, since "task config" is increasingly overloaded.
> Pass full task config to build

- Cargo.lock
- drv/lpc55-spi/src/lib.rs
- drv/lpc55-sprot-server/src/handler.rs
- drv/lpc55-sprot-server/src/main.rs
- drv/spi-api/src/lib.rs
- drv/sprot-api/Cargo.toml
- drv/sprot-api/src/lib.rs
- drv/stm32h7-sprot-server/Cargo.toml
- drv/stm32h7-sprot-server/src/main.rs
- drv/update-api/src/lib.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/control-plane-agent/src/update/mod.rs
- task/control-plane-agent/src/update/rot.rs
This PR contains sprot enhancements which serve as a follow up to #965 and also support successful RoT update from faux-mgs. It also contains the changes to control-plane-agent necessary to use sprot for RoT update.
This code has been split into four logical commits. The first three commits are all sprot related changes, and only the third commit will compile. They were split only to aid in reviewing, and will be collapsed for merge. The last commit is the related control-plane-agent changes.
Please see the individual commit messages for full details.
> RoT Update

- Cargo.lock
- lib/task-config/Cargo.toml
- lib/task-config/src/lib.rs
- test/test-idol-api/Cargo.toml
- test/test-idol-api/src/lib.rs
- test/tests-stm32g0/app-g070.toml
They were broken by
- Changes to `HUBRIS_TASK_CONFIG` to include the full config
- `idol_runtime::IHaveConsideredServerDeathWithThisErrorType`
(`test/tests-psc/app.toml` is still broken, but it was broken before)
> Fix broken test apps

- drv/stm32xx-i2c-server/src/main.rs
- drv/stm32xx-i2c/src/lib.rs
High is for ~100+MHz signals and will be producing annoyingly sharp edges. Low is good up into the MHz+range which is fine for I2C.
> stm32xx: Change I2C slew rates to Low

- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gemini-bu/app.toml
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app-dc2024.toml
- app/gimletlet/app-mgmt.toml
- app/gimletlet/app-sidecar-emulator.toml
- app/gimletlet/app-vsc7448.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
- build/xtask/src/dist.rs
- drv/fpga-server/Cargo.toml
- drv/stm32h7-spi-server-core/Cargo.toml
- drv/stm32h7-spi-server-core/build.rs
- drv/stm32h7-spi-server/Cargo.toml
- drv/stm32h7-sprot-server/Cargo.toml
- task/monorail-server/Cargo.toml
- task/net/Cargo.toml
Previously, Sidecar took 19 seconds to rebuild, because `drv-stm32h7-spi-server-core` was being
- instantiated more than once
- with identical features
- but dependent on environmental variables that are changing
This caused it to be rebuilt – and more importantly, the tasks using it to be re-linked – multiple times per full Hubris build.
Because Cargo caches builds based on features, we can fix this by activating a `spiX` feature in this crate, based on the SPI peripheral being used.
This requires a little plumbing to propagate the feature through other crates which depend on `drv-stm32h7-spi-server-core`.
This brings a Sidecar rebuild down to **7 seconds**, which is much more tolerable.
In addition, the feature is used to select the global SPI configuration block, eliminating the old …
> Plumb SPI features through tasks to improve rebuild

- README.mkdn
- `test` was duplicated
- path was wrong
> readme: fixed `cargo xtask test` example for lpc55

- Cargo.lock
- Cargo.toml
- task/control-plane-agent/src/update/host_flash.rs
Depends on https://github.com/oxidecomputer/management-gateway-service/pull/53 ; we should switch the dependency back to `main` once that's merged.
Closes #1098
> Fail on oversized host flash update

- Cargo.lock
- Cargo.toml
- drv/gimlet-seq-server/src/main.rs
- drv/mock-gimlet-seq-server/src/main.rs
- drv/stm32h7-usart/src/lib.rs
- idl/gimlet-seq.idol
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
Depends on https://github.com/oxidecomputer/management-gateway-service/pull/56 and should be updated back to `management-gateway-service:main` after that lands.
> Add support for host NMI and UART break

- app/gimletlet/app-dc2024.toml
- task/control-plane-agent/src/inventory.rs
- task/validate-api/build.rs
We keep the const versions around (with `_CONST` appended to their names) for use by static assertions, but use the `static` variant in all real code.
> Prefer static over const for device description arrays.

- Cargo.lock
- app/gimletlet/app-mgmt.toml
- build/spi/Cargo.toml
- build/spi/src/lib.rs
- drv/fpga-server/src/main.rs
- drv/gimlet-seq-server/src/main.rs
- drv/spi-api/Cargo.toml
- drv/spi-api/build.rs
- drv/spi-api/src/lib.rs
- drv/stm32h7-spi-server-core/Cargo.toml
- drv/stm32h7-spi-server-core/build.rs
- drv/stm32h7-sprot-server/src/main.rs
- task/monorail-server/src/main.rs
- task/net/src/bsp/gimlet_bc.rs
- task/net/src/bsp/gimletlet_mgmt.rs
- task/net/src/bsp/gimletlet_nic.rs
- task/net/src/bsp/psc_a.rs
- task/net/src/bsp/psc_b.rs
- task/net/src/bsp/sidecar_a.rs
- task/net/src/bsp/sidecar_b.rs
This isn't as strongly-typed as possible, but it's an improvement over the status quo!
I pulled the `GlobalConfig` from `stm32h7-drv-spi-server-core` to a new `build/spi` crate, then reused it in `spi-api`.
> Switch to names for SPI devices

- drv/lpc55-update-server/src/main.rs
To more clearly indicate that IMAGE addresses should not be dereferenced in the lpc55-update-server, make them arrays of 0 length. This is based on current recommendations from unsafe code wg. Hat tip to @cbiffle for the suggestion.
> Use zero sized types for extern image locations

- app/donglet/app-g031.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- task/vpd-api/src/lib.rs
- task/vpd/Cargo.toml
- task/vpd/src/main.rs
This adds a feature to stub out `read_tmp117_eeprom`, which is unused as far as I can tell (but may be relevant for Donglet?)
> Add VPD task to PSC

- Cargo.lock
- build/util/src/lib.rs
- idl/power.idol
- task/power-api/Cargo.toml
- task/power-api/src/lib.rs
- task/power/Cargo.toml
- task/power/src/main.rs
This will let us implement https://github.com/oxidecomputer/humility/pull/325 without raw I2C, which in turns lets us (a) call it over the network and (b) plumb it into `control-plane-agent`.
Tested on a rev B Gimlet:
```console
matt@niles ~ (gimlet) $ h hiffy -c Power.bmr491_max_lifecycle_event_index
humility: attached to 0483:374f:000C001F4D46500F20373033 via ST-Link V3
Power.bmr491_max_lifecycle_event_index() => 0x2b
matt@niles ~ (gimlet) $ h hiffy -c Power.bmr491_max_fault_event_index
humility: attached to 0483:374f:000C001F4D46500F20373033 via ST-Link V3
Power.bmr491_max_fault_event_index() => 0x6
matt@niles ~ (gimlet) $ h hiffy -c Power.bmr491_event_log_read -aindex=42
humility: attached to 0483:374f:000C001F4D46500F20373033 via ST-Link V3
Power.bmr491_event_log_read() => …
```
> Add API to read BMR491 event log

- Cargo.lock
- Cargo.toml
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app-dc2024.toml
- app/gimletlet/app.toml
- idl/control-plane-agent.idol
- lib/host-sp-messages/src/lib.rs
- task/control-plane-agent-api/src/lib.rs
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/host-sp-comms/Cargo.toml
- task/host-sp-comms/src/main.rs
- task/host-sp-comms/src/tx_buf.rs
Adds:
* Implementations for the new `set_ipcc_key_lookup_value()` handler for incoming MGS messages
* sidecar/psc return errors - they have no IPCC
* gimlet's implementation allows MGS to set the installinator image ID to any binary blob of at most 512 bytes
* The `host_sp_messages::Key::InstallinatorImageId` variant
* An idol call allowing `host_sp_comms` to ask `control_plane_agent` for the current installinator image ID when a host process requests it via the IPCC ioctl described on #1113 
Todo:
> Add Installinator Image ID plumbing

- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
Several small changes to make sidecar SPs happy:
* Bump up `control-plane-agent`'s stack; we were overflowing by ~600 bytes; this bumps us up 2 KiB
* On gimlet, change `dump_agent`'s priority to be lower (i.e., numerically higher) than sprot by 1
* Add `dump_agent` to sidecar and PSC
> Stack size and dump_agent housekeeping

- drv/sidecar-seq-server/src/clock_generator_payload_b.rs
This config was tested with a rev B Sidecar on the bench as part of in-progress PCIe clocking working. The significant changes are matching the VDDO setting of each output buffer with the actual voltage level of the power rail and disabling unused DPLLs for a possible reduction in noise/jitter.
> Update Sidecar Rev B clock config as part of hardware-sidecar/#757

- lib/host-sp-messages/src/lib.rs
- task/host-sp-comms/src/main.rs
Instead of overloading `HubpackError` (which `host-sp-comms` then had to interpret, which it sometimes couldn't do accurately), `host_sp_messages::deserialize()` now returns a `DecodeFailureReason` directly, with suitable responses for bad or missing CRCs.
Fixes #1141.
> More accurate errors in host-sp-messages deserialization

- drv/stm32xx-i2c-server/src/main.rs
- drv/stm32xx-sys-api/src/lib.rs
By alternating between `configure_alternate` (for normal operation) and `configure_input` (to shut off pins and switch to a different set of pads), the I2C driver was introducing a subtle and brief glitch in the output lines -- as a side effect of how `configure_input` is defined.
Concretely, `configure_input` implies setting the pin's alternate function mux (AF) to an arbitrary value, under the assumption that the configuration will be set once and not changed.
The `configure_alternate_input` operation lets us preserve the AF during reconfiguration and should prevent the glitch. However, the STM32 docs are ambiguous on whether the peripheral selected by the AF mux can still see inputs when the pin is set to input -- and the block diagrams strongly suggest that it can.
And so, rather than …
> stm32xx-i2c-server: don't glitch pins on mux swaps

- app/gimlet-rot/app-b.toml
- app/gimlet-rot/app-c.toml
- app/rot-carrier/app-secure.toml
- app/rot-carrier/app.toml
Most of these changes come from the `gpio_driver` and `swd` tasks operating with the same priority. `swd` talks  to `gpio_driver` so it must be at a lower (numerically higher) priority. This trickles down to other tasks that use `swd` like `dumper`, and tasks that use `dumper` like `sprot`.
> app.toml: Fix priority inversions in RoT app tomls.

- build/xtask/src/graph.rs
The graphs we were generating did not reliably put different priorities on different tiers. As far as I can tell, this turns out to be due to backwards (priority inversion) edges causing it to throw up its hands and collapse ranks.
This marks backwards edges as constraint=false to exempt them from the rank calculation.
> xtask graph: fix priority ranking

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- drv/gimlet-hf-api/Cargo.toml
- drv/gimlet-hf-api/src/lib.rs
- drv/gimlet-hf-server/Cargo.toml
- drv/gimlet-hf-server/src/main.rs
- drv/stm32h7-hash-server/src/main.rs
- drv/stm32h7-qspi/src/lib.rs
- idl/gimlet-hf.idol
- task/control-plane-agent/src/update/host_flash.rs
- task/hiffy/src/common.rs
- task/hiffy/src/stm32h7.rs
This PR implements the scheme described in https://github.com/oxidecomputer/hubris/issues/985 for storing persistent host flash data (current slot and boot flags).
It reserves the lowest sector (64 KiB) of QSPI flash for Hubris, adding new HIF functions if you _really_ want to overwrite it and returning an error code otherwise.  Within sector 0, we store up to 512 copies of `RawPersistentData`; the one with the largest `epoch` field is our current value.
A new Idol API is added to write this persistent data, by scanning sector 0 on both flash ICs, finding the highest `epoch`, and incrementing it.
`control-plane-agent` is modified to avoid writing sector 0, but checks that any bytes that we _try_ to write in that sector are `0xFF` and returns an error otherwise.
> Initial support for host flash persistence

- drv/i2c-devices/src/bmr491.rs
- drv/i2c-devices/src/isl68224.rs
- drv/i2c-devices/src/mwocp68.rs
- drv/i2c-devices/src/raa229618.rs
- drv/i2c-devices/src/tps546b24a.rs
- idl/power.idol
- task/power-api/src/lib.rs
- task/power/src/main.rs
Currently, we read the BMR491 black-box through raw I2C in Humility.
We'd like to switch to using the `bmr491_*` APIs, which are Idol functions that could be called remotely – initially via `humility rpc`, and later by MGS.
However, to interpret IBC blackbox data, we need to know `VOUT_MODE`.  This PR adds an Idol function to read it!
> Add `Power.read_mode`

- build/xtask/src/graph.rs
@lzrd noted that the edges in the graph were relying on red and green to distinguish correct from inverted priority relationships, which isn't very useful for folks with atypical color vision.
With this commit, they are still red vs green, but
- The inverted edges are also dashed
- And labeled with the word "BAD"
> xtask graph: improve visual accessibility

- Cargo.lock
@jgallagher and @mkeeter noted that one of the TLVC routines on ARMv7-M was creating a 1068 byte stack frame, which was causing a hard-to-diagnose stack overflow in `control-plane-agent`.
I have fixed the TLVC crate, this pulls in the fix.
> Bump tlvc version to reduce stack usage.

- drv/gimlet-seq-server/src/main.rs
Testing notes: measured `SP3_VDD33_SENSE` at TP454 in A2 and A0 on rev B s/n 15.  Before this change, it was at 1.87 V in A2 and 3.34 V in A0.  After this change, it is at 0.036 V in A2 and 3.34 V in A0.  Verified that no NMI is asserted by default when the host boots.  Verified default disposition of pin J:2 with `hiffy gpio -i` is 1.  Then asserted NMI via hiffy (`gpio -p J:2 -r`) which worked as expected.
> hubris#1163 gimlet NMI output GPIO back-powers A0 rail

- Cargo.lock
- Cargo.toml
- app/demo-stm32g0-nucleo/app-g070-mini.toml
- app/demo-stm32g0-nucleo/app-g070.toml
- app/donglet/app-g031-i2c.toml
- app/donglet/app-g031.toml
- build/kernel-link.x
- build/util/src/lib.rs
- build/xtask/Cargo.toml
- build/xtask/src/clippy.rs
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- build/xtask/src/lsp.rs
- build/xtask/src/sizes.rs
- doc/biblio.adoc
- doc/guide/caboose.adoc
- doc/guide/index.adoc
- doc/kipc.adoc
- idl/caboose.idol
- sys/abi/src/lib.rs
- sys/kern/src/header.rs
- sys/kern/src/kipc.rs
- sys/userlib/src/kipc.rs
- task/caboose-reader-api/Cargo.toml
- task/caboose-reader-api/build.rs
- task/caboose-reader-api/src/lib.rs
- task/caboose-reader/Cargo.toml
- task/caboose-reader/build.rs
- task/caboose-reader/src/main.rs
Closes #1157, which has discussion of this design.
This PR does several things!
Primarily, it adds an optional `caboose` to Hubris images.  The caboose is located at the end of flash and contains (1) two words indicating that it's a caboose and (2) extra space for user data.
It is documented in a newly added section of the [Hubris manual](https://github.com/oxidecomputer/hubris/blob/caboose/doc/guide/caboose.adoc).
This also accomplishes _some_ of the goals of #1004 , namely having a "commit point" at the end of flashing.  For the moment, this implementation still requires having an `ImageHeader` after the vector table.  The caboose is after everything else in flash, but is not at the last page; this means that we need a way to find it, which is specified in the `ImageHeader`.
(We could …
> Add the Hubris Caboose

- Cargo.lock
- drv/local-vpd/src/lib.rs
- lib/oxide-barcode/Cargo.toml
- lib/oxide-barcode/src/lib.rs
- task/control-plane-agent-api/Cargo.toml
- task/control-plane-agent-api/src/lib.rs
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_common.rs
The actual changes to support 0XV2 barcodes (which have the hyphen in the part number) are minimal, so most of the changes in this PR are organizational:
* Adds `local_vpd::read_config_into()` so we can read into an array without knowing the exact size ahead of time
* Adds `oxide-barcode` lib (primarily for easy unit testing)
* Moves `VpdIdentity` from `control-plane-agent-api` to `oxide-barcode`
Fixes #1183
> Add support for 0XV2 barcodes

- Cargo.lock
- idl/sensor.idol
Only one checked-in service appears to have been affected by this bug, which would cause a method that specified both Hubpack/Ssmarshal and a recv strategy that didn't _happen_ to bitwise-match how the argument was going to be serialized to become uncallable.
> Bump idol to guard against the recv+Hubpack bug.

- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/sidecar/rev-a.toml
- app/sidecar/rev-b.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- doc/guide/caboose.adoc
If `default = true` in the `[caboose]` section of TOML, populates a default caboose with `VERS = "0.0.0-git"`.
> Add default caboose

- Cargo.lock
- Cargo.toml
- app/gimlet-rot/stage0-b-lab.toml
- app/gimlet-rot/stage0-b.toml
- app/gimlet-rot/stage0-c-lab.toml
- app/gimlet-rot/stage0-c.toml
- app/lpc55xpresso/stage0.toml
- app/rot-carrier/stage0-secure.toml
- app/rot-carrier/stage0.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- stage0/Cargo.toml
This PR removes the Hubris-specific signing code in favor of calling into `hubtools`, which knows how to sign Hubris archives.
Depends on https://github.com/oxidecomputer/hubtools/pull/3/files and should be merged after it
> Sign images with hubtools

- Cargo.lock
- Cargo.toml
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_gimlet/host_phase2.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
The Gimlet SP handler now keeps track of the last serial-console-related packet (attach, write, break, or the new keepalive) it receives from an attached MGS; when it wants to send a serial console packet, we now first check to see if it's been long enough since we heard from MGS that we think the connection is stale. If it is, we effectively "detach" - if MGS comes back, it will get an error and have to reattach.
TODO:
> Stop sending serial console packets to MGS if it has stopped talking to us

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app-dc2024.toml
- app/gimletlet/app.toml
- idl/packrat.idol
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/host-sp-comms/Cargo.toml
- task/host-sp-comms/src/main.rs
- task/packrat-api/Cargo.toml
- task/packrat-api/src/lib.rs
- task/packrat/src/main.rs
This moves storage of the host startup options out of `control-plane-agent` and into `packrat`, which accomplishes two minor things:
1. They now persist even if `c-p-a` restarts
2. `host-sp-comms` makes fewer requests of `c-p-a`
It's a little tempting to remove the startup-options-related idol calls from `control-plane-agent` altogether, but I opted not to for two reasons:
1. Folks have workflows that would need a minor update, and
2. `packrat`'s setter takes an actual `HostStartupOptions`, which `hiffy` doesn't know how to accept on the command line. (`c-p-a`'s setter takes a `u64` and fails if it contains unknown bits, which seems reasonable for a hiffy interface but not so much for packrat).
One change is that the default host startup options are now specified _in packrat_ instead of …
> Store host startup options in packrat

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimletlet/app-dc2024.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/sidecar/rev-b.toml
- app/sidecar/rev-c.toml
- task/udpbroadcast/Cargo.toml
- task/udpbroadcast/src/main.rs
Also adds a version field to the front of the packet and a byte indicating whether the VPD is valid (useful both for VPD-less boards like gimletlet and for detecting busted VPD).
From a wireshark capture of a gimletlet's broadcasts:
```
01 00 00 00                      # version
0e 1d 7d ef 9f 1d                # mac
80 bd fe ba e3 ab 59 27          # hubris image id
00                               # identity_valid
00 00 00 00 00 00 00 00 00 00 00 # identity_valid=0, so this is all zero
00 00 00 00                      # identity_valid=0, so this is all zero
00 00 00 00 00 00 00 00 00 00 00 # identity_valid=0, so this is all zero
```
and from a snoop capture of a gimlet:
```
0100 0000                   # version
a840 2504 0281              # mac
0b4d 9df2 0ef2 0809         # hubris image …
```
> Add VPD identity to packets sent by udpbroadcast

- Cargo.lock
- app/gimlet-rot/app-b.toml
- app/gimlet-rot/app-c.toml
- app/lpc55xpresso/app.toml
- app/rot-carrier/app.toml
- chips/lpc55/chip.toml
- drv/lpc55-flash/Cargo.toml
- drv/lpc55-flash/src/lib.rs
- drv/lpc55-update-server/Cargo.toml
- drv/lpc55-update-server/build.rs
- drv/lpc55-update-server/src/main.rs
Previously we've been calling through the LPC55's ROM to write/erase flash. In build configurations where Trustzone was enabled, this meant indirecting through the hypovisor into the secure-world to perform the flash writes.
This mostly worked fine but had some structural issues:
- The actual code to interact with flash was spread over four crates and a closed-source ROM, so answering basic questions like "does this function called write actually erase?" was surprisingly involved.
- Adding new entry points to flash (e.g. for erase-check or verify) required modifying ~4 crates.
- Getting the ROM working from within a Hubris task (for the non-hypovisor case) consumed all of the task's MPU slots to map: SYSCON, the secure alias of SYSCON, the flash controller, the ROM itself, program RAM, …
> LPC55 raw flash driver and update support.

- Cargo.lock
- build/xtask/src/dist.rs
This ensures that the `final.{bin,elf}` in the build directory are cabooséd and signed.
> Extract final.bin/elf from the archive in the build system

- Cargo.lock
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/psc/rev-c.toml
- drv/psc-seq-server/Cargo.toml
- drv/psc-seq-server/src/main.rs
- drv/user-leds/src/main.rs
This works on Ian's rev B, although it doesn't work on my rev A; Ian is going to double-check the rev A layout, because it may disagree with the schematic in EDM.
> Illuminate user LED on PSC

- app/sidecar/rev-b.toml
- app/sidecar/rev-c.toml
- sys/kern/src/kipc.rs
- sys/kern/src/lib.rs
- sys/kern/src/umem.rs
- sys/kern/src/util.rs
Doing a kernel dump from within the kernel is inherently hairy. We wind up needing to do a raw byte read of a Task struct, which we also need to interact with as an actual Task.
The implementation was
- Creating (using core::slice::from_raw_parts) a byte slice that aliased the &mut [Task] task table
- Then using it and the &mut concurrently
which is UB due to aliasing violations.
The code also contained an easily accessible way of crashing the kernel: send in a region such that base+size overflows. Triggering this reliably required choosing a base value within the TCB address range, because the other code path used USlice.
I've reworked the logic. The particular code that was causing the UB issue has been replaced by
- Deriving a &mut Task to the specific task we want to access, and then …
> kern: rework dump impl to reduce UB

- sys/kern/src/kipc.rs
This use-statement was unused in builds missing the dump feature, which was generating warnings in some RoT builds. My mistake.
> kern: fix warning in kipc built without dump feature

- Cargo.lock
- build/task-link.x
- build/task-rlink.x
- build/task-tlink.x
- build/xtask/src/clippy.rs
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- lib/toml-task/src/lib.rs
- stage0/src/main.rs
- Bumps hubtools to a version that accepts the new or old magic numbers in images, in preparation for the magic number change.
- Improves diagnostics of hubtool errors by adding context messages in the build system
- Removes currently-untested trustzone related config stuff in the TOML and collapses it down to the "not trustzone" case.
> Build system cleanups as followup to #1254

- app/gimlet-rot/stage0-c-lab.toml
- app/gimlet-rot/stage0-c.toml
- app/lpc55xpresso/stage0.toml
- sys/kern/build.rs
- sys/kern/src/arch/arm_m.rs
- task/ping/build.rs
- task/ping/src/main.rs
- test/test-suite/build.rs
- test/test-suite/src/main.rs
#1254 eliminates TZ support from Hubris, but because stage0 still had TZ support enabled, Hubris would fail on a secure fault on its first exception.  This disables TZ support in stage0 on those parts that support is (i.e., LPC55S69), as well as removes build apparatus that only existed to support TZ (following up on similar work done in #1255).
> stage0 should no longer enable TrustZone

- Cargo.lock
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimlet/rev-d.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/psc/rev-c.toml
- task/control-plane-agent/Cargo.toml
- task/control-plane-agent/src/inventory.rs
- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
This should be merged after https://github.com/oxidecomputer/management-gateway-service/pull/76
It plumbs system LED control through `control-plane-agent`.
> Implement MGS LED control

- Cargo.lock
- Cargo.toml
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimlet/rev-d.toml
- app/gimletlet/app-dc2024.toml
- app/gimletlet/app-mgmt.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/psc/rev-c.toml
- app/sidecar/rev-b.toml
- app/sidecar/rev-c.toml
- build/net/src/lib.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/dump-agent-api/src/lib.rs
- task/dump-agent/Cargo.toml
- task/dump-agent/build.rs
- task/dump-agent/src/main.rs
- task/dump-agent/src/udp.rs
This is part of the https://github.com/oxidecomputer/hubris/issues/1217 saga, which begins with https://github.com/oxidecomputer/humpty/pull/4/files and also requires a Humility PR.
This Hubris PR adds an optional `net` feature to `dump-agent`.  When the feature is enabled, `dump-agent` listens on a UDP socket for messages which encode dump commands, using API types from `humpty` (see PR above).  These messages are a thin layer above the existing hiffy API.
Most of the code changes are in the `udp` module; changes in `ServerImpl` are mostly to make more functions callable from either hiffy or the `udp` module.
> Add network feature to `dump-agent`

- Cargo.lock
- Cargo.toml
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/lpc55xpresso/app.toml
- app/lpc55xpresso/src/main.rs
- idl/dump-agent.idol
- idl/jefe.idol
- task/dump-agent/src/main.rs
- task/dump-agent/src/udp.rs
- task/jefe/build.rs
- task/jefe/src/dump.rs
- task/jefe/src/main.rs
This PR implements single-task dumping in Hubris, mediated by the supervisor task.  It includes three new APIs:
- Dump a single task
- Dump a subregion of memory from a single task
- Reinitialize dump areas starting at a particular index
(see https://github.com/oxidecomputer/humpty/pull/5 for the associated UDP types)
Single-task dumping is between the supervisor and the kernel, and doesn't require the RoT!
Most of this PR is plumbing of various kinds:
- UDP messages to `dump-agent` → Idol messages to Jefe
- Idol messages to `dump-agent` -> Idol messages to Jefe
- Idol messages to Jefe → actual work being done 
Within `jefe::dump`, `dump_task` splits into four functions:
- Setup (`dump_task_setup`)
- Run (`dump_task_run`)
- `dump_task`, which now uses the above
- The new …
> Single-task dumping

- Cargo.lock
- Cargo.toml
This brings us up to `hubpack v0.1.2`
> Bump hubpack and gateway-messages

- drv/gimlet-seq-api/src/lib.rs
- drv/gimlet-seq-server/src/main.rs
This fixes #1268. On a machine with a correct CPU in SP3:
```
humility: ring buffer drv_gimlet_seq_server::__RINGBUF in gimlet_seq:
0  167        1        1 Ice40Rails(true, true)
1  196        1        1 Ice40PowerGoodV1P2(true)
2  217        1        1 Ice40PowerGoodV3P3(true)
3  259        1        1 IdentValid(false)
4  262        1        1 ChecksumValid(false)
5  265        1        1 Reprogram(true)
6  279        1        1 Programming
7  308        1        1 Programmed
8  311        1        1 RailsOff
9  314        1        1 Ident(0xde01)
10  320        1        1 A2Status(0x0)
11  343        1      446 ClockConfigWrite
12  355        1        1 ClockConfigSuccess
13 1131        1        1 V3P3SysA0VOut(Volts(0.171875))
14  357        1 …
```
> Gimlet sequencer should check for a processor

- task/net/src/server.rs
This watchdog panics the net task if a queue remains full for > 500 ms, to work around https://github.com/smoltcp-rs/smoltcp/issues/594
Tested on a bench with a hacked `udpbroadcast` to clog the pipes, and it seems to work fine.
> Add watchdog for QueueFull issue

- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimlet/rev-d.toml
- app/gimletlet/app.toml
- app/psc/rev-a.toml
- app/psc/rev-b.toml
- app/psc/rev-c.toml
- app/sidecar/rev-b.toml
- app/sidecar/rev-c.toml
Prior to this PR, attempting to call `Jefe.request_reset` via `udprpc` would time out:
```
% cargo xtask humility app/gimletlet/app.toml  -- --ip fe80::0c1d:7dff:feef:9f1d%eth0 hiffy -c Jefe.request_reset
Finished dev [optimized + debuginfo] target(s) in 0.21s
Running `target/debug/xtask humility app/gimletlet/app.toml -- --ip 'fe80::0c1d:7dff:feef:9f1d%eth0' hiffy -c Jefe.request_reset`
humility: connecting to fe80::0c1d:7dff:feef:9f1d%eth0
humility hiffy failed: Resource temporarily unavailable (os error 11)
Error: humility failed
```
because jefe returned an access violation:
```
14 udprpc                       1   6 FAULT: reply fault: task id #0/gen0, reason AccessViolation (was: wait: reply from jefe/gen0)
```
After this PR, attempting to call `Jefe.request_reset` via `udprpc` …
> Allow udprpc to send `Jefe.request_reset`

- Cargo.lock
- build/xtask/src/dist.rs
Depends on https://github.com/oxidecomputer/hubtools/pull/5 and https://github.com/oxidecomputer/lpc55_support/pull/58
> Bump lpc55_* and hubtools

- app/rot-carrier/Cargo.toml
- lib/lpc55-rot-startup/build.rs
Small work required to build an RoT image w/ `dice-mfg` feature.
> rot-carrier: Restore 'dice-mfg' feature.

- drv/i2c-devices/src/adm1272.rs
- drv/i2c-devices/src/bmr491.rs
- drv/i2c-devices/src/isl68224.rs
- drv/i2c-devices/src/ltc4282.rs
- drv/i2c-devices/src/max5970.rs
- drv/i2c-devices/src/mwocp68.rs
- drv/i2c-devices/src/raa229618.rs
- drv/i2c-devices/src/tps546b24a.rs
- idl/power.idol
- task/power/src/main.rs
Using absolute indexes into the `CONTROLLER_CONFIG` array isn't (easily) visible outside of Hubris.
This assumes that we don't have duplicate addresses, which is true for now (good enough!)
> Index Renesas blackboxes by i2c address

- task/net/src/server.rs
Using `can_send` is too optimistic; it will return `true` if there's room in the buffer but a max-length packet won't actually fit.  This results in a storm of `QueueFull` if
a) The host isn't replying
b) There's room in the buffer, **but**
c) The next packet is larger than available space
This PR switches to the single source of truth for socket happiness: did we get a `QueueFull`?
> Improve QueueFull watchdog

- app/gimlet/rev-b-lab.toml
- app/gimlet/rev-c-lab.toml
- app/gimlet/rev-d-lab.toml
- task/packrat/Cargo.toml
- task/packrat/src/gimlet.rs
This change set the default gimlet startup options to none, and adds a
new packrat task feature that is set in lab builds that sets the
default to be more verbose and boot with the kernel debugger loaded.
Fixes #1148
> Set production host startup options

- idl/power.idol
- task/power/src/main.rs
This is a building block for https://github.com/oxidecomputer/humility/issues/374
It's a very thin API; we expect to do most of the decoding on the Humility side.
```
matt@niles ~ () $ h -tgimlet hiffy -c Power.rendmp_dma_read -aaddr=0x5a,reg=0xE905
humility: attached to 0483:374f:000C001F4D46500F20373033 via ST-Link V3
Power.rendmp_dma_read() => 0xfaa
```
> Add `rendmp_dma_read` Idol command

- drv/gimlet-seq-server/src/main.rs
- drv/gimlet-state/src/lib.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/host-sp-comms/src/main.rs
- task/net/src/bsp/gimlet_bcd.rs
- task/power/src/bsp/gimlet_bcd.rs
- task/spd/src/main.rs
- task/thermal/src/bsp/gimlet_bcd.rs
The main goal of this change was to have some comments on the enum variants, but while attempting to reverse engineer the comments, I noticed that A2PlusMono is unused and removed it rather than documenting it.
> Document and tidy Gimlet PowerStates

- drv/gimlet-hf-server/src/bsp/gimlet_bcd.rs
We've been having flake with the QSPI flash on Gimlet C revs, some of which has been manufacturing errors, but not all of it.
It turns out we've got at least one board (serial '43) that appears to be assembled correctly, but whose QSPI circuit doesn't work at 40 MHz. The bits wind up shifting with respect to the clock, suggesting that we've got a propagation delay or rise time issue across the translator and mux.
This change lowers the speed to 33 1/3 MHz, which is stable on all the machines we've tried so far.
> gimlet-hf: reduce clock speed to 33MHz.

- Cargo.lock
- Cargo.toml
- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
We can use the existing "component active slot" messages the same way host flash does.
Depends on https://github.com/oxidecomputer/management-gateway-service/pull/86.
> Remove switch-default-image MGS handler.

- Cargo.lock
- Cargo.toml
- drv/sidecar-front-io/src/leds.rs
- drv/sidecar-front-io/src/transceivers.rs
- drv/transceivers-api/src/lib.rs
- drv/transceivers-server/src/main.rs
- drv/transceivers-server/src/udp.rs
- idl/transceivers.idol
This change is to support the control of the transceiver port LEDs over the network (see #1167). It does not implement control of the system LED via MGS (#1332).
Summary of changes:
* Support `LedState` and `SetLedState` `transceiver-messages`
* Adds some state to the `transceiver-server` to keep track of the state of LEDs, as well as functions to determine on vs off.
* Updates the `leds` module to use stronger typing, similar to the `transceivers` module
* Adds a compile-time fix for a hardware bug on Rev B QSFP Boards which swapped LEDs for 16<->17 and 18<->19
* Add a bunch of commands to the Idol interface to adjust LED state as well as modify brightness (via current and/or PWM). These mostly to support benchtop activity and do not need to stick around.
> Move transceiver LED control to the network

- drv/i2c-api/src/lib.rs
- drv/stm32xx-i2c-server/src/main.rs
- idl/power.idol
- task/power-api/src/lib.rs
- task/power/src/bsp/gimlet_bcd.rs
- task/power/src/bsp/gimletlet_2.rs
- task/power/src/bsp/psc_abc.rs
- task/power/src/bsp/sidecar_bc.rs
- task/power/src/main.rs
These are building blocks that allow us to
- Run `humility pmbus` over the network (https://github.com/oxidecomputer/humility/pull/382)
- Switch to fixed-PWM mode for debugging (pending implementation in Humility)
> Add Idol APIs for PMBus operations

- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
On the rot-carrier I added the caboose_reader task for testing purposes. A future commit will plumb up the caboose information as part of RotState.
> Add a default caboose to the RoT

- drv/user-leds/src/main.rs
This prevents a timer interrupt from being queued up and not delivered until the next time blinking is enabled, which would cause a double-blink.
(harmless, but might as well do it right)
> Always use dispatch_n for LED blinking

- Cargo.lock
All changes are internal to the type & all of the work happens on the mfg side of the message exchange.
This PR is a replacement for #1360 and resolves #1305
> Update `dice-mfg-msgs` to get rfd 303 platform id string format.

- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
Our stack margin prior to this PR was 24 bytes; after this PR, we _usually_ see a stackmargin of 536 bytes (i.e., 24+512), but after running sufficiently-many requests for state from MGS, we see it drop to 432 bytes. Cliff suggests this is from getting an interrupt at an inopportune time. This explains what we were seeing in #1374: if we received such an interrupt while the update was running, it would trigger a SO of `update_server`, explaining the "no update started" error we saw.
Fixes #1374.
> Bump lpc55-update-server stack size up by 512

- drv/transceivers-server/src/main.rs
When I retooled the internal front-io LEDs logic I failed to change the _state_ of the system LED to `On`, so the old initialization process would turn it on directly (which lasted for for a single tick) and then the update loop would see the state was still in `Off` state and shut it off. This change just modifies the initialization process to update the state correctly and the loop will do the work of turning it on.
This resolves https://github.com/oxidecomputer/hubris/issues/1382
> Fix sidecar system LED default state

- Cargo.lock
- app/oxide-rot-1/app-dev.toml
- task/jefe/Cargo.toml
This switches the "default" app/oxide-rot-1/app.toml to build a production RoT config. The concrete differences are:
- An identity key in flash is now required. The system will halt at first boot and try to get one over the UART from the manufacturing station.
- Development stuff like Hiffy is removed.
For running a self-signed RoT config on a board, use the new app-dev.toml file instead.
Fixes #1384.
> oxide-rot-1: switch to prod settings, add new dev config

- app/sidecar/rev-b.toml
- app/sidecar/rev-c.toml
This adds the following missing devices to the manifest:
* U7: `V3P3_SYS_A2` (TPS546B24A)
* U15: `V3P3_QSFP0_A0` (TPS546B24A)
* U18: `V3P3_QSFP1_A0` (TPS546B24A)
As with other front-io devices, these are marked with `removable = true` since a Sidecar mainboard does not require a front-io board to be connected to operate.
Both QSFP rails have 3 phases (each a unique device). The devices in the manifest act as the I2C controller with the remaining two devices being targets.
All other devices of importance on the front-io board have been accounted for already: 
* I2C: FRUID, GPIO Expander, Left/Right LED Controllers
* SPI: FPGA(s)
* Sensors: Transceiver's thermals
The FPGAs proxy communications to the transceivers and the technician port PHY, so they do not exist in the manifest.
Fixes #1381
> Adds missing TPS546b24As on the front-io i2c bus

- sys/userlib/src/macros.rs
The `:vis` syntax type lets us remove some copypasta introduced in #1357.
> Remove duplicate task_slot! definition

- Cargo.lock
- lib/dice/Cargo.toml
- lib/lpc55-rot-startup/Cargo.toml
- lib/lpc55-rot-startup/src/dice.rs
- lib/lpc55-rot-startup/src/dice_mfg_usart.rs
I ran across this while trying to cause the `attest` task from #1378 to behave badly as described in: 
https://github.com/oxidecomputer/hubris/pull/1378#discussion_r1220440263. While disabling the dice features in `lib-lpc55-rot-startup` I noticed that the dependency on the `dice` crate remained. This was caused by `lib-lpc55-rot-startup` not listing the dependency as optional & enabled by the dice features.
This PR includes additional cleanup renaming the dice library from `dice` to `lib-dice` to align with project conventions & prevent conflicts with feature names.
> Dice optional

- drv/ignition-api/src/lib.rs
- idl/ignition.idol
Fixes this issue:
```
matt@lurch ~ (sidecar-sp) $ h hiffy -c Ignition.send_request -aport=34,request=SystemPowerReset
humility: attached to 0483:374e:0028001E4741500720383733 via ST-Link V3
humility hiffy failed: IgnitionError matches more than one enum: drv_ignition_api::IgnitionError as GOFF 0x0000331d (object 23), gateway_messages::sp_to_mgs::ignition::IgnitionError as GOFF 0x0000b8e8 (object 23)
```
> Fully specify `IgnitionError` type in Idol API

- drv/stm32h7-startup/src/lib.rs
The DBGMCU block has a facility for intercepting clocks to various peripherals during debug halt. This is nice, because otherwise the I2C transaction timeout counter keeps on counting while Humility has halted the processor.
This means that running, say, humility tasks, can cause I2C timeouts while the debugger extracts information, appearing to reproduce various I2C failures but actually just creating new and exciting ones.
So, this change turns on the debug freeze bits for the I2C controllers.
> stm32h7-startup: stop I2C timeout during debug halt

- drv/ignition-api/src/lib.rs
- drv/ignition-server/src/main.rs
- idl/ignition.idol
Humility needs a bit of help to distinguish between the GOFFs in `drv_ignition_api` and re-exported versions in `gateway_messages`. Being explicit helps.
> Properly scope types in Ignition Idol interface

- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gimletlet/app-mgmt.toml
- app/gimletlet/app.toml
- app/sidecar/rev-b.toml
- app/sidecar/rev-c.toml
- idl/jefe.idol
- task/jefe-api/src/lib.rs
- task/jefe/src/main.rs
- task/net/src/bsp/gimlet_bcd.rs
- task/net/src/bsp/psc_a.rs
- task/net/src/bsp/psc_bc.rs
- task/net/src/main.rs
This adds a method for tasks to restart themselves without indicating a fault, which has the advantage of bypassing Jefe's crash-dump logic for deliberate restarts.
Currently the only case of a deliberate restart is in net, for the receive watchdog. This should knock about 66ms off each firing of that watchdog.
I initially implemented this as a syscall, but @mkeeter noted it could be done entirely outside the kernel -- and so here it is. Long live the emokernel.
> Add Jefe::restart_me and use it for net watchdog.

- Cargo.lock
- Cargo.toml
- app/lpc55xpresso/app-sprot.toml
- app/lpc55xpresso/app.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
- build/xtask/Cargo.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
These files are unused, misleading, and potentially dangerous.  Let's not ship them in all our RoT archives.
> Remove CMPA and CFPA from Hubris archives

- drv/i2c-api/src/lib.rs
- drv/stm32xx-i2c-server/src/main.rs
- drv/stm32xx-i2c/src/lib.rs
Draft commit comment:
```
After the fix to #1413, the system is unwilling to ignore mux related
errors -- which has generated a problem on some lab systems that are
missing muxes:  because we can never get the bus into a known mux
state these systems now become entirely unusable, as even devices that
aren't on the missing segments are not accessible.  This fixes that by
observing that a mux that is affirmatively missing -- that is, one
that doesn't reply to its in-band management at all -- can be assumed
to have segments that are similarly missing (and therefore as good as
disabled).  This (naturally) doesn't change the fact that accessing
any devices attached to the missing mux will generate an error, but it
allows the system to broadly drive on absent accesses to those
devices.
```
> better handle missing I2C muxes

- lib/lpc55-rot-startup/src/handoff.rs
> lpc55-rot-startup: clear unused Handoff area when storing

- app/lpc55xpresso/app.toml
- lib/lpc55-romapi/src/lib.rs
ROMAPI's flash_erase_verify only indicates that at least one page in
the range is programmed.  validate_programmed needs to call that on
each individual flash page to ensure that all of them are programmed.
Fixes #1432
> lpc55_romapi: fix validate_programmed

- Cargo.lock
- app/lpc55xpresso/app-sprot.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
- drv/lpc55-sprot-server/Cargo.toml
- drv/lpc55-sprot-server/src/handler.rs
- drv/sprot-api/Cargo.toml
- drv/sprot-api/src/error.rs
- drv/sprot-api/src/lib.rs
- drv/stm32h7-sprot-server/src/main.rs
- idl/sprot.idol
- task/attest-api/Cargo.toml
This allows us to use hiffy in the SP to get certs out of the RoT.
> Add plumbing required to get certs from the attest task via sprot.

- drv/i2c-api/src/lib.rs
- drv/stm32xx-i2c-server/src/main.rs
> fix i2c_driver panic/stack overflow + I2C resilience

- drv/gimlet-seq-server/src/main.rs
This helps us correlate events to the blackbox in #1438
> Add timestamp to sequencer `SetState` log

- drv/transceivers-server/src/udp.rs
Otherwise, we copy `MessageKind::HostToSp` from the header, which makes the host mad.
> Reply with MessageKind::Error when reporting an error

- Cargo.lock
- task/monorail-server/Cargo.toml
- task/monorail-server/src/bsp/sidecar_bc.rs
To avoid spurious calls to `Monorail.reinit`, the 10G link watchdog checks whether the PCIE host reset bit is set.
Unfortunately, this bit changed from bit 0 to bit 1 in #1454; this broke the VSC7448 side of the watchdog, resulting in the link staying down if `dendrite` restarted on the Scrimlet.
This PR switches to using the bit's canonical definition in our register file, which is less likely to be wrong.
> Fix 10G watchdog checks

- task/thermal/src/bsp/gimlet_bcd.rs
- task/thermal/src/bsp/sidecar_bc.rs
- task/thermal/src/control.rs
Previously, devices in the thermal loop were either removable or not, marked by a boolean flag.
This PR adds a third type of device (`RemovableAndErrorProne`) and changes that flag into an `enum`.
The new type of device is applicable to our U.2s: it means that upon _any I2C error_, we treat the device as **safely absent**.  Previously, only a `NoDevice` error would treat the device as safely absent; this remains the case for devices marked `Removable`.
> Add U.2 error handling

- Cargo.lock
- Cargo.toml
- app/lpc55xpresso/app-sprot.toml
- app/lpc55xpresso/app.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
- idl/attest.idol
- task/attest-api/src/lib.rs
- task/attest/Cargo.toml
- task/attest/src/main.rs
This function is *not* idempotent: if the 'record' function is called with the same parameters repeatedly the measurement log will eventually fill up resulting in an error. The measurement log is just an array of measurements (aka [u8; 32]) that is managed in an ArrayVec. The 'record' function takes an enum parameter identifying the hash algorithm and a lease holding the digest. We pass the digest as a lease partially because humility / hiffy can't pass arbitrary arrays as parameters, but also because it's possible that in the future we'll need to support digests with varying lengths.
> attest: Add function to record a measurement observed by the platform.

- .github/workflows/test.yml
For some reason, you need a secondary `name` for this check to show up as a branch protection option.
(I also decapitalized "Tests" to match our other CI workflows)
> Add name for `tests` workflow

- Cargo.lock
- Cargo.toml
- app/oxide-rot-1/app.toml
- lib/dice/src/mfg.rs
Tested by modifying lpc55expresso to use dice-mfg, flashing to lpc55xpresso w/ secure boot enabled, and running `dice-mfg get-key-slot-status` (from https://github.com/oxidecomputer/dice-util/pull/88) which reported all slots enabled as expected.
Depends on https://github.com/oxidecomputer/dice-util/pull/88 so CI will fail until that is merged.
> dice-mfg: allow querying secure boot key slot status

- app/sidecar/base.toml
- task/thermal/src/bsp/sidecar_bc.rs
In a [previous comment](https://github.com/oxidecomputer/hubris/pull/1400#discussion_r1223337891) I stated:
>The drawing we got from SD notes an inlet vs outlet fan. In our system the inlet fan is more "north" and connects to pwm0/tach0, while the outlet fan is more "south" and connects to pwm1/tach1.
This is incorrect, for whatever reason my brain that day was thinking that the inlet fan was more towards the back (aka North) while the outlet fan was towards the front (aka South). This is backwards as we draw air from front to back, not back to front, which means that the inlet fan is _actually_ South while the outlet fan is North. This commit cleans up that error.
There aren't any other system impacts beyond fixing up the comment and fan naming.
> sidecar: fix comment about fan rotor ordering

- .github/workflows/documentation.yml
The `documentation` workflow is triggered to run on both all pull requests and pushes to `master`. The former cannot (and should not) succeed on PRs from the public, even if the workflow is manually triggered by some with write permissions  (Oxide). This has caused checks by public PRs to fail, such as https://github.com/oxidecomputer/hubris/pull/1488 with https://github.com/oxidecomputer/hubris/actions/runs/5838750982/job/15876474521?pr=1488.
Additionally, we probably don't want to trigger the workflow on pull requests, because it'd mean the live GH pages are updated before a PR is accepted. For example: https://github.com/oxidecomputer/hubris/pull/1489/files can be seen on https://oxidecomputer.github.io/hubris/reference/.
This PR just removes the trigger on `pull_reqeusts` while …
> Remove the `pull_request` trigger for the `documentation` workflow

- doc/interrupts.adoc
> doc(interrupts): fix variable name in code sample

- app/oxide-rot-1/app.toml
- lib/lpc55-rot-startup/src/lib.rs
The beacon register can only be set during debug authentication. If this register is set, enable debugging.
> Enable RoT debug when the beacon is set

- drv/stm32h7-eth/src/ring.rs
The stm32h7 ethernet driver uses a code sequence bult from explicit tests against the size of the ring to wrap around to the beginning, for both Tx and Rx rings.
I had asked about this sequence when I first joined, and Cliff said it was due to lack of an integer modulus operator and the compiler generating very poor code generation if the `%` operator was used:
https://matrix.to/#/!uMMSVUNAgMdoTtyJPR:oxide.computer/$JY-kOZprRrGzFFG6KoVRQ_a7RB9KFbWR6GQuKFW_azk?via=oxide.computer&via=unix.house
I noticed this again when working on the ring tail pointer fixes and decided to take a look at the generated code; perhaps it had changed?  I think perhaps it has (though have little basis for comparison against older compilers).
The generated code has become a `udiv` followed by an `mls`, which was …
> Replace explicit wrapping `if` with modular arith

- drv/stm32h7-eth/src/lib.rs
- drv/stm32h7-eth/src/ring.rs
At its root, #750 is about a race condition between the DMA engine and the STM32 Ethernet, and the host CPU.  We can prevent this race by properly maintaining the Rx tail pointer.
Some background information to contextual this change:
The device and host participate in a simple protocol to drive a state machine: the host gives descriptors to the device that specify buffers to DMA incoming Ethernet frames into. The host gives a descriptor to the device by setting the ownership bit and setting the tail pointer: this driver handles the former properly, but does not handle the latter correctly.
The device consumes these descriptors as frames arrive and it DMAs them host memory.  In turn, the device lets the host know that it is done with a descriptor by doing two things:
1. Resetting the …
> Fix #750 by maintaining the Rx tail pointer

- drv/stm32h7-eth/src/lib.rs
- drv/stm32h7-eth/src/ring.rs
Analagous to #1493, we should maintain the Tx tail pointer properly, as well.  Note that since the device won't examine a Tx descriptor until the tail pointer is set appropriately, we can relax stores and rely on the barrier in `tx_notify` to flush everything to RAM properly before writing the tail pointer and kicking off a DMA.
> stm32h7-eth: Properly maintain Tx tail pointer

- Cargo.lock
- Cargo.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
- drv/transceivers-server/src/main.rs
- idl/sensor.idol
- task/control-plane-agent/src/inventory.rs
- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/sensor-api/src/lib.rs
- task/sensor-polling/src/main.rs
- task/sensor/src/main.rs
- task/thermal/src/main.rs
This PR bumps MGS and implements the new `SensorRead` message.
It also ends up making the `Sensor` API more flexible:
- We now distinguish between device errors (`NoData`) and API errors (the new `enum SensorApiError`).  The existing existing `SensorError` type remains the union of both types, but we can use `SensorApiError` for almost all `Sensor` API return values
- Add a new `Sensor.get_raw_reading` function, which maintains the distinction between device and API errors in its return type.  This 
- All `Sensor` functions are idempotent, so we can remove the `ServerDeath` variant
- Added new APIs to get the last data or error reading, including the timestamp
- Extend the `LastReading` type so that we know if we've _ever_ seen a data or error value; this allows us to correctly return …
> Add MGS sensor reading

- drv/sidecar-front-io/src/phy_smi.rs
- drv/sidecar-mainboard-controller/src/tofino2.rs
- drv/sidecar-seq-server/src/front_io.rs
- drv/sidecar-seq-server/src/main.rs
- drv/sidecar-seq-server/src/tofino.rs
- idl/sidecar-seq.idol
- task/monorail-server/src/bsp/sidecar_bc.rs
- task/net/src/bsp/sidecar_bc.rs
Monorail monitors the 10G link with Tofino and periodically restarts the task if this link is not up. This in turn causes the technician port PHY to flap which is disruptive while working with `pilot racktest`.
In order to reduce spurious restarts the PCIe link with Tofino is monitored and restarts are only performed if the link is up, assuming the 10G port is down otherwise. In addition logging in the sequencer task is improved, making the events more accurate and cutting down on noise.
The following ringbuf snippets are shown when a chassis is freshly booted and the PCIe link with a Gimlet is not (yet) up:
```
humility: ring buffer drv_sidecar_seq_server::__RINGBUF in sequencer:
0  802        1        1 FpgaInit
1  810        1        1 …
```
> Sidecar: avoid Monorail restart if Tofino PCIe link not up

- Cargo.lock
- Cargo.toml
We also enable the `extra-traits` feature of `syn`, which `derive-idol-err` needs but we were previously only picking up via feature unification: zerocopy-derive 0.3.1 enabled it, but zerocopy-derive 0.6.4 depends on syn2 so we lost it.
> Bump gateway-messages and zerocopy to latest

- app/lpc55xpresso/app-sprot.toml
This removes use of the now removed ITM feature in jefe as well as increasing the flash size required by recent sprot changes.
> Update lpc55xpresso app-sprot.toml accounting for recent changes.

- app/lpc55xpresso/Cargo.toml
- app/oxide-rot-1/Cargo.toml
- app/rot-carrier/Cargo.toml
- lib/lpc55-rot-startup/Cargo.toml
- lib/lpc55-rot-startup/src/lib.rs
Locking via CMPA is permanent and can't be undone. We can at least mimic part of the behavior by setting the flash lock registers.
> Add feature to mimic locking

- Cargo.lock
- app/oxcon2023g0/Cargo.toml
- app/oxcon2023g0/README.md
- app/oxcon2023g0/app.toml
- app/oxcon2023g0/build.rs
- app/oxcon2023g0/src/main.rs
- build/xtask/src/flash.rs
- chips/stm32g0/memory-g030x6.toml
- drv/user-leds/src/main.rs
- sys/kern/Cargo.toml
- sys/kern/src/fail.rs
- task/jefe/Cargo.toml
This applies some size improvements to enable halfway-useful Hubris systems on 32kiB STM32G030 parts, which happens to be the part I'm putting on the 0xCon demo boards. Net effects:
- Jefe can now be compiled without ringbuf for a savings of a few kiB. This seems acceptable since it's somewhat unusual to debug Jefe issues, particularly in simpler systems.
- Kernel panic messages can now be disabled, which knocks 8 kiB off. When built in this mode, the kernel will still set the KERNEL_HAS_FAILED boolean for Humility, but will not fill out the KERNEL_EPITAPH block (which won't exist). This seems like an ok compromise since kernel panics on Hubris are very uncommon.
I've added an app (oxcon2023g0) for the new board and done the shotgun changes required to make it work (someday I still want …
> STM32G0 size improvements.

- Cargo.lock
- app/oxcon2023g0/app.toml
- drv/user-leds/Cargo.toml
- drv/user-leds/src/main.rs
- lib/task-config/src/lib.rs
- sys/kern/src/fail.rs
We've been including the pong task in most basic/starter images for the
sole purpose of blinking some LEDs.
For the simplest case of a small board with a single debug LED and not a
lot of flash, this is quite wasteful (burns about a kiB). To conserve
resources on such boards, I've added a mechanism for configuring the
user-leds driver to start some LEDs blinking automatically.
Unlike with pong, the LEDs will all blink together, not in a sequence.
Such is the cost of frugality. On boards with one LED the distinction is
not material.
This imposes no size cost on existing uses of user-leds because the
configuration is evaluated at compile time, and will compile away. On
the oxcon2023 board it costs about 16 bytes to set the LED a-blinkin'.
>  drv/user-leds: optionally blink some LEDs at start 

- Cargo.lock
- app/oxcon2023g0/app.toml
- app/oxcon2023g0/src/main.rs
- drv/stm32xx-i2c/Cargo.toml
- drv/stm32xx-i2c/src/lib.rs
- drv/user-leds/src/main.rs
- Add insomniac feature to suppress sleep at WFI because Humility
doesn't know how to attach to an STM32G0 that is sleeping.
- Fix bug in user leds "blink on start" feature that failed to actually
set up blink on start, because there are several pieces of data to
update and I missed two of them.
>  Final(?) fixes for Oxcon board.

- Cargo.lock
- app/lpc55xpresso/app.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
- drv/lpc55-sprot-server/src/handler.rs
- drv/sprot-api/src/lib.rs
- drv/stm32h7-sprot-server/src/main.rs
- idl/attest.idol
- idl/sprot.idol
- task/attest-api/src/lib.rs
- task/attest/Cargo.toml
- task/attest/src/main.rs
This PR:
- replaces use of ArrayVec for maintaining the measurement log with a custom type that can be serialized with hubpack
- adds a 'log' and 'log_len' function to the Attest IDL
- adds a 'log' and 'log_len' function to the Sprot IDL
This is sufficient to expose the measurement log through the hiffy task on either the RoT or the SP.
> Expose measurement log.

- .github/workflows/release-builds.yml
- .github/workflows/release.yml
The release tagging seems to be working as expected, drop the draft option. Also fix typo for building devboard releases.
> Fix release tagging

- app/lpc55xpresso/app-sprot.toml
This app*.toml wasn't compiling/linking. Fixed.
> Fix app/lpc55xpresso/app-sprot.toml so that it compiles after SpRot changes

- .github/workflows/build-boards.yml
- .github/workflows/build-one.yml
One upon a time we needed to manually specify the compilation triple. This is no longer true.
> Drop compilation triple

- README.mkdn
This was pointing at an old workflow that no longer exists. 
Shout-out to https://news.ycombinator.com/item?id=38032561 for raising this issue.
> Fix build badge

- drv/gimlet-seq-server/src/main.rs
This pulls the fault pin low (active) shortly after the sequencer task first runs, and then sets it high (inactive) only once we get up to the IPC loop.
Failures in the sequencer startup tend to cause panics, which will have the effect of holding the pin low as the task is repeatedly restarted. This also means we will be able to externally observe any other restart of the task.
> gimlet-seq-server: start driving fault pin.

- README.mkdn
Trivial mention of a dependency required to build `humility`.
> Mention a dependency required to build humility

- Cargo.lock
- build/i2c/src/lib.rs
Currently the build code may emit structures/enums in a different order each build. This produces correct code but is not reproducible. Ensure the build output happens the same way each time by sorting before outputing. We don't actually care how things are sorted, only that they are sorted.
> Make build output reproducible

- task/host-sp-comms/src/main.rs
Fixes https://github.com/oxidecomputer/hubris/issues/1172
> Set host flash Mux back to SP once host is booted

- app/gimlet/base.toml
- drv/i2c-devices/src/max5970.rs
- idl/power.idol
- task/power/src/bsp/gimlet_bcde.rs
- task/power/src/bsp/gimletlet_2.rs
- task/power/src/bsp/psc_abc.rs
- task/power/src/bsp/sidecar_bc.rs
- task/power/src/main.rs
Draft commit message:
```
Traces peaks (recorded minimumm and maximum) from the MAX5970, as well
as attempts to infer and trace resets (albeit with a mechanism that
can result in false negatives), along with some refactoring to get
board-specific code (e.g., MAX5970 instrumentation) in the board
support package.  Also includes an Idol interface to clear the
BMR491's event buffer.
```
Note that this work increases the flash size of the `power` task, but that already needs to be done for #1579.
> trace MAX5970 peaks + resets

- Cargo.lock
- Cargo.toml
Upstream took our patch adding zeroize support. This was released in version 0.3: https://github.com/ycrypto/salty/pull/26. Updating this package required updating the sprockets-rot package as well. This should remove the need for our fork of the salty repo.
> Update salty to version 0.3

- Cargo.lock
- Cargo.toml
- task/attest/Cargo.toml
- task/attest/src/main.rs
This commit moves the types used in the attest IDL / API into a library crate in the dice-util repo. This enables consumers outside of hubris to use the API.
> attest: move types in attest task IDL / API into external crate

- app/lpc55xpresso/app-sprot.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
#1597 bumped `syn` and `proc-macro2`.  For some reason, this slightly changes the size of the `sprot` task, so `master` is not building for me right now:
```console
Error: task sprot: needs 47360 bytes of flash but max-sizes limits it to 47328
```
[Last time I investigated](https://matrix.to/#/!jxnlDLnJsVaIRstnrt:oxide.computer/$pCYj2H5LWUDkQwx_svMii1GZiOkXxpHA26BOjJzXPBA?via=oxide.computer&via=unix.house&via=matrix.org), I came to the conclusion that bumping `proc-macro2` caused LLVM functions to be emitted in a different order, which changed inlining behavior, which pushed one task over the size limit (and there were literally no changes in the generated LLVM IR).
> Bump sprot sizes to fix build

- Cargo.lock
- Cargo.toml
- drv/stm32xx-sys/src/main.rs
- lib/host-sp-messages/src/lib.rs
- sys/abi/src/lib.rs
- sys/kern/src/descs.rs
- task/thermal/src/bsp/gimlet_bcdef.rs
- task/thermal/src/bsp/sidecar_bcd.rs
This brings us up to the most recent release, and has some nice properties, like there now being a trait that describes the bitflags API instead of it all being open-coded. (This is the property that motivated this change.)
There are some slightly annoying aspects, like the operations in that trait no longer being const (because we don't have const impls yet). So, this required some surgery.
> Update bitflags to 2.x

- Cargo.lock
- app/sidecar/base.toml
- build/kconfig/src/lib.rs
- build/xtask/src/clippy.rs
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- build/xtask/src/main.rs
- build/xtask/src/sizes.rs
- sys/kern/build.rs
This PR modifies the build system to let flash use all available MPU regions, resulting in tighter packing and smaller total image size.  This shrinks the `sidecar-rev-c` image by 256 KiB, and the `gimlet-f` image by 188 KiB.
In other words, tasks go from having exactly 1 flash region to _at least_ 1 flash region; this is mostly plumbing that change from `suggest_memory_region_size` all the way through the `kconfig`.
The change does makes task packing trickier, because tasks can be placed in one of two orientations: largest-chunk-first, or largest-chunk-last.  I went for a very dumb O(N^2) algorithm that checks every unplaced task and picks the best; we're far from having > 100 tasks, so I'm not worried about bad scaling (famous last words!).
In addition, it updates `xtask/src/sizes.rs` …
> Multi region packing

- drv/gimlet-seq-api/src/lib.rs
- drv/gimlet-seq-server/src/main.rs
Currently, the sequencer task uses `unwrap()` on I2C bus operations.
However, these may fail due to transient bus errors, or fail permanently
for reasons wholly outside the sequencer task's control. As discussed in
issue #1205, it's incorrect for the sequencer task to unwap these
errors, as panicking results in the task being restarted. On fatal bus
errors, this means we crash loop.
Instead, this commit changes the `gimlet-seq` task to retry failed I2C
reads/writes up to three times, and, if they still fail, transition to a
permanent failed state, setting the FAULT net to Ignition to indicate
that the Gimlet must be power-cycled.
> gimlet-seq: retry I2C errors, or die trying

- lib/ringbuf/src/lib.rs
- task/control-plane-agent/src/main.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
The final commit is the relevant one, description copied below. The other two commits are cleanups on the way there.
---
Our ability to debug #1613 was hampered by the control-plane-agent
ringbuf being overwritten, on average, every 1.5 seconds. This adds a
secondary ringbuf that only holds "important" events -- specifically,
commands received from the network that affect the host.
Unfortunately due to the BSP structure in the agent right now, this
required copy-pasting a change into three files. Fixing that appears
difficult.
> Yo dawg i heard you like ringbufs

- .github/workflows/build-one.yml
- .github/workflows/documentation.yml
- .github/workflows/formatting.yml
- .github/workflows/test.yml
There are a zillion CI warnings (one per build) about how `checkout@v3` is going to stop working (e.g. [here](https://github.com/oxidecomputer/hubris/actions/runs/7995668611)).  This looks like an easy fix!
> Bump CI checkout action to fix warnings

- drv/gimlet-seq-server/src/main.rs
I introduced a regression in the `gimlet-seq` task in commit 4cb9eddab7952ffa760762bfb2953b584696712f, where the call to `idol_runtime::dispatch_n` was inadvertently replaced with `idol_runtime::dispatch`. This resulted in the `gimlet-seq` task ignoring notifications that it previously handled. In particular, the bug causes the `gimlet-seq` task to ignore the timer notifications it sets for itself to poll the sequencer state after reaching A0. This manifests as a failure to power on the T6, as described in issue #1625.
This commit fixes the regression by changing `dispatch` back to `dispatch_n`. Thanks to @wesolows for identifying the root cause of this bug!
I've tested this on Gimlet c71 in the lab, and after applying this patch, the T6 once again powers on as expected:
```console …
```
> gimlet-seq: don't ignore notifications in dispatch

- task/net/src/main.rs
- task/net/src/server.rs
- task/net/src/server_basic.rs
- task/net/src/server_vlan.rs
Now that #750 is closed and we're pretty confident in the fix, we can stop rebooting the netstack periodically. This should save resources (by not constantly dumping and restarting), and also get us back into the state where any task's generation number advancing is Probably Bad.
> net: remove MAC RX activity watchdog.

- lib/ringbuf/src/lib.rs
This knocks about 120 bytes off of each ringbuf in a task (because the Ringbuf::entry routine gets specialized for each ringbuf, and this makes that routine smaller).
Reduces Gimlet flash image size by 3.4%.
> ringbuf: rewrite entry to have no panics

- drv/ksz8463/src/lib.rs
- drv/vsc-err/src/lib.rs
- task/monorail-server/src/bsp/sidecar_bcd.rs
- task/monorail-server/src/main.rs
- task/net/src/bsp/gimletlet_nic.rs
- task/net/src/bsp/nucleo_h7.rs
- task/net/src/bsp/sidecar_bcd.rs
- task/net/src/mgmt.rs
This knocks about 3.7 kiB (!) off Gimlet's netstack task size, by removing much of its dependence on the formatting machinery invoked by unwrap. (It's not all gone, because smoltcp still uses it.)
> net: fix several unwraps of complex errors

- Cargo.lock
PR oxidecomputer/idolatry#40 updates `idol`'s code generation to use the `quote` crate for generating Rust code, rather than representing it as a string. This commit updates Hubris' dependency on `idol` to oxidecomputer/idolatry@c5222fe79b55e007db06bfdab0ea7e2b1db28629.
> update `idol` to use `quote!` in codegen

- app/oxcon2023g0/app.toml
The size requirement increased, because the build system managed to pack the firmware tighter and free up 9.4% of flash. But, this means bigger descriptor tables, which currently have to be accounted for in the kernel's size allotment.
> oxcon2023g0: adjust kernel size allocation

- lib/counters/derive/Cargo.toml
- lib/counters/derive/src/lib.rs
- lib/counters/examples/count_generic.rs
- lib/counters/src/lib.rs
- task/jefe/build.rs
Currently, placing the `#[derive(Count)]` attribute on a generic `enum`
doesn't compile. This branch changes the `#[derive(Count)]` code
generation to support generic types. If a type parameter is used as a
field with the `#[count(children)]` attribute, the generated counters
struct will also be generic over that type parameter, and contain the
counters type for that type's `Count` implementation, with a `where`
clause requiring that type to also implement `Count`. If the type
parameter is *not* used in a field that has the `#[count(children)]`
attribute, the generated counters struct needn't be generic over that
type parameter,[^error] so we exclude it from the counter's struct list
of type params. This required a bit of a complex change to the code
generation to implement.
I've added a …
> counters: allow deriving `Count` for generic types

- drv/gimlet-seq-server/src/main.rs
- lib/counters/examples/count.rs
- lib/counters/src/lib.rs
Currently, we have a bunch of ringbuf enum variants with single `bool` fields, like `Trace::NICPowerEnableLow(bool)` in `gimlet-seq-server`. This commit adds a `counters::Count` implementation for `bool`, allowing us to place `#[count(children)]` on these variants and generate separate `true` and `false` counters for them.
> counters: add support for counting `bool`s

- lib/counters/src/lib.rs
This commit adds implementations of the `counters::Count` trait for
`Option<T> where T: Count` and `Result<T, E> where T: Count, E: Count`.
Currently, we aren't using these anywhere, but we _will_ be! :D
> counters: implement `Count` for `Option`/`Result`

- Cargo.lock
- drv/fpga-devices/src/ecp5_spi.rs
- drv/fpga-devices/src/ecp5_spi_mux_pca9538.rs
- drv/ice40-spi-program/src/lib.rs
- drv/ksz8463/Cargo.toml
- drv/ksz8463/src/lib.rs
- drv/spi-api/src/lib.rs
- drv/stm32h7-spi-server-core/src/lib.rs
- drv/stm32h7-spi-server/src/main.rs
- idl/spi.idol
Currently, the SPI API has a single big error enum which it returns from
all IPCs. This isn't all that great: for example, a `NothingToRelease`
error can be returned from the `Spi::read` IPC, which...doesn't make a
ton of sense. Additionally, many of these error variants are returned
only in the event of a programmer error in a client task, rather than
expected runtime errors, and probably should be `reply-fault`s rather
than error codes.
Per @cbiffle on Matrix:
> Re: the SPI errors, we've got
>
> - `TaskRestarted` - sure makes sense, also probably not appropriate to
>   unwrap though
> - `NothingToRelease` - should be reply-fault, indicates that you're
>   acting like you've locked the device when you haven't.
> - `BadDevice` - should be reply-fault, indicates that you've made up a
> …
> spi: A reSPIte from excessive error codes

- lib/ringbuf/Cargo.toml
- lib/ringbuf/src/lib.rs
The `ringbuf` crate has a `"disabled` feature flag, which disables ring buffers, intended for use on memory-constrained targets. Currently, setting the `"disabled"` feature flag still enables counters for ring buffers declared using the `counted_ringbuf!` macro, because counters generally require less RAM than full ringbufs. However, on some targets, even counters are too large, especially when a ringbuf's entry type has too many variants (e.g. see [this comment][1] from @bcantrill --- the `i2c_driver` ringbuf must disable counters in order to fit in Donglet's RAM).
Therefore, this commit adds an additional `"counters-disabled"` feature flag to the `ringbuf` crate, to allow disabling counters as well as ring buffers.
[1]: https://github.com/oxidecomputer/hubris/pull/1657#discussion_r152535 …
> counters: add `"counters-disabled"` feature flag

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/donglet/app-g031.toml
- app/gemini-bu/app.toml
- app/gimlet/base.toml
- app/gimletlet/base-gimletlet2.toml
- app/psc/base.toml
- app/sidecar/base.toml
- drv/stm32xx-i2c-server/src/main.rs
- drv/stm32xx-i2c/Cargo.toml
- drv/stm32xx-i2c/src/lib.rs
- task/spd/src/main.rs
Draft commit message:
```
This addresses #1631 by adding a (long) timeout whenever we wait for
an interrupt from the I2C controller.  This timeout shouldn't ever
fire:  if it does, something seriously is amiss, so we record more or
less everything we can out of the I2C controller and explicitly panic.
```
> prevent I2C from hanging on lost interrupt

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- chips/stm32h7/chip.toml
- drv/stm32h7-fmc-demo-server/Cargo.toml
- drv/stm32h7-fmc-demo-server/README.md
- drv/stm32h7-fmc-demo-server/build.rs
- drv/stm32h7-fmc-demo-server/src/main.rs
- drv/stm32xx-gpio-common/src/lib.rs
- idl/fmc-demo.idol
This is an exercise fixture for the PSRAM mode of the Flexible Memory Controller on the STM32H7, for evaluating FPGA interface options. It lets you do many ill-advised things via IPC. They all appear to work, no matter what the datasheet implies.
Good luck!
> drv/stm32h7-fmc-demo: ill-advised memory controller

- Cargo.lock
- Cargo.toml
- sys/userlib/Cargo.toml
- sys/userlib/src/critical_section.rs
- sys/userlib/src/lib.rs
The embedded ecosystem is starting to catch up with the fact that not all of us are running a single address space in privileged mode, and crates like `portable-atomics` may now be in a state where we could rely on them.
Implementing things like atomic polyfills on platforms without atomics requires some way to control concurrency, and crates seem to be standardizing on the `critical-section` crate -- which unlike the old critical section in `cortex-m`, can be customized for our purposes.
So, this commit adds a backing implementation to `userlib` to allow the `critical-section` crate to be used in tasks. I'm slightly alarmed to note that our dependency graph already includes a very old version of `critical-section`, but I'm _pretty sure_ that should be safe since we've never provided an …
> userlib: add a critical-section impl for task code.

- drv/transceivers-server/src/udp.rs
- task/control-plane-agent/src/main.rs
- task/dump-agent/src/udp.rs
- task/gimlet-inspector/src/main.rs
- task/net-api/src/lib.rs
- task/net/src/server.rs
- task/udpecho/src/main.rs
- task/udprpc/src/main.rs
Since its original implementation, the netstack has had some error variants that were... strange. Some of them clearly indicate programming errors (like `NotYours`, which happens if you attempt to send through somebody else's socket), and others clearly indicate...well, nothing, because there was one called `Other`.
I tracked down what was generating these in practice and converted most of the cases to reply-fault, since they represented programmer errors that broke preconditions. I've cleaned up and commented the handling of the remaining error conditions in all clients.
> Make error types in the net API more precise

- .github/workflows/build-boards.yml
- drv/stm32xx-sys/Cargo.toml
- drv/stm32xx-sys/src/main.rs
- task/hiffy/src/tests.rs
- test/test-assist/src/main.rs
- test/test-idol-server/src/main.rs
- test/test-runner/src/main.rs
- test/test-suite/src/main.rs
- test/tests-psc/app.toml
- test/tests-stm32g0/app-g070.toml
Currently, Hubris' CI doesn't build the tests at all. This means that it's quite easy for the various test apps to bitrot --- for example, the PSC test app doesn't build, because [it maps IRQs by bit, rather than by name][1]. Named IRQ support was added back in 2022 (e.g. #424), so this TOML clearly hasn't been touched in...kind of a while, which I think is a pretty convincing argument for building these tests on CI!
[1]: https://github.com/oxidecomputer/hubris/blob/3325c6343a3e51a4d2c63cb3eac46085ba61dac3/test/tests-psc/app.toml#L68-L74
> ci: add test apps to `build-boards.yml`

- test/tests-stm32h7/Cargo.toml
- test/tests-stm32h7/src/main.rs
This uses the baseline clock configuration and does no I/O, like the original test suite did before I messed that up. This will now run on any h7 board and should eliminate the need for having per-board copies of the core-system tests. (Board-specific functionality tests, of course, need to be separate.)
> tests-stm32h7: make general to any h7 system.

- build/xtask/src/dist.rs
The kernel will reject leases that span multiple regions, so this PR disables smart packing entirely by forcing each task's flash into a single MPU region (just like before #1599).  Otherwise, tasks which loan out their flash memory may produce spurious faults.
> Disable smart packing

- drv/stm32xx-i2c-server/Cargo.toml
This unbreaks the donglet build for now, after disabling autopacking in #1671 made it too big.
> i2c_driver: disable panic messages on g031

- lib/host-sp-messages/src/lib.rs
- task/host-sp-comms/src/bsp/gimlet_bcde.rs
The host will eventually want fan tachometer data in its IPCC inventory; this PR adds MAX31790 sensor IDs to our `enum InventoryData` in preparation.
The new variant is added at the end to preserve existing serialization.
> Add MAX31790 to IPCC inventory

- Cargo.lock
- Cargo.toml
- drv/spi-api/build.rs
- drv/stm32h7-spi-server-core/Cargo.toml
- drv/stm32h7-spi-server-core/src/lib.rs
The `stm32xx-spi-server-core` ringbuf fills up pretty quickly when the system is busy, so it's hard to see the total number of SPI operations that may have occurred in the past. This branch adds counters to this ring buffer.
Note that this PR depends on an upstream `idol` change, oxidecomputer/idolatry#49, to allow us to derive the `Count` trait for the `SpiOperation` generated type. So, we should merge that first, and get this pointed back at oxidecomputer/idolatry@main.
For example (on my gimletlet):
```console
$ humility ringbuf spi_server_core
humility: attached via ST-Link V3
humility: ring buffer drv_stm32h7_spi_server_core::__RINGBUF in net:
TOTAL VARIANT
3374 WaitISR
3184 Tx
3184 Rx
590 Start(exchange)
206 Start(write)
6  467      117        2 …
```
> Add counters to `stm32xx-spi-server-core` ringbuf

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h753.toml
- app/lpc55xpresso/app.toml
- app/rot-carrier/app.toml
- sys/kern/Cargo.toml
- sys/kern/build.rs
- sys/kern/src/descs.rs
- sys/kern/src/task.rs
- sys/kern/src/umem.rs
- sys/kerncore/Cargo.toml
- sys/kerncore/README.mkdn
- sys/kerncore/src/lib.rs
Now that the build system has started packing tasks more cleverly, MPU region boundaries can appear in the middle of task RAM and Flash in positions that are difficult for the program to predict. This means the program can't safely lend any section of RAM or Flash without risking drawing the ire of the kernel, which --- owing to the limitations of earlier versions of the build system --- would not accept any access that spanned a region.
This fixes that. To make fixing that relatively inexpensive, this also sorts task region tables by base address, so we can do a linear scan with early exit.
See #1672 for more details and analysis.
> kern: permit USlices to span contiguous MPU regions

- build/xtask/src/config.rs
Our linker scripts all assume that things are aligned to at least 32-bit boundaries. Right now, if you configure an lpc55 target (at least) with a kernel flash size that isn't a multiple of 4, you get an obscure error from the linker late in the build process.
That's annoying because (1) it happens late, so iteration time is slow, and (2) linker errors are designed by space aliens to confuse humanity, or so I've inferred.
This adds an explicit check and early failure for the case.
> xtask: require kernel flash/RAM to be 0 mod 4

- Cargo.lock
- Cargo.toml
- drv/sidecar-front-io/src/controller.rs
- drv/sidecar-front-io/src/transceivers.rs
- drv/transceivers-api/src/lib.rs
- drv/transceivers-server/src/main.rs
- drv/transceivers-server/src/udp.rs
Currently the `transceivers` server will loop and await the Front IO board to be ready before entering is service loop. This means that in the case where the Front IO board is not present (or ready), `transceivers` server cannot handle any incoming requests, making the host software that is sending those requests unhappy. This change addresses that.
This is intended to address #1562
> Decouple `transceivers` server from Front IO readiness

- drv/spi-api/src/lib.rs
- idl/net.idol
- idl/spi.idol
- task/net-api/src/lib.rs
- task/net/src/main.rs
This fixes name collisions between `drv_spi_api::SpiError` and `gateway_messages::sp_to_mgs::SpiError`, and between `task_net_api::{SendError, RecvError}` and `smoltcp::{SendError, RecvError}` that confuses Humility, as in:
```
humility: WARNING: SpiError matches more than one enum: drv_spi_api::SpiError as GOFF 0x0000786b (object 4), gateway_messages::sp_to_mgs::SpiError as GOFF 0x00010532 (object 4)
humility: WARNING: SpiError matches more than one enum: drv_spi_api::SpiError as GOFF 0x0000786b (object 4), gateway_messages::sp_to_mgs::SpiError as GOFF 0x00010532 (object 4)
humility: WARNING: SpiError matches more than one enum: drv_spi_api::SpiError as GOFF 0x0000786b (object 4), gateway_messages::sp_to_mgs::SpiError as GOFF 0x00010532 (object 4)
humility: WARNING: SpiError matches more …
```
> fully qualify `SpiError`, `task_net_api::{SendError, RecvError}` types in Idol

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- build/stm32xx-sys/Cargo.toml
- build/stm32xx-sys/src/lib.rs
- drv/stm32xx-sys/Cargo.toml
- drv/stm32xx-sys/build.rs
- drv/stm32xx-sys/src/main.rs
- task/nucleo-user-button/Cargo.toml
- task/nucleo-user-button/build.rs
- task/nucleo-user-button/src/main.rs
This commit adds build-time code generation for the EXTI IRQ dispatch table. Now, an app.toml can define a section like this:
```toml
[config.sys.gpio-irq.button]
port = "C"
pin = 13
owner = { name = "mytask", notification = "button" }
```
To assign PC13's EXTI IRQ to the `button` notification for task `mytask`. The dispatch table is now generated by `build/stm32xx-sys` and will include the EXTI interrupt configurations in the config.
> stm32xx-sys: configure EXTI IRQs in app.toml

- app/demo-stm32g0-nucleo/app-g070.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/donglet/app-g031-i2c.toml
- app/donglet/app-g031.toml
- app/sidecar/base.toml
- build/xtask/src/dist.rs
- test/tests-stm32g0/app-g070.toml
Now that release 7 is closer to finalized and we've gained some confidence in the kernel fixes for #1672, it would be nice to regain the benefits of task packing and stop fretting so much about fragmentation.
> build: re-enable task packing.

- task/power/src/bsp/gimlet_bcdef.rs
This should help avoid the situation where someone unknowingly removes or modifies this in a way that breaks racktest.
> power: add comments to gimlet rail sag trace facility

- drv/stm32xx-sys/src/main.rs
- task/nucleo-user-button/src/main.rs
This branch contains two commits, both related to documentation for EXTI GPIO IRQs:
- 1d069b73346558111ade86cf30752a1d921c0ada fixes a wrong comment in the `nucleo-user-button` demo task
- 87c502721303a98b4811b5293db9030ff3c4003b adds example code for actually using EXTI IRQs to the `stm32xx-sys` crate
> EXTI IRQ docs improvements

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- drv/stm32xx-sys-api/Cargo.toml
- drv/stm32xx-sys-api/src/lib.rs
- drv/stm32xx-sys/src/main.rs
- idl/stm32xx-sys.idol
- task/nucleo-user-button/src/main.rs
The current `Sys::gpio_irq_configure` IPC interface is a bit confusing, as it takes two `bool`s for the rising and falling edge sensitivities, as in:
```rust
sys.gpio_irq_configure(mask, true, false);
```
This isn't particularly clear for a reader, who then has to remember the order of the arguments to determine which edge sensitivity is being enabled here. This is a case of ["boolean blindness"][1].
This commit improves the interface by changing it to take an `enum` with variants for `Rising`, `Falling`, and `Both`. Now, the same call to the IPC looks like this:
```rust
sys.gpio_irq_configure(mask, Edge::Rising);
```
which should be much more obvious to a reader, who no longer needs to remember the argument ordering to decypher calls to this function.
Also, this has the advantage of …
> stm32xx-sys: configure GPIO IRQ edge with an enum

- app/gimlet/base.toml
- app/gimletlet/app.toml
- app/psc/base.toml
- app/sidecar/base.toml
- task/sensor/build.rs
- task/sensor/src/main.rs
task/sensor was configuring a timer to wake it every 1 Hz. Each time it woke up, it would snooze its alarm clock and go back to sleep.
While I definitely sympathize with that desire, this is essentially dead code that looks like a bug, so this commit removes it. I'm not sure what the history here is.
In addition to removing noise from the code, this knocks 114 bytes off the sensor task text size.
> sensor: remove noop 1 Hz timer

- sys/userlib/Cargo.toml
- sys/userlib/src/lib.rs
When enabled, this will turn any panics in a task into linker errors. That's not ideal, but it's better than expecting people to manually read disassembly.
This currently has no users in the source tree, because it's factored out of some other work I'm doing. Wanted to make this available so we can start turning it on opportunistically.
> userlib: add no-panic feature

- drv/gimlet-seq-server/src/main.rs
- drv/lpc55-sha256/src/lib.rs
- drv/lpc55-spi-server/src/main.rs
- drv/lpc55-sprot-server/src/main.rs
- drv/lpc55-update-server/src/main.rs
- drv/psc-seq-server/src/main.rs
- drv/stm32h7-eth/src/lib.rs
- drv/stm32h7-hash/src/lib.rs
- drv/stm32h7-qspi/src/lib.rs
- drv/stm32h7-spi-server-core/src/lib.rs
- drv/stm32h7-update-server/src/main.rs
- drv/stm32xx-i2c-server/src/main.rs
- sys/kern/src/syscalls.rs
- sys/userlib/src/hl.rs
- sys/userlib/src/lib.rs
- task/gimlet-inspector/src/main.rs
- task/net/src/bsp/gimlet_bcdef.rs
- task/net/src/bsp/psc_a.rs
- task/net/src/bsp/psc_bc.rs
- task/nucleo-user-button/src/main.rs
- task/sp_measure/src/main.rs
- task/spd/src/main.rs
- task/uartecho/src/main.rs
- task/udpecho/src/main.rs
- task/udprpc/src/main.rs
- test/test-suite/src/main.rs
This is an alternate API for accessing the common "receive only kernel
notifications" pattern. That specific use of the sys_recv syscall is
defined as not being able to fail. Different users have handled that in
different ways -- some panic, some ignore the result. The latter embeds
the assumption of that behavior in many different places in the
codebase, a pattern I'm trying to keep an eye on.
This change adds a new sys_recv_notification userlib function that
bundles up this common pattern. Because of its central placement in
userlib, it seems like a more appropriate place to encode the assumption
about the syscall not failing, and so I've done that, using
unreachable_unchecked to explain it to the compiler.
This removes a panic site from every notification-wait in programs that
were …
> Convenient no-panic API for just waiting on notifications

- drv/stm32xx-sys/src/main.rs
In the Giant Scary Nested Match we had to write to be able to address the EXTI register array as an array through the PAC, I typo'd the number base being used to select the field within the register, by reusing 2 from the line above. This is the _base 2 logarithm_ of the number we actually wanted, 4, because the operations are shift and mod, respectively.
Wheeee
Anyway, this fixes the situation where EXTI configuration of any pin p such that p % 4 = 2 or 3 on any port other than A mysteriously senses a different pin in port A instead.
> stm32xx-sys: fix typo in EXTI pin configuration

- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- drv/stm32xx-sys-api/src/lib.rs
- drv/stm32xx-sys/src/main.rs
- idl/stm32xx-sys.idol
- task/nucleo-user-button/src/main.rs
Currently, there is no mechanism for a task woken by a notification
mapped to an EXTI GPIO interrupt to determine whether the pin it cares
about has actually changed state, rather than receiving a notification
posted by some other task (see #1700). In order to make this possible,
@cbiffle [suggested] that the `stm32xx-sys` task provide an IPC
interface that a task receiving an EXTI notification can call to ack
that the IPC actually was caused by a pin state transition.
This branch extends the `Sys::gpio_irq_control` IPC to return a bool if
any EXTI IRQs mapped to the notifications in a task's notification
maskhave triggered since the last time `gpio_irq_control` was called.
Adding this functionality to `gpio_irq_control` --- which a task that
wishes to receive another EXTI notification …
> stm32xx-sys: add interrupt acking to `gpio_irq_control`

- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
- task/control-plane-agent/src/update/host_flash.rs
- task/control-plane-agent/src/update/mod.rs
- task/control-plane-agent/src/update/rot.rs
- task/control-plane-agent/src/update/sp.rs
This change causes SpUpdate to impl ComponentUpdater, instead of sporting functions that look a lot _like_ ComponentUpdater but aren't actually. This fixes a warning in the newest toolchain, which was concerned that operations in the non-public trait were going unused (which they were!).
In order to adapt ComponentUpdater to be able to describe all three cases, I have added two associated types to it. UpdatePrepare parameterizes the difference between RoT/HostFlash updates (which want ComponentUpdatePrepare) and SP updates (which want a different SpUpdatePrepare type). SubComponent models the fact that only the SP seems to want a specifier for sub-components inside itself; the others set this to ().
> control-plane-agent: finish ComponentUpdater

- Cargo.lock
- build/stm32xx-sys/src/lib.rs
- build/util/src/lib.rs
- drv/stm32h7-sprot-server/src/main.rs
- drv/stm32xx-sys-api/Cargo.toml
- drv/stm32xx-sys-api/build.rs
- drv/stm32xx-sys-api/src/lib.rs
- task/nucleo-user-button/src/main.rs
Currently, pins used for EXTI IRQs are defined in the `sys` task's config in `app.toml`. When a task wishes to actually use those pins, though, it must _also_ define them separately in order to call `sys.gpio_configure_input` (and if it wants to perform its own GPIO reads on that pin). This is generally done either by hard-coding the port and pin number in the task's source code, or by defining its own config for configuring which pin to use.
This is unfortunate, as it results in a duplicated pin definition, either between the source code and the config if hard-coded, or twice in the config, if the task also gets the definition from config. And, if the task configures the pin in its own config, the author of that task must re-implement the config handling.
This commit fixes this by adding …
> stm32xx-sys: generate constants for EXTI pins

- app/psc/base.toml
- drv/stm32h7-sprot-server/src/main.rs
This branch fixes a pair of regressions I introduced in PR #1696 : 
- **sprot: fix backwards ROT_IRQ edge detection** (8be5f3c24b70bc4e71f8428c2552b8b90299e46d)
In PR #1696, I broke the `drv-stm32h7-sprot-server` code for waiting for
`ROT_IRQ` to change state. The `ROT_IRQ` signal is active low (and in
the schematic it's called `ROT_TO_SP_IRQ_L`), but in the code, the pin
is just referred to as `ROT_IRQ`, so I configured edge sensitivity
backwards, meaning we missed the IRQ signal. Oops, my bad.
This commit changes the edge sensitivity to wait for the falling edge
when waiting for `ROT_IRQ` to be asserted, and to wait for the rising
edge when waiting for it to be deasserted, instead of the other way
around. Now, it actually works correctly.
```console
eliza@lurch ~ $ pfexec humility -t …
```
> fix ROT_IRQ regressions from #1696

- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
It would be convenient for https://github.com/oxidecomputer/hubris/pull/1707 if `MgsCommon` could check update state, so this PR moves the `SpUpdate` and `RotUpdate` members into `MgsCommon`.
> Move sp_update and rot_update to MgsCommon

- task/thermal-api/src/lib.rs
- task/thermal/src/bsp/gimlet_bcdef.rs
- task/thermal/src/bsp/sidecar_bcd.rs
- task/thermal/src/main.rs
Currently, the `thermal` task uses `unwrap()` in a bunch of places,
requiring it to derive `Debug` for a bunch of stuff. This commit changes
those to `unwrap_lite()`, and removes many of the derived `Debug` impls.
On `gimlet-f`, this shaves off about 1K of flash:
before:
```
thermal              flash   23316  23328  32768
ram     7820   8192   8192
```
after:
```
thermal              flash   22392  22400  32768
ram     7820   8192   8192
```
It would be nice to also remove the derived `Debug` from types like
`SensorId`, but it looks like that's currently used by `validate_api`
--- I wasn't sure if any of the `validate_api` types are used in
control-plane comms, so I didn't touch that yet. May do so in a
follow-up.
> thermal: remove panic formatting and `Debug` impls

- lib/dice/src/cert.rs
These traits are newly detected as dead by the new toolchain, so after discussion with @flihp I'm removing them -- we can always get them out of git if we need them.
> lib/dice: remove dead traits

- app/gimlet/base.toml
- build/i2c/src/lib.rs
- drv/gimlet-seq-server/src/main.rs
- drv/gimlet-seq-server/src/vcore.rs
- drv/i2c-devices/src/lib.rs
- drv/i2c-devices/src/raa229618.rs
Draft commit comment:
```
In our ongoing attempts to characterize sags in the V12_SYS_A2 rail,
we enlist one of the RAA229618 VRs to record observed READ_VIN values
whenever the rail drops below 11.75V.
```
Example output:
```
0   99        1        1 Initializing
1  103        1        1 LimitLoaded
2  107        1        1 FaultsCleared
3  116        1        1 Initialized
4  124        1        1 Notified
5  127        1        1 Fault
6  144        1        1 Reading { timestamp: 0x271cb, volts: Volts(11.680001) }
7  144        1        1 Reading { timestamp: 0x271cc, volts: Volts(11.610001) }
8  144        1        1 Reading { timestamp: 0x271cd, volts: Volts(11.500001) }
9  144        1        1 Reading { timestamp: 0x271ce, volts: Volts(11.440001) …
```
> add RAA229618 VIN monitoring

- .github/workflows/build-one.yml
- build/stm32xx-sys/src/lib.rs
- drv/gimlet-hf-server/src/main.rs
- drv/i2c-devices/src/pca9956b.rs
- drv/lpc55-sprot-server/src/handler.rs
- drv/lpc55-update-server/src/main.rs
- drv/sidecar-seq-server/src/front_io.rs
- drv/sidecar-seq-server/src/main.rs
- drv/stm32h7-eth/src/ring.rs
- lib/dice/src/mfg.rs
- lib/lpc55-rot-startup/src/images.rs
- lib/update-buffer/src/lib.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_gimlet/host_phase2.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/hiffy/src/generic.rs
- task/hiffy/src/lpc55.rs
- task/hiffy/src/main.rs
- task/hiffy/src/stm32g0.rs
- task/host-sp-comms/src/main.rs
- task/monorail-server/src/server.rs
- task/net/src/server.rs
- test/test-suite/src/main.rs
This fixes everything but Hiffy's use of unsafe (or anything anybody has added since I started on this branch).
This change turns Clippy back on to prevent regressions.
> Fix almost all remaining warnings from the toolchain update.

- sys/kerncore/src/lib.rs
The recent Oxide and Friends episode mentioned this memory region spanning slices issue, and the code was interesting. I thought I saw a chance to optimise it by omitting the start address containment checking once the start region is found. (Based on benchmarking against the test impls, it isn't faster.) The obvious issue with that was of course validity of the intermediate regions but I realised that wouldn't be a problem since I still need to check the validity of each region between start and end.
I figured I'd write tests to show that the alternative solution works but then realised the actual issue: My "optimised" algorithm allows for uncontained (unmapped?) memory to be accessed as long as it is found between two good regions. I presume this makes my improvement worthless, but at …
> kerncore: Add tests for bad or uncontained memory contained in a contiguous slice

- app/lpc55xpresso/app-sprot.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
- build/lpc55pins/src/lib.rs
This means that invalid pin configuration parameters will fail to parse, instead of making it through codegen and then failing at (Hubris) compile time.
I don't love leaning on the derived `Debug` here:
```rust
let mode = format_ident!("{}", format!("{:?}", self.get_mode()));
let slew = format_ident!("{}", format!("{:?}", self.get_slew()));
let invert = format_ident!("{}", format!("{:?}", self.get_invert()));
let digimode = format_ident!("{}", format!("{:?}", self.get_digimode()));
let od = format_ident!("{}", format!("{:?}", self.get_opendrain()));
tokens.append_all(final_pin);
tokens.append_all(quote::quote! {
AltFn::#alt_num,
Mode::#mode,
Slew::#slew,
Invert::#invert,
Digimode::#digimode,
Opendrain::#od,
});
```
but my other experiments were all worse; I'm open to suggestions for how …
> Add enums for LPC55 pin codegen

- app/gimlet/base.toml
I'm seeing stack overflow for `gimlet-seq` on the `gimlet-c-dev` image.  Running with a boosted stack size, I see a `stackmargin` size of 1728, which is above the limit of 1600.  Bisecting, this appears to have been introduced in #1730; I'm guessing it's the nested `ServerImpl::handle_notifications → VCore::handle_notifications` dispatch.
> Bump gimlet-seq stacksize

- Cargo.lock
- Cargo.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/rot-carrier/app.toml
- build/lpc55pins/src/lib.rs
- drv/lpc55-sprot-server/Cargo.toml
- drv/lpc55-sprot-server/src/handler.rs
- drv/lpc55-sprot-server/src/main.rs
- drv/lpc55-swd/build.rs
- drv/lpc55-swd/src/main.rs
- drv/sprot-api/src/error.rs
- drv/sprot-api/src/lib.rs
- drv/stm32h7-sprot-server/src/main.rs
- idl/sp-ctrl.idol
- idl/sprot.idol
- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/mgs_gimlet.rs
- task/control-plane-agent/src/mgs_psc.rs
- task/control-plane-agent/src/mgs_sidecar.rs
An SP update has one fundamental requirement: it has to allow for future updates.
This is not guaranteed: a sufficiently broken SP image could fail to bring up `net` or `control-plane-agent`, which would require physical intervention to reflash (not ideal in a rack!).
In https://github.com/oxidecomputer/hubris/issues/1695, we discuss a strategy for automatically rolling back updates, using the RoT as a watchdog.  This PR adds the tools to implement that strategy:
- New SP-RoT messages to enable and disable a "reset into alternate slot" watchdog timer
- RoT implementation of that watchdog
- MGS plumbing (along with https://github.com/oxidecomputer/management-gateway-service/pull/216) to accept these commands over the network
> SP reset watchdog

- drv/gimlet-seq-server/src/main.rs
- drv/lpc55-swd/src/main.rs
- drv/meanwell/src/main.rs
- drv/sidecar-seq-server/src/main.rs
- drv/stm32h7-sprot-server/src/main.rs
- drv/user-leds/src/main.rs
- lib/multitimer/src/lib.rs
- sys/userlib/src/hl.rs
- sys/userlib/src/lib.rs
- task/control-plane-agent/src/mgs_gimlet/host_phase2.rs
- task/host-sp-comms/src/main.rs
- task/jefe/src/main.rs
- task/monorail-server/src/bsp/sidecar_bcd.rs
- task/monorail-server/src/server.rs
- task/power/src/main.rs
- task/thermal/src/main.rs
See the commits for more detail, but in brief, this removes a panic from `userlib::hl::sleep_for` and then introduces a `set_timer_relative` operation for doing the common timer set operation in a way that won't panic.
> Remove most panics from timer-related operations

- Cargo.toml
- lib/multitimer/Cargo.toml
- lib/multitimer/src/lib.rs
- sys/abi/Cargo.toml
- sys/kern/Cargo.toml
- sys/kern/src/startup.rs
- sys/kerncore/Cargo.toml
- sys/num-tasks/Cargo.toml
- sys/userlib/Cargo.toml
- task/jefe/Cargo.toml
- task/jefe/src/dump.rs
- task/jefe/src/external.rs
- task/jefe/src/main.rs
- test/test-api/Cargo.toml
- test/test-api/src/lib.rs
- test/test-assist/Cargo.toml
- test/test-assist/src/main.rs
- test/test-idol-api/Cargo.toml
- test/test-idol-api/src/lib.rs
- test/test-idol-server/Cargo.toml
- test/test-idol-server/src/main.rs
- test/test-runner/Cargo.toml
- test/test-runner/src/main.rs
- test/test-suite/Cargo.toml
- test/test-suite/src/main.rs
This starts with the "core" code in sys, test, and jefe, and works out from there.
Any package can opt into this at any time by adding this to its Cargo.toml:
[lints]
workspace = true
This will also cause it to pick up any future lints we decide on.
> Begin removing/disabling wildcard imports.

- doc/syscalls.adoc
- sys/abi/src/lib.rs
- sys/kern/src/task.rs
- sys/userlib/src/lib.rs
Previously, a closed RECV against the kernel was special-cased as a "listen only for notifications" operation. Closed RECV against any other task would ignore the provided notification mask and treat it as zero.
This seemed weird and limiting.
This commit alters the semantics of RECV with a non-zero notification mask and enables notifications in that specific situation.
As far as I can tell, we have no code that relies on notifications being filtered out during closed-RECV, so this should be safe.
Fixes #1761.
> Enable notifications on any closed RECV.

- drv/sidecar-mainboard-controller/src/tofino2.rs
- drv/sidecar-seq-server/src/main.rs
We noticed on the dogfood rack that a Sidecar's 10G link was persistently down.
Normally, this is fixed by a watchdog.  However, the watchdog only fires if the PCIe link is active (https://github.com/oxidecomputer/hubris/pull/1510).
The PCIe link was falsely being reported as down because the debug port state (`TOFINO_DEBUG_PORT_STATE`) had `receive_buffer_empty = false`, so we bailed out of the check at [this condition](https://github.com/oxidecomputer/hubris/blob/020d014880382d872d048fbfe1e8152a39e7c47a/drv/sidecar-mainboard-controller/src/tofino2.rs#L662).  This failure was persistent through SP reboots (which notably do not reflash the FPGA), so it's likely out-of-sync state between the FPGA and SP.
This PR adds a startup step to reset the debug port tx/rx buffers by writing to the …
> Reset debug port on startup

- Cargo.lock
- build/fpga-regmap/Cargo.toml
- build/fpga-regmap/src/lib.rs
- drv/gimlet-seq-server/src/main.rs
- drv/sidecar-front-io/src/transceivers.rs
- drv/transceivers-server/src/main.rs
- drv/transceivers-server/src/udp.rs
I'll start off with a bit of context since this is a corner of the system that doesn't get looked at often. We use SystemRDL to define registers in the FPGA. When we build an FPGA, one of the outputs is a JSON file that describes the registers. We commit that JSON file alongside the bitfile in this repo, which then gets turned into Rust by `build/fpga-regmap`. A neat part of this is that we can define enums as a register field in the RTL and carry them into the Rust code via a property we call `encode`.
For example, consider the [`STATUS_PORT0` register](https://github.com/oxidecomputer/hubris/blob/master/drv/sidecar-front-io/sidecar_qsfp_x32_controller_regs.json#L1154-L1213). Today, that would generate the following code:
```rust
...
#[allow(non_snake_case)]
pub mod STATUS_PORT0 { …
```
> Make enum encoded FPGA register fields more flexible

- build/xtask/src/config.rs
... I think this got stabilized? A quick grep of the code doesn't show invoking the flag. Let's see what CI says, I probably missed something.
> Removed named-profiles feature flag

- Cargo.lock
- app/psc/base.toml
- drv/psc-seq-server/Cargo.toml
- drv/psc-seq-server/build.rs
- drv/psc-seq-server/src/main.rs
This adds very basic monitoring of the presence and power-good lines from the PSUs at the PSC. It can manage remove/insertion of power supplies, delay restarts to ensure we don't cycle things too quickly, and respond to faults by resetting things. So far data is only logged to a ringbuf.
> PSC monitoring MVP

- build/xtask/src/lsp.rs
If a HUBRIS_APP environment variable is defined and points to an app.toml file, cargo xtask lsp will assume this is the app you'd like to use for build context.
> xtask lsp: optionally source app.toml from HUBRIS_APP

- app/oxcon2023g0/app.toml
The IPC counters made this too RAM hungry; opted out of them.
> oxcon2023g0: fix the build

- app/gimlet/base.toml
The compiler bump in https://github.com/oxidecomputer/hubris/pull/1703 left us with a mere 24 bytes of `stackmargin` on `host-sp-comms` (down from about 1 KiB).  This manifests as sporadic stack overflows, basically if we hit an interrupt at exactly the wrong time.
Cores are collected in `/staff/dogfood/cores-collected-20240507`.  All of the per-task cores show the same issue:
```
matt@cadbury /staff/dogfood/cores-collected-20240507 () $ for f in $(find . -name "hubris.core.host_sp_comms*"); do printf "\n$f\n"; h --dump $f tasks; done
./BRM42220009/hubris.core.host_sp_comms.0
humility: attached to dump
system time = 87005911
ID TASK                       GEN PRI STATE
16 host_sp_comms                0   7 FAULT: stack overflow; sp=0x2401fff0 (was: ready) …
```
> Bump `host-sp-comms` stacksize

- Cargo.lock
Between 46fec5217 (inclusive) and this commit (exclusive) we haven't generated DWARF info for the Idol ARGS struct in the specific case of a zero-argument function using non-zerocopy encoding. Humility 0.11.6 has been fixed to tolerate this, but in the interest of broader compatibility, we've also patched Idol to try and bring the debug info back.
This pulls in the Idol fix.
Fixes #1777
> Bump Idol to get foo_ARGS struct fix.

- build/fpga-regmap/src/lib.rs
- drv/sidecar-front-io/src/transceivers.rs
- drv/transceivers-server/src/main.rs
- drv/transceivers-server/src/udp.rs
#1768 did not properly account for the FIFO behavior of the FPGA's data buffers. The "check the status byte" portion of the loop happened outside the part where we read the buffer, and since the buffer was just memory-mapped registers it could be repeatedly without consequence. Since the data was now in a FIFO, I was inadvertently draining the FIFO before the transaction was done. This PR consolidates the "is I2C done yet" logic into the `get_i2c_status_and_read_buffer` so calling code can just deal with the status register and the data buffer.
Fixes #1786
> transceivers: fix I2C read bug

- drv/psc-seq-server/src/main.rs
We're currently in a situation where the dogfood rack has the power whip feeding PSUs 3-5 disconnected. This means the PSUs are sitting there in faulted state refusing to enable. Since we can't distinguish this from actual PSU failures, currently we're frantically chatting about this situation in the logs. This is annoying, and overwrites other data.
This change alters the behavior to note a sticky fault condition _once_ and then quietly keep trying to resolve it without the spam.
> psc-seq: don't repeat StickyFault every time.

- task/thermal-api/src/lib.rs
- task/thermal/src/bsp/gimlet_bcdef.rs
- task/thermal/src/bsp/sidecar_bcd.rs
- task/thermal/src/control.rs
- task/thermal/src/main.rs
Currently, the `thermal` task tries to initialize the MAX31790 fan
controller(s) once when the task starts, and `unwrap_lite`s the result.
This means that in the face of a transient I2C error, the whole task
panics and gets restarted. This is unfortunate: sometimes, the bus is
briefly locked or arbitration is lost or something, and then everything
is fine. Furthermore, if we can't talk to the MAX31790, its watchdog
will trip and it'll just run the fans at 100%...and would probably
prefer to just let the `thermal` task keep running and publishing sensor
readings, rather than crashlooping.
This commit changes the `thermal` task to track whether it has
initialized the MAX31790(s), and if it hasn't yet, any operation which
will attempt to talk to the MAX31790(s) will first try to initialize …
> thermal: don't panic if MAX31790 init fails

- drv/stm32h7-update-api/src/lib.rs
- drv/stm32h7-update-server/src/main.rs
- idl/stm32h7-update.idol
- task/control-plane-agent/src/mgs_common.rs
- task/control-plane-agent/src/update/sp.rs
It's useful for the SP to be able to change the active slot. Pull this through. The final finish step no longer implicitly swaps the bank.
> Allow SP to set active slot

- drv/stm32h7-sprot-server/src/main.rs
Setting the stage0 boot component involves writing to flash which requires a longer timeout
> Add a long timeout for setting boot component

- drv/auxflash-server/src/main.rs
This is a legacy pin from the original Gemini Bringup Board, and isn't actually connected on Sidecar (PF5 is `V1P8_PG_A2`, which we're presumably fighting against)
> Remove unconnected QSPI reset line

- Cargo.lock
- build/stm32xx-sys/src/lib.rs
- drv/gimlet-seq-server/Cargo.toml
- drv/gimlet-seq-server/build.rs
- drv/gimlet-seq-server/src/main.rs
- drv/gimlet-seq-server/src/vcore.rs
- drv/stm32h7-sprot-server/Cargo.toml
- drv/stm32h7-sprot-server/build.rs
- drv/stm32h7-sprot-server/src/main.rs
- drv/stm32xx-sys-api/Cargo.toml
- drv/stm32xx-sys-api/build.rs
- drv/stm32xx-sys-api/src/lib.rs
- task/nucleo-user-button/Cargo.toml
- task/nucleo-user-button/build.rs
- task/nucleo-user-button/src/main.rs
Using GPIO interrupts (EXTI) on STM32xx devices involves code generation based on the pins mapped to EXTI interrupts in the app config. Currently, this code generation is done when building the `drv-stm32xx-sys-api` crate. Unfortunately, this codegen depends on `task_name` to determine which task's GPIO pin IRQs to build the generated code for, which results in `drv-stm32xx-sys-api` being recompiled for each task in an image when it would not otherwise be necessary to do so. This is a shame, as it results in substantially longer builds; see #1828 for details.
There isn't *really* any reason that this code needs to be generated in the `drv-stm32xx-sys-api` crate rather than in the `build.rs` files for the tasks that actually use GPIO interrupts. The only reason for doing it this way is "I …
> stm32xx-sys: move GPIO IRQ codegen to tasks

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/grapefruit/app.toml
- drv/stm32h7-fmc-demo-server/Cargo.toml
- drv/stm32h7-fmc-demo-server/README.md
- drv/stm32h7-fmc-demo-server/src/main.rs
This adds a UDP interface for messing with Grapefruit's FPGA. The protocol is documented in `drv/stm32h7-fmc-demo-server/README.md`.
> grapefruit: add fmc-demo IP interface

- lib/host-sp-messages/src/lib.rs
- task/host-sp-comms/src/main.rs
Running with this fix:
```console
$ humility ringbuf host_sp_comms | grep BootFail
humility: attached via ST-Link V3
1 Request(HostBootFailure)
15  712        1        1 Request { now: 0x173bd, sequence: 0x5, message: HostBootFailure { reason: 0x2 } }
$ humility host boot-fail
humility: attached via ST-Link V3
Message is 46 bytes long:
Could not find a valid phase2 image on disk:17
$ humility host last-panic
humility: attached via ST-Link V3
version:   1 (determined)
cause:     IPCC_PANIC_CALL
error:     0
cpuid:     0
thread:    0xfffffffffbe9f1e0
addr:      0x0
pc:        0xfffffffff7cafffa
fp:        0xfffffffffbea5060
rp:        0x0
message:   Could not find a valid phase2 image on disk:17
stack:
oxide_boot_locate+0x18a                          (0xfffffffff7cafffa) …
```
> `HostPanic` and `HostBootFailure` discard bytes

- task/net/src/main.rs
- task/net/src/server.rs
This avoids a potential liveness issue described in #1844, wherein a task waiting for tx queue space would not notice net restarting.
Fixes #1844.
> net: wake all sockets on restart.

- .github/workflows/dist.yml
- .github/workflows/test.yml
We were previously maintaining `grapefruit-bringup` as a long-running branch, but have since merged it into `master`.
> Remove grapefruit branch from CI

- drv/auxflash-api/src/lib.rs
- drv/auxflash-server/src/main.rs
- drv/eeprom/src/main.rs
- drv/fpga-api/src/lib.rs
- drv/fpga-devices/src/ecp5.rs
- drv/fpga-server/src/main.rs
- drv/gimlet-hf-api/src/lib.rs
- drv/gimlet-hf-server/src/main.rs
- drv/gimlet-seq-api/src/lib.rs
- drv/gimlet-seq-server/src/main.rs
- drv/gimlet-seq-server/src/vcore.rs
- drv/hash-api/src/lib.rs
- drv/i2c-api/src/lib.rs
- drv/i2c-devices/src/emc2305.rs
- drv/i2c-devices/src/ltc4282.rs
- drv/i2c-devices/src/max31790.rs
- drv/i2c-devices/src/max5970.rs
- drv/i2c-devices/src/pca9538.rs
- drv/ignition-server/src/main.rs
- drv/lpc55-gpio/src/main.rs
- drv/lpc55-i2c/src/main.rs
- drv/lpc55-rng/src/main.rs
- drv/lpc55-spi-server/src/main.rs
- drv/lpc55-swd/src/main.rs
- drv/lpc55-syscon/src/main.rs
Didn't quite have the time to get rid of all of these, but I removed a bunch of userlib namespace imports.
These were mentioned in a PR nearly half a year ago and I "helpfully" went through and pointed out those that were in the PR, so this is my atonement.
Each task is done in a separate commit here. All others except `drv-lpc55-spi-server` is tested to cause no build errors, or I think anyway. I'm randomly building tasks based on searches into the repository with the device name, and testing that they fail if I remove the `userlib::*` import entirely, and then add imports until build works.
> chore: Cleanup userlib namespace imports

- drv/lpc55-sprot-server/src/handler.rs
- drv/sprot-api/src/error.rs
- drv/sprot-api/src/lib.rs
- drv/stm32h7-sprot-server/src/main.rs
- idl/sprot.idol
We want to make policy decisions based on whether a system is in development or release mode.  For example, development machines may have more lax policy on tech port unlocking; see [RFD 492](https://rfd.shared.oxide.computer/rfd/506) and [506](https://rfd.shared.oxide.computer/rfd/506)
This PR adds a `SpRot` message and Idol function to perform a "development or release" check.  The policy decision is made on the RoT, which returns either `Development` or `Release`.
--------------------------------------------------------------------------------
The RoT uses two pieces of information to make this policy decision.
First, it checks which keys are active in the Root of Trust's CFPA region, which has four slots:
- Release is `[valid, valid, invalid, invalid]`
- Development is `[revoked, …
> Add APIs to check if the RoT is dev or release

- lib/ringbuf/src/lib.rs
- lib/static-cell/src/lib.rs
> The ~~Hitchhiker's Guide to the Galaxy~~ ringbuf has already
> supplanted ~~the great Encyclopaedia Galactica~~ text-based logging as
> the standard repository of all knowledge and wisdom, for though it has
> many omissions, it scores over the older, more pedestrian work in two
> important respects. First, it is slightly cheaper; and secondly it has
> the words **DON'T PANIC** inscribed in large friendly letters on its
> cover.
We have support in `userlib` for statically disabling all panics at
compile-time. When a task enables the `no-panic` feature flag on
`userlib`, any panic in that task will result in a link error. This
allows us to guarantee that some tasks will never panic, and we get a
nice code size reduction from doing so. However, the `ringbuf` crate
currently cannot be used …
> ringbuf: Eliminate potential panics

- drv/cosmo-hf/src/hf.rs
- drv/cosmo-hf/src/main.rs
- drv/hf-api/src/lib.rs
Staged on top of #1851
This PR splits the FMC NOR flash into `FlashDriver` (talking to the FPGA and flash) and `ServerImpl` (implementing the `HostFlash` API).  In addition, it adds a non-panicking failure path.  In this new failure path, there's a small Idol server which replies with an error to any message.
> Split `ServerImpl` versus `FlashDriver`, add `FailServer`

- Cargo.lock
- app/grapefruit/app.toml
- drv/cosmo-hf/src/hf.rs
- drv/cosmo-hf/src/main.rs
- drv/gimlet-hf-server/Cargo.toml
- drv/gimlet-hf-server/src/main.rs
- drv/hf-api/Cargo.toml
- drv/hf-api/src/lib.rs
Staged on top of #1853
This PR implement persistent storage in host flash for Cosmo, using the same strategy as Gimlet: reserve sector 0 and tile it with a small data payload, using a CRC to ensure validity and a monotonic counter to find the newest payload.
This only works because the AMD boot sequence ignores sector 0 (other than word 0, which must be all 1s).
`RawPersistentData` is moved to `drv-hf-api` and renamed `HfRawPersistentData` for consistency.  In addition, it now implements `cmp`, making a few operations cleaner.
The new code in `drv-cosmo-hf` is _mostly_ copypasta from `drv-gimlet-hf`, but with a few tweaks (both virtual devices are on the same flash chip, the QSPI driver has a slightly different API, etc).
> Implement persistent data for Cosmo `hf` slot selection

- build/xtask/src/config.rs
This *may* need to go in "nightly features that our dependencies use", as it doesn't appear in our code. Let's try that out!
> Remove array_methods flag

- Cargo.lock
- build/xtask/src/config.rs
- drv/stm32h7-fmc-demo-server/Cargo.toml
- drv/stm32h7-fmc-demo-server/src/main.rs
- lib/toml-task/src/lib.rs
- task/idle/Cargo.toml
tasks & kernels that want to disable default features can do so using the `no-default-features` boolean in the task / kernel config sections of the relevant `app.toml` files.
this resolves #1829
> xtask: Allow tasks & the kernel to specify default features.

- lib/lpc55-rot-startup/src/dice.rs
- lib/lpc55-rot-startup/src/lib.rs
Include the Hubris measurement in DICE even though it is done in Hubris pre-main.
> Include the Hubris measurement in DICE

- app/sidecar/base.toml
We have Sidecar's fans wired up to the controllers in a non-intuitive way. That leads to a couple places we need to have this accounted for properly in the code: speed sensor naming and controller mapping. The speed sensor naming was incorrect and fixed by this commit.
fixes #1865
> Fix Sidecar fan speed sensor ordering in base.toml

- app/gimlet/rev-b.toml
- app/gimlet/rev-c.toml
- app/gimlet/rev-d.toml
- app/gimlet/rev-e.toml
- app/gimlet/rev-f.toml
- app/oxide-rot-1/app.toml
- app/psc/rev-b.toml
- app/psc/rev-c.toml
- app/sidecar/rev-b.toml
- app/sidecar/rev-c.toml
- app/sidecar/rev-d.toml
We currently have an implicit assumption that our production images have the same name as the board. It's useful to take advantage of this in places like the control plane so document this for our future selves.
> Add comments explaining production assumption

- drv/hf-api/src/lib.rs
hf-api includes a function that computes a CRC32 of a chunk of data. Unfortunately, it made the (easy, common) mistake of allocating a crc::Crc on the stack.
The upstream crc crate, despite our protests, optimizes for time over space. A crc::Crc includes a lookup table to accelerate the calculation of the CRC. Creating one at runtime on the stack means
1. The lookup table is on your stack (all 2048 bytes of it, in this case), and
2. Your function now contains code to generate the lookup table.
This is a footgun in the crc API design, IMO. It's far too easy to make this mistake.
Anyway, made it static for a 2 kiB improvement in stack margin.
> hf-api: knock 2 kiB off stack usage

- .github/workflows/build-boards.yml
- .github/workflows/build-one.yml
- test/tests-stm32fx/app-f3.toml
The newer version is stricter about unique upload names which currently conflicts for the tests
> Move to actions/upload-artifact@v4

- task/thermal/src/bsp/gimlet_bcdef.rs
- task/thermal/src/bsp/grapefruit.rs
- task/thermal/src/bsp/medusa_a.rs
- task/thermal/src/bsp/sidecar_bcd.rs
- task/thermal/src/control.rs
The EMC2305 on Grapefruit doesn't turn on the fans at 0 PWM, and we want some airflow to get better readings from the temperature sensor.  Might as well make the lower and upper bounds fully parameterized by the PID config!
> Add min and max output bounds to `PidConfig`

- app/gimlet/base.toml
- app/psc/base.toml
- app/sidecar/base.toml
We found a crash where the stack size was 3980. This was awfully close to 4096. 12000 is definitely a large bound but it is a safe bound.
> Bump stack size on control-plane-agent

- build/xtask/src/dist.rs
on Rust nightlies [since about 2023-03-09](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-168-2023-03-09) it seems the default (-on-nightly?) Cargo protocol switched to "sparse". this has a side effect of caching fetched crates at a different path, so the `github.com` path remapping is no longer sufficient to normalize all crate paths.
we then picked that change up back at v1.0.14, bumping [nightly forward a year and change](https://github.com/oxidecomputer/hubris/commit/24bdff63d662053c097d6f84566bfae3ef772edd#diff-2b1bde2cf3a858b7bf7424cb8bcbf01f35b94dc80b925d9432cbab3319ca9b4e), so local builds of hubris between then and v1.0.26 have source paths that are not actually remapped :(
thankfully, to make it sufficient we only have to handle the new …
> remap crates fetched via sparse registry as well

- .github/workflows/build-boards.yml
- app/oxide-rot-1/app-dev.toml
- build/xtask/src/dist.rs
`oxide-rot-1/app.toml` expects to be run on a machine that has been through the full manufacturing flow. If it is run on one that hasn't had that happen it will fail to boot (loop forever). This is mostly a concern for engineering development but it keeps tripping people up so attempt to differentiate the correct image to use by changing the board. It's not strictly incompatible but going from one to another kind is a sort of cheap and relatively easy to rework.
> Make `oxide-rot-1-dev` a completely different board

- drv/cosmo-hf/src/hf.rs
- drv/cosmo-hf/src/main.rs
- Implements (virtual) mux control for `cosmo-hf`
- Adds checks on reads and writes that the flash is muxed to the SP
- Moves some magic numbers into named constants in the `regs` module
> Add cosmo hf mux control; minor cleanup

- build/xtask/src/flash.rs
This got missed when the board name was changed
> Add `oxide-rot-1-selfsigned` to flashing code

- build/xtask/src/dist.rs
This file contains local paths which reduces reproducibility. The local paths also mean it's not useful in the archive anyway.
> Drop gdb file from the archive

- Cargo.lock
- Cargo.toml
- drv/sprot-api/src/error.rs
- task/host-sp-comms/src/main.rs
Change the name `SprotError` in `attest-data` to avoid conflicts with the hubris `SprotError`. Rust handles this just fine but our external hiffy tooling does not handle this case.
> Avoid name conflict

- Cargo.lock
- Cargo.toml
- build/xtask/src/dist.rs
Minor change related to paths for bart signing.
Tested on rot-carrier.
> Bump hubtools version to 0.4.6

- Cargo.lock
- Cargo.toml
- app/demo-stm32g0-nucleo/app-g070.toml
- app/gimlet/base.toml
- app/gimletlet/app.toml
- build/xtask/Cargo.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- build/xtask/src/sizes.rs
(details to come, but opening as a draft to see if any of the CI-checked builds fail)
> Fail to build if tasks may overflow

- build/xtask/src/lsp.rs
Setting HUBRIS_TASK causes xtask lsp to only search tasks of a specific name, across configured apps (either the default set, or the one chosen by HUBRIS_APP).
This can be useful to get the cfgs right for a specific case.
> xtask lsp: add HUBRIS_TASK environment variable

- .github/buildomat/build-one.sh
- .github/buildomat/force-git-over-https.sh
- .github/buildomat/jobs/gimlet-c-lab.sh
- .github/buildomat/jobs/gimlet-c.sh
- .github/buildomat/jobs/gimlet-d-lab.sh
- .github/buildomat/jobs/gimlet-d.sh
- .github/buildomat/jobs/gimlet-e-lab.sh
- .github/buildomat/jobs/gimlet-e.sh
- .github/buildomat/jobs/gimlet-f-lab.sh
- .github/buildomat/jobs/gimlet-f.sh
- .github/buildomat/jobs/psc-b.sh
- .github/buildomat/jobs/psc-c.sh
- .github/buildomat/jobs/rot.sh
- .github/buildomat/jobs/sidecar-b-lab.sh
- .github/buildomat/jobs/sidecar-b.sh
- .github/buildomat/jobs/sidecar-c-lab.sh
- .github/buildomat/jobs/sidecar-c.sh
- .github/buildomat/jobs/sidecar-d-lab.sh
- .github/buildomat/jobs/sidecar-d.sh
- .github/buildomat/jobs/sign-sp1.sh
- .github/buildomat/jobs/sign-sp2.sh
- .github/buildomat/notes.md
- .github/buildomat/permslip-setup.sh
It's useful to have some images that have gone through a `permslip sign`. Do so in a very limited fashion.
> Add buildomat jobs for select images

- website/bugs/index.html
- website/index.html
- website/style.css
The `gh-pages` branch is autogenerated from this folder, so our previous changes were blown away.
> Add 'days since last Hubris bug' to website subfolder

- build/kernel-link.x
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/lib.rs
The only nightly feature still used in the kernel is `#[naked]` on functions. This can be replaced with careful use of `global_asm!` to create functions in pure assembly language.
With this change, the kernel builds and works on stable 1.82.0 using my out-of-tree build system.
> Allow kernel to be built with stable toolchain.

- drv/gimlet-seq-server/src/main.rs
Fixes #1929
Since `write_bytes` uses the `Write` operation, we effectively clear the A1 bit when setting the A0 bit. Using `set_bytes` uses a `BitSet` operation, allowing us to set A0 while leaving A1 in place. The FPGA has papered over this by ignoring the A1 bit while it is in A0.
> gimlet-seq-server: use set_bytes not write_bytes for sequencing control

- app/donglet/app-g031.toml
- sys/kern/build.rs
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/syscalls.rs
- test/tests-stm32g0/app-g070.toml
You might recognize this as #1134. Well, it's back. My fix for the problem on ARMv6-M was apparently never quite correct on M0+, because the core register we were relying on to detect and cancel a pending SVC -- SHCSR -- is _implemented_ but _only visible from the debugger._ So when I tried it by hand in openocd, it worked... but from the kernel it silently fails.
ARM, you are not making friends with stuff like this.
I've worked out a different way to _detect_ the "fault during SVC" case using the always-implemented ICSR register. That register doesn't provide any way to _cancel_ the SVC, so I've added conditional code to the syscall entry path that can do it.
Fixes #1928.
> kern: suppress phantom SVCs on ARMv6-M

- doc/kipc.adoc
- sys/abi/src/lib.rs
- sys/kern/src/kipc.rs
- sys/userlib/src/kipc.rs
- task/jefe/src/main.rs
This resolves a four-year-old TODO in El Jefe asking for a way to process faulted tasks without making so many kipcs. The original supervisor kipc interface was, by definition, designed before we knew what we were doing. Now that we have some miles on the system, some things are more clear:
1. The supervisor doesn't use the TaskState data to make its decisions.
2. The TaskState data is pretty expensive to serialize/deserialize, and produces code containing panic sites.
3. Panic sites in the supervisor are bad, since it is not allowed to panic.
The new find_faulted_task operation can detect all N faulted tasks using N+1 kipcs, instead of one per potentially faulted task, and the request and response messages are trivial to serialize (one four-byte integer each way). This has allowed me to …
> Add kipc::find_faulted_task.

- sys/userlib/src/kipc.rs
The kipc stubs tend to assert on the rc value received from the kernel. This isn't ideal: we generally have to trust the kernel, and we can't do anything useful if it misbehaves. So the assert is merely costing a bunch of flash for a condition that can never happen. This removes these asserts.
The system_restart kipc needs to indicate a "noreturn" send, but of course we have no way of doing that right now. So, it panicked if the send returned. This created _another_ can't-happen panic site in flash. I've replaced it with an infinite loop that compiles to a two-byte branch instruction, and in practice will never even be reached (but the compiler doesn't know that).
This further reduces text and stack size in El Jefe.
> userlib: remove panics in kipc implementation

- lib/host-sp-messages/src/lib.rs
- lib/oxide-barcode/src/lib.rs
This retains the original maximum length for both fields, but permits parsed strings to contain shorter sections. Shorter sections are right-padded with NULs for consistency with IPCC.
Fixes #1893
> oxide-barcode: allow shorter serial and part numbers

- app/donglet/app-g031.toml
- task/jefe/Cargo.toml
- task/jefe/src/main.rs
The supervisor task in Hubris is not permitted to panic, since it's responsible for handling panics.
Jefe has historically contained a bunch of (static) panics, many of which aren't actually possible at runtime. I've been gradually grinding away at these in my other PRs.
As of #1937, it's now possible to build a _minimal_ Jefe (like we use on the G0) that contains no panics. So I've enabled that on donglet, and turned on the userlib/no-panic feature that will statically ensure it remains true.
Turning on dump support in Jefe causes a bunch of panics to reappear, because humpty is panic-heavy. That's a task for another day.
> Enable a panic-free Jefe for the first time

- build/util/src/lib.rs
Previously, if you attempted to use certain functions in the build_util crate...and your output directory happened to not include any parent directories with the exact name "target"...
...the build script would burn 100% of a core forever, until you killed it.
This doesn't affect Hubris-proper but _does_ affect out of tree builds. The original code was arguably wrong anyway, so, this fixes that.
> build/util: prevent infinite loop if target/ not found

- Cargo.lock
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gemini-bu/app.toml
- app/gimletlet/base-gimletlet2.toml
- app/sidecar/base.toml
- drv/stm32h7-rng/Cargo.toml
- drv/stm32h7-rng/src/main.rs
We have a machine in manufacturing that gets periodic seed errors. The manual specifies a recovery procedure for seed errors... which we haven't implemented.
This commit makes us more tolerant of seed errors by attempting recovery, but not twice in a row. Two seed errors in a row will still return an error.
This also adds a ringbuf so we can monitor frequency.
> stm32h7-rng: rework driver, add seed error recovery

- sys/kern/src/arch/arm_m.rs
The kernel really wants to scribble task memory. Like, really really. Like, contains `unwrap()`s about it.
This is silly. It's a diagnostic tool. The kernel doesn't care if it works or not, and the application should not fail to start because of it.
So, this commit makes it optional and tolerates failure.
Is this me papering over a kernel bug? Yes, #1943 to be precise. But it's reasonable paper.
> kern: Make stack zap failure less catastrophic

- doc/syscalls.adoc
- sys/abi/src/lib.rs
- sys/kern/src/arch/arm_m.rs
- sys/kern/src/syscalls.rs
- sys/userlib/src/lib.rs
Currently drivers tend to get a spurious interrupt notification just after handling a real one. This is because the interrupt controller notices the kernel generic ISR exit while the interrupt condition is still asserted, because it doesn't expect us to be handling it in task code. So, it sets the pending bit so the 'new' interrupt condition isn't forgotten.
This causes an interrupt to occur immediately when we re-enable.
This adds an additional bit for IRQ_CONTROL that drivers can use to request any pending interrupt status be cleared.
Fixes #536.
> kern: let drivers disable double-interrupt behavior

- drv/auxflash-api/src/lib.rs
- drv/auxflash-server/src/main.rs
The auxflash server was computing a SHA3 of every potentially occupied slot in the QSPI flash, only to compare it to _the stored SHA3_ and then compare it to _the expected SHA3_ and then throw it away. This has been causing Sidecar startup to be linear in the number of valid images that have ever been flashed to auxflash, up to 16.
This change rearranges the logic, at least for startup. For each chunk, we now see if it even claims to have the right SHA. Only then do we compute the actual SHA to validate. This reduces an 11.6s delay observed on one Sidecar to just over 1s, and knocks 6s off the boot (something else is still delaying for 5s).
I haven't changed the behavior of the externally exposed `read_slot_checksum` operation, because it has no documentation and I can't figure out what …
> auxflash: make startup a lot faster.

- app/donglet/app-g031-i2c.toml
- app/gimlet/rev-b.toml
- app/gimlet/rev-d.toml
- app/sidecar/base.toml
- drv/stm32xx-i2c/src/lib.rs
- drv/stm32xx-i2c/src/pca9545.rs
It turns out that none of our hardware actually uses the 8-channel part (except Grapefruit, indirectly through Ruby).
> Add PCA9545 driver, use on Gimlet + Sidecar

- doc/interrupts.adoc
- doc/kipc.adoc
I [recently discovered][1] that the `software_irq` KIPC call is missing
reference documentation. In fact, the KIPC documentation doesn't even
mention it (in contrast to other KIPC calls that have no documentation
but are still listed in the reference). Instead, the reference
documentation currently incorrectly states that `find_faulted_task` is
KIPC number 8, when it's actually KIPC 9 and `software_irq` is number 8.
Not adding this KIPC to the docs was an oversight on my part in PR #1661
--- my bad, sorry!
This commit adds documentation for the `software_irq` KIPC to the
reference.
[1]: https://github.com/oxidecomputer/hubris/pull/1961#discussion_r1898058287
> docs: add missing `software_irq` KIPC docs

- doc/syscalls.adoc
- sys/abi/src/lib.rs
- sys/kern/src/syscalls.rs
The syscall docs say that attempting to reply with a message that's too big for your client to accept is a programming error. Programming errors are expected to produce faults in the program with the error. This fault is documented as being of type `ReplyTooLarge`.
However, there is no such fault defined in the ABI, and the actual behavior of the kernel is to deliver the prefix of the reply that fits, and hand the client the length of that prefix. In our current world, this means the client will generally die shortly thereafter with a deserialization error.
In a potential future world where messages can contain variable length portions, the client might not even hit an error when the reply is truncated.
The code in the kernel has been marked with a TODO since forever. This commit resolves …
> kern: reply buffer capacity checking

- sys/kern/src/arch/arm_m.rs
I was playing with reducing ARMv8-M context switch time, by looking into the same sort of changes to MPU loading that I recently did on v6/7.
I noticed that we only ever bitwise-OR values into the MAIR registers. In other words, the first task that gets activated loads its exact attributes into MAIR for each region; the _second_ task combines its attributes using bitwise OR; and so on until the registers contain the bitwise OR of all regions in all tasks. (Note that these are the cacheability/sharability attributes, _not_ the access permissions, which are set correctly. The main implication of this would be accidentally caching device memory or breaking DMA.)
That seemed bad, so I removed it and reworked the MPU loading loop. Now we build up the MAIR contents in a local before writing …
> kern: rework ARMv8-M context switch, fixing a bug?

- app/grapefruit/app.toml
- task/packrat/Cargo.toml
- task/packrat/src/grapefruit.rs
- task/packrat/src/main.rs
> Add host startup options support to Grapefruit

- app/grapefruit/app.toml
- drv/grapefruit-seq-server/src/main.rs
This is another small improvement for #1983
It needs testing on actual hardware!
> Add `send_hardware_nmi` to Grapefruit

- app/gimletlet/app.toml
- task/host-sp-comms/src/tx_buf.rs
In the current IPCC design, the SP sends zero bytes periodically when the channel is idle to guard against the possibility of losing a frame terminator. On gimlet this causes the UART FIFO to quickly fill up and so when the channel wakes up there are around 16 bytes to drain and things move along. On grapefruit/cosmo, however, there is a 4K FIFO in the FPGA upstream of the SP here so the natural saturation doesn't (yet) occur as we'd like. The extra zero bytes also make tracing the bus harder. Disable them for now.
> Disable periodic IPCC zero bytes on Grapefruit

- sys/kern/src/arch/arm_m.rs
- sys/kern/src/kipc.rs
- sys/kern/src/syscalls.rs
It turns out it's possible to trigger a bounds check in kipc handling code by submitting an invalid IRQ number. This fixes that, causing the bounds check to be optimized out.
In several syscall paths (and one kipc) we manipulate interrupts without accepting an interrupt number from the client. In these cases, a bad interrupt number would indicate a problem in our dispatch table, so I've made them explicit panics. (They were panics before, just implicit ones in the array access.)
This causes a small increase in kernel text size (40-64 bytes), but kipc should not be able to crash the kernel!
> kern: fix client-controlled kernel panic in kipc

- sys/abi/src/lib.rs
- sys/kern/src/syscalls.rs
- sys/kern/src/task.rs
- sys/kern/src/umem.rs
- sys/kern/src/util.rs
- sys/kerncore/src/lib.rs
- test/test-suite/src/main.rs
This is unspooling more commits from my performance fix branch in my fork. As with the previous performance PR, this is a collection of semi-related commits that may be easier to review commit-by-commit than as a big diff. Boy I miss Gerrit.
This is only a ~10% overall improvement because most of the truly low hanging fruit has been eaten. But, this significantly improves the performance of kernel memory copies and SEND with an empty message (unusual but not unheard of). This also knocks a few hundred bytes off a typical kernel by removing some panic sites.
> Another batch of syscall perf enhancements

- task/power/src/bsp/gimlet_bcdef.rs
- task/power/src/bsp/gimletlet_2.rs
- task/power/src/bsp/psc_bc.rs
- task/power/src/bsp/sidecar_bcd.rs
- task/power/src/main.rs
On Gimlet and Sidecar, the mapping from `DeviceType` (CPU, memory, fans, etc) to chip (RAA229618, MAX5970, etc) was one-to-one.  However, that's going to change for Cosmo (RAA229620A power controller, new hot-swap ICs, etc).
This PR adds a separate `chip: DeviceChip` field to the (static) power controller configuration.  It leaves the previous `DeviceType` field unchanged, although I'm not _totally_ sure if it's still relevant.
> Separate device type and chip for power config

- task/host-sp-comms/src/bsp/gimlet_bcde.rs
- task/host-sp-comms/src/inventory.rs
This is standalone prep for Cosmo, making the macro useable outside of the Gimlet inventory.
In addition, we add a variant to the macro which lets the caller control the array size.  This is needed when there are designators of different lengths in the same inventory slot, e.g. `U123` and `U51`.
> Move `by_refdes` into `pub(crate)` module

- website/bugs/index.html
This includes the bugs I've found recently, all of which have merged fixes.
> website: update the kernel bug page, which has been lagging

- drv/cosmo-hf/src/hf.rs
- drv/cosmo-hf/src/main.rs
- drv/gimlet-hf-server/src/main.rs
- drv/hf-api/src/lib.rs
- idl/hf.idol
In Cosmo and Grapefruit, we divide a 128 MiB flash chip into two (now three) sections:
- 32 MiB of slot 0 (host boot data)
- 32 MiB of slot 1 (host boot data)
- 64 MiB of Bonus Data (previously unused)
The host boot slots use the lowest 64 KiB for "persistent data", which right now encodes which slot to select at boot time.  This behavior is identical to Gimlet, and is unchanged in the PR.
This PR consists of three standalone commits, which do the following:
- Check flash addresses in the `cosmo-hf` driver, to avoid writing into other sections by accident
- Use a strong type for an absolute address (versus `u32` for a section-relative address)
- Add new Hiffy APIs to read and write the upper 64 MiB of flash
- These APIs are added to the `HostFlash` interface, so they're also added to …
> Add support for Bonus Data in Cosmo host flash

- drv/transceivers-server/src/main.rs
While Sidecar is not in A0 the transceivers-server will now keep the LEDs off. The current behavior is that the LEDs only change state when Dendrite tells them to, and while the Sidecar is not in Dendrite isn't doing much at all! An A0->A2 transition left the LEDs in their current state which is confusing for folks who may have eyes on the switch as it would indicate Dendrite is running when it is in fact not. The system attention LED is unaffected by this commit.
fixes https://github.com/oxidecomputer/hubris/issues/1995
> transceivers-server: keep LEDs off while not in A0

- Cargo.lock
- drv/i2c-devices/src/lib.rs
- drv/i2c-devices/src/raa229620a.rs
- task/power/src/main.rs
Another standalone building block for Cosmo.
The RAA229620A is identical to the RAA229618 (for our purposes), other than its device ID code.
> Add RAA229620A rail driver

- Cargo.lock
- app/grapefruit/app.toml
- drv/cosmo-hf/Cargo.toml
- drv/cosmo-hf/src/main.rs
- drv/grapefruit-seq-server/Cargo.toml
- drv/grapefruit-seq-server/src/main.rs
- drv/spartan7-loader-api/Cargo.toml
- drv/spartan7-loader-api/build.rs
- drv/spartan7-loader-api/src/lib.rs
- drv/spartan7-loader/Cargo.toml
- drv/spartan7-loader/build.rs
- drv/spartan7-loader/src/main.rs
- drv/spartan7-spi-program/src/lib.rs
- idl/spartan7-loader.idol
For Grapefruit and Cosmo, the Spartan-7 FPGA is used as a memory-mapped peripheral once its bitstream is loaded.  It's important that it not die or be reset, because that will be Very Confusing for any tasks writing directly into its memory space.
This PR moves loading that FPGA into a standalone task, separate from `grapefruit-seq` (and the eventual `cosmo-seq`).  The new task is infallible once it enters the Idol runtime loop, and can provide unforgeable tokens that prove the FPGA was loaded; eventually, I'd like for FPGA-based peripherals to take those tokens in their constructors.
The code changes in this PR are mostly reorganization and boilerplate, pulling stuff from `grapefruit-seq` into `drv-spartan7-loader` and writing `drv-spartan7-loader-api` / Idol files.
Tested on Grapefruit …
> Standalone spartan-7 loader

- drv/stm32h7-update-server/src/main.rs
It was incorrectly set to 0x00.
Measurement of an installed SP image will not be correct without this change.
Using `humility readmem ...` we can see the effect of this change.
Incorrect padding of an SP image with 0x00.
See caboose offset at 0x00083afc (0x00000100) with 0x00 padding to the end of 256-byte flash block.
```
00083a60  f7 c4 84 3c 67 72 61 70  65 66 72 75 69 74 00 00  |...<grapefruit..|
00083a70  f8 11 f5 08 ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00083a80  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00083af0  ff ff ff ff ff ff ff ff  ff ff ff ff 00 01 00 00  |................|
00083b00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00083c00  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff …
```
> Flash padding byte is 0xff for correct SP FWID.

- app/gimletlet/app.toml
- drv/mock-gimlet-hf-server/src/main.rs
We have more boards available with actual host flash, just use the mock server by default.
> Fixup `mock-gimlet-hf-server` and switch to it for gimletlet

- .github/workflows/build-boards.yml
- app/grapefruit/app-dev.toml
- app/grapefruit/app-ruby.toml
- app/grapefruit/base.toml
- task/host-sp-comms/Cargo.toml
- task/host-sp-comms/src/main.rs
- Splits Grapefruit into `app-dev.toml` (dev boards only) and `app-ruby.toml` (attached to Ruby)
- Switch `app-dev` to using UART8, which is brought out on a connector
This lets us test IPCC on a desktop, connecting to Grapefruit with a USB-to-serial cable.
> Split Grapefruit into Ruby vs standalone images

- .github/buildomat/build-one.sh
- .github/buildomat/jobs/rot.sh
- .github/buildomat/permslip-setup.sh
- .github/workflows/build-one.yml
Works around https://github.com/rust-lang/rustup/pull/3985 ?
> Install toolchain before doing anything

- drv/cosmo-hf/build.rs
- drv/cosmo-hf/src/main.rs
- drv/hf-api/src/lib.rs
Eventually, `cosmo-hf` will support both Grapefruit and Cosmo FPGA images.  The upcoming Cosmo image has a different set of base registers, so let's not check them; checking that the FPGA has booted is not really `cosmo-hf`'s job anyways!
(cherry-picked from 73fbbb98f50117f51a2a8cbf6dd5b83f628b805c in the `mkeeter/cosmo-support` branch)
> Don't get FPGA ID in `cosmo-hf`

- Cargo.lock
- Cargo.toml
- app/grapefruit/base.toml
- build/xtask/Cargo.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- chips/stm32h7/chip.toml
This lets us specify a set of FMC-attached **virtual peripherals**, which are implemented in an FPGA.
A manifest may specify an `[fmc]` configuration object, with a base address and register map (which is a JSON file).  If present, `xtask` parses the JSON file and adds its peripherals to the `chip.toml`'s peripheral list, prefixed with `fmc_`.  Tasks can include these peripherals in their `uses = [...]` list.
Instead of copying `chip.toml` into the output archive, we re-serialize the `peripherals` map, so that it includes these virtual peripherals.  This means that `humility map` works fine:
```
DESC       LOW          HIGH          SIZE ATTR   ID TASK
...elided...
0x08005820 0x60000000 - 0x600000ff     256 rw-d-- 24 [fmc_base] fmc_demo, hf
0x0800585c 0x60000100 - 0x600001ff     256 …
```
> FMC-attached peripherals

- test/tests-lpc55xpresso/src/main.rs
I'm actually not 100% sure this isn't needed here, but it appears vestigial, so let's give it a CI run.
> Removed unneeded used_with_arg

- task/jefe/src/main.rs
The address in the dump area header is constant, but other values can change, so we should reload it from RAM!
Fixes #2031
> Fix dump area caching

- app/donglet/app-g031.toml
- task/hiffy/src/main.rs
The compiler was getting rid of some HIFFY symbols we actually needed, so we try to ask it to keep them.
Bump stack size to keep `jefe` from faulting.
> adjust settings for donglet

- build/i2c/src/lib.rs
We had issues on Cosmo due to selecting a non-existent mux; this checks at build time.
> Fail build if an I2C device uses a non-existent mux

- drv/cosmo-hf/src/hf.rs
- drv/gimlet-hf-server/src/main.rs
- drv/mock-gimlet-hf-server/src/main.rs
- idl/hf.idol
- task/control-plane-agent/src/update/host_flash.rs
We don't want programming the host flash to _also_ set the slot used at boot (see #1958 for details), because interruptions could leave us in an unfortunate state.
This PR adds new `page_program_dev` and `sector_erase_dev` functions, which operate on a particular slot (passed as an argument), but are guaranteed to leave the active slot unchanged when they exit.  In other words, they switch to a particular slot, perform an action, then restore the previous slot before returning the result.
In `control-plane-agent`, we now use those functions during host flash updates (previously, we set the host flash slot during `HostFlashUpdate::prepare` then assumed it wouldn't change).
There's one behavioral change: at the end of the update, we have not (implicitly) switched to the new slot.  Looking …
> Don't modify active slot while updating host flash

- app/cosmo/base.toml
- app/demo-stm32h7-nucleo/app-h743.toml
- app/demo-stm32h7-nucleo/app-h753.toml
- app/gimlet/base.toml
- app/gimletlet/base-gimletlet2.toml
- app/grapefruit/base.toml
- app/medusa/base.toml
- app/minibar/app.toml
- app/psc/base.toml
- app/sidecar/base.toml
- task/hiffy/Cargo.toml
- task/hiffy/src/main.rs
_No description provided._
So, `humility qspi` and auxflash commands are Really Slow on Cosmo. It turns out that this is because Hiffy has a magical list of boards that are allowed to go fast, and we never put Cosmo on it. Boards on the go-faster list are allowed to use a much larger buffer for data transferred through Hiffy than boards not on the go faster list. 
Controlling this based on `target_board` seems quite unfortunate. Subsequent revisions of the same board need to be added to the list, and it's easy to forget to do that when there's a new board revision and regress hiffy performance again (c.f. #1498). Instead, let's control this via a Cargo feature, which can at least be set in the `base.toml` for a board and inherited by every subsequent revision of the board without having …
> "humility qspi -D" is sluggish on...everything else

- Cargo.lock
- sys/task-names/Cargo.toml
- sys/task-names/build.rs
- sys/task-names/src/lib.rs
This allows tasks to refer to other tasks by name, which we need _very rarely,_ but has come up for fault reporting.
> Basic crate for accessing task names at build time.

- drv/cosmo-hf/src/main.rs
I discovered this commit floating in my tree, and it seems reasonable enough!
> Re-export host flash constants

- idl/thermal.idol
- task/thermal/src/bsp/cosmo_a.rs
- task/thermal/src/bsp/gimlet_bcdef.rs
- task/thermal/src/bsp/grapefruit.rs
- task/thermal/src/control.rs
- task/thermal/src/main.rs
I'm removing `set_fan_pwm` from the `thermal` task interface because its existence no longer serves a purpose. Fans can either be in `auto` control mode, where the thermal model decides the PWM, or `manual` control mode, which effectively hardcodes the PWM to the `initial_pwm` argument of `set_mode_manual`. I say "effectively hardcodes" because it calls the [`maintain_pwm`](https://github.com/oxidecomputer/hubris/blob/master/task/thermal/src/main.rs#L333) function each loop iteration. This means that when `set_fan_pwm` was setting the PWM value, it would just be overwritten the next iteration. In addition to that, we just don't control single fans really, so the fact that `set_fan_pwm` required a single fan to be specified just doesn't match reality any more.
An alternative path here …
> thermal: remove set_fan_pwm

- drv/i2c-devices/src/lm5066.rs
- task/power/src/bsp/cosmo_a.rs
The LM5066 has strong opinions on what error flags should be set on startup:
- `STATUS_BYTE` says the VIN fault flag is set by default, no comment about autoclearing; flags should be cleared with `CLEAR_FAULTS`
- `STATUS_WORD` says VIN fault flag is set by default, and is cleared when input voltage > UVLO threshold
- `STATUS_INPUT` says the VIN _warning_ flag is set by default (the VIN fault flag is 0 by default), and is cleared when input voltage > UVLO threshold
In practice, we see the fault flag set in all three of these registers, as well as `!PowerGood`.
This PR adds a `CLEAR_FAULTS` call to the `power` task startup, to persuade the power-good bit to actually reflect reality.  We don't expect the `power` task to restart, so this should be a one-off occurrence (and genuine faults …
> Clear LM5066 faults on `power` startup

- Cargo.lock
- app/cosmo/base.toml
- drv/i2c-devices/src/lib.rs
- drv/i2c-devices/src/lm5066i.rs
- lib/host-sp-messages/src/lib.rs
- task/host-sp-comms/src/bsp/cosmo_a.rs
- task/power/src/bsp/cosmo_a.rs
- task/power/src/main.rs
(Staged on top of #2073)
The LM5066I has different coefficients and a different validation serial name.  This PR makes a new driver for it (which uses a bunch of types from LM5066, and is _mostly_ copy-pasted).  This new part is used on Cosmo.
> Add LM5066I driver; use it on Cosmo

- task/host-sp-comms/src/bsp/cosmo_a.rs
The BSP identities for the sharkfin refdes were using the Gimlet sharkfin refdes as opposed to the Cosmo ones as the board ended up changing across this. I still will need to test this with some sharkfins present and will not merge until I can confirm that I have data. But I do note that we are now using the correct key when missing sharkfins:
```
BRM13250010 # /usr/platform/oxide/bin/ipcc inventory 4
metadata:
version: 0x0
entries: 0x3b
J200/U2/ID (4) -- Result: 2 [I/O error -- device gone?]
BRM13250010 # /usr/platform/oxide/bin/ipcc inventory 14
metadata:
version: 0x0
entries: 0x3b
J200/U2 (14) -- Result: 2 [I/O error -- device gone?]
```
> Correct cosmo sharkfin refdes

- drv/cosmo-hf/src/hf.rs
@rmustacc noticed that updating host flash didn't work over the management network on Cosmo.  I reproduced this locally on a Grapefruit; this PR is the fix.
The issue was that MGS uses `HostFlash::capacity` to decide how many sectors to erase.  On Gimlet, this is the true capacity of a physical flash chip, of which there are two.  On Cosmo, we instead split a single 1 GiB flash into 2× 32 MiB + 1× 64 MiB virtual devices.
We were returning the full 1 GiB flash size, so MGS tried to erase outside the range of the 32 MiB virtual slot.  On the bright side, Hubris correctly detects this and returned an `HfError::BadAddress`.
The fix is to return a capacity of 32 MiB, because that's the capacity that MGS needs to know about.
> Fix Cosmo flash capacity

- Cargo.lock
- app/cosmo/base.toml
- drv/ignition-flash/Cargo.toml
- drv/ignition-flash/build.rs
- drv/ignition-flash/src/main.rs
- idl/ignition-flash.idol
This is a minimal flash driver, suitable for testing with `humility hiffy -c IgnitionFlash....`
It has somewhat been tested by Nathanael on a reworked Cosmo, but should be tested again to check that `Command::ReleaseFromDeepPowerDown` is working.
> Add Ignition flash driver to `cosmo` images

- lib/host-sp-messages/src/lib.rs
- task/host-sp-comms/src/bsp/cosmo_a.rs
- task/host-sp-comms/src/bsp/gimlet_bcde.rs
- task/host-sp-comms/src/bsp/gimletlet.rs
- task/host-sp-comms/src/bsp/grapefruit.rs
- task/host-sp-comms/src/main.rs
(staged on top of #2094)
This adds DDR5 DIMMS to the `host_sp_comms` inventory reported over IPCC.
I'd like to do some refactoring to reduce stack allocation, because the `enum InventoryData` is now over 1 KiB, but this is reasonable for initial tests.
> Add cosmo dimms to host_sp_comms inventory

- drv/gimlet-seq-server/src/main.rs
https://github.com/oxidecomputer/hubris/pull/2104 accidentally waited for `Done` instead of `GroupcPg`, so the sequencer would never come up.
> Fix sequencing wait condition

- drv/cosmo-hf/src/hf.rs
- drv/cosmo-hf/src/main.rs
- drv/gimlet-hf-server/src/main.rs
- drv/hf-api/src/lib.rs
- drv/mock-gimlet-hf-server/src/main.rs
- idl/hf.idol
- lib/host-sp-messages/src/lib.rs
- task/hiffy/src/common.rs
- task/host-sp-comms/src/bsp/cosmo_a.rs
- task/host-sp-comms/src/bsp/grapefruit.rs
- task/host-sp-comms/src/main.rs
- Add a new `HfChipId` type as a more structured chip ID, then use it in the various host flash drivers
- Add an `InventoryData::W25q01jvzeiq` variant and use it on Cosmo
This needs testing, so I'm opening as a draft for now.
> Add Cosmo host flash to inventory

- chips/stm32f3/memory.toml
- chips/stm32f4/memory.toml
This fixes a failing test (`execdata`) in the kernel test suite on the STM32F3 Discovery Board.
> Make RAM non-executable on STM32Fx parts

- README.mkdn
There are currently a few things in the README which are incorrect or no longer relevant:
- There is no longer a `stage0/` directory in the repository (I presume this has been subsumed by `bootleby`)
- The `chip/` directory is actually called `chips/`
- Various references to OpenOCD/pyOCD being required development dependencies. These are no longer necessary, as `humility` now uses `probe-rs` instead.
I didn't touch a couple bits of sample output from `pyocd` in the LPCXpresso55S69 documentation, as I don't have that board on hand and couldn't generate the equivalent examples for `probe-rs`' commands. If someone has that board and wants to take the time to produce the equivalent example output, I'm happy to add them here.
> Remove outdated references from README

- app/cosmo/base.toml
- app/gimlet/base.toml
- app/gimletlet/base-gimletlet2.toml
- app/lpc55xpresso/app.toml
- app/medusa/base.toml
- app/oxide-rot-1/app-dev.toml
- app/oxide-rot-1/app.toml
- app/psc/base.toml
- app/rot-carrier/app.toml
- app/sidecar/base.toml
- build/xtask/Cargo.toml
- build/xtask/src/config.rs
- build/xtask/src/dist.rs
- build/xtask/src/main.rs
- doc/guide/caboose.adoc
When flashing an engineering Hubris image on an SP that will participate
in a control-plane driven software update, it is necessary to populate
the `VERS` key in the caboose must be present so that the update
machienry doesn't get confused. If it is desirable for the engineering
image to not be overwritten during an update, the verson must also be
set to the version expected by the system. Being able to do this is
useful for testing Hubris changes in integration with the rest of the
system.
Historically, such images have been created by hacking up the `xtask
dist` code to write the desired version string when creating the default
caboose. I thought that this seemed like a common enough thing to want
to do that there should just be a way to ask for it without having to
change the build …
> xtask: Override default caboose version from env

- app/cosmo/base.toml
- app/gimlet/base.toml
- app/grapefruit/base.toml
- app/psc/base.toml
This isn't detected by the stack size check because `serde` has recursive calls.
```
humility: attached to dump
system time = 123546
ID TASK                       GEN PRI STATE
20 control_plane_agent          0   8 FAULT: stack overflow; sp=0x2402ffd8 (was: ready)
could not read registers: read of 32 bytes from invalid address: 0x2402ffd8
guessing at stack trace using saved frame pointer
|
+--->  0x24031870 0x08054b98 <hubpack::de::SeqAccess as serde::de::SeqAccess>::next_element_seed
@ /crates.io/hubpack-0.1.2/src/de.rs:280
```
Marking it as a draft, pending testing on hardware (as part of #2158)
> Bump Cosmo `control-plane-agent` stack size

- drv/stm32xx-i2c-server/src/main.rs
- drv/stm32xx-i2c/src/lib.rs
- drv/stm32xx-i2c/src/ltc4306.rs
- drv/stm32xx-i2c/src/max7358.rs
- drv/stm32xx-i2c/src/oximux16.rs
- drv/stm32xx-i2c/src/pca9545.rs
- drv/stm32xx-i2c/src/pca9548.rs
It turns out that, in practice, we only ever provide a single function for each of `wfi` and `enable` here. This makes the table itself an unnecessary level of indirection, which has some deleterious effects:
- It opens the possibility for _different_ I2cControl structs containing _different_ function pointers to be passed to each call, complicating analysis. (Searching for this phenomenon was what led me to notice that we only ever use one implementation.)
- It makes it a lot harder to recognize use of syscalls (or misuse of syscalls) in the I2C layer.
- It routes important parts of the I2C stack through indirect function calls, defeating stack analysis.
- It adds a bunch of code that isn't really necessary, as it turns out.
This commit removes the dispatch table, inlining the existing …
> stm32xx-i2c: remove I2cControl function table

- app/cosmo/base.toml
- app/gemini-bu/app.toml
- app/gimlet/base.toml
- app/gimletlet/app.toml
We now get all sprot pin configuration via the stm32xx-sys library
> Remove old SP sprot configurations

- Cargo.lock
- app/cosmo/base.toml
- drv/cosmo-seq-server/Cargo.toml
- drv/cosmo-seq-server/build.rs
- drv/cosmo-seq-server/src/main.rs
- drv/cpu-seq-api/src/lib.rs
Instead of polling for our state changes, rely on the sequencer to deliver interrupts to us
> Introduce cosmo sequencer interrupts

- Cargo.lock
- app/cosmo/base.toml
- app/donglet/app-g031.toml
- app/gemini-bu/app.toml
- app/gimlet/base.toml
- app/gimlet/rev-b.toml
- app/gimlet/rev-d.toml
- app/gimletlet/app.toml
- app/grapefruit/app-ruby.toml
- app/medusa/base.toml
- app/psc/base.toml
- app/sidecar/base.toml
- build/i2c/src/lib.rs
- drv/i2c-api/Cargo.toml
- drv/i2c-api/src/lib.rs
- task/control-plane-agent/src/inventory.rs
- task/host-sp-comms/src/bsp/cosmo_a.rs
- task/host-sp-comms/src/bsp/gimlet_bcde.rs
- task/host-sp-comms/src/inventory.rs
- task/validate-api/Cargo.toml
- task/validate-api/build.rs
- task/validate-api/src/lib.rs
In the `gateway-sp-comms` protocol, hardware devices known to the SP are uniquely identified by _component IDs_. These IDs are generated by the SP and are given to the control plane when reporting inventory. The control plane may then request details about a particular hardware component using the ID received from the inventory.
Presently, these IDs use what I've been referring to as the "dev-NN scheme".  In this scheme, each component is identified by a string consisting of `"dev-` followed by a two digit number, which is generated by the `control-plane-agent` task from that device's position in an array of devices generated at build time. While @jgallagher  will claim that this is just a bad design driven entirely by expedience, it does have some redeeming qualities: the SP can look up …
> Use refdes-based component IDs in control-plane-agent

- drv/cosmo-hf/src/hf.rs
- drv/cosmo-hf/src/main.rs
In the current code, both `hash` and `hash_range_update` apply the `flash_addr` correction (going from relative offset to absolute address).
This means that if `Flash1` is selected, `hash` will end up hashing the Bonus Flash range:
- `hash` applies an offset to get an absolute address in `Flash1`
- `hash_range_update` re-applies that offset to an already-absolute address, pushing the address into Bonus Flash
I fixed this by not applying the offset in `hash` (although I still call `flash_addr` to perform address checks).
> Fix incorrect hash offset

- app/lpc55xpresso/Cargo.toml
This is useful for testing our mfg tools on an lpc55xpresso board
> lpc55xpresso: Add `dice-mfg` feature

- app/cosmo/base.toml
- app/grapefruit/base.toml
- drv/auxflash-api/Cargo.toml
- drv/auxflash-server/Cargo.toml
- drv/auxflash-server/src/main.rs
- drv/spartan7-loader/src/main.rs
On Cosmo and Grapefruit, it takes ~10 seconds to load the sequencer FPGA, which is a very human-noticeable delay.
According to https://github.com/oxidecomputer/hubris/issues/2088 , 4-bit QSPI works on Cosmo at 66 MHz, so this PR adds a new `fast-qspi` feature to use those settings.  The feature is enabled for Cosmo and Grapefruit.  It is not enabled for Sidecar because that hasn't been validated, and Sidecar load times have been less annoying.
In addition, the PR bumps our FPGA SPI clock divider from `DIV64` (1.5625 MHz) to `DIV8` (12.5 MHz).  This is well below the FPGA's limit of 100 MHz, but any faster and we hit https://github.com/oxidecomputer/hubris/issues/2133
Together, this bring the FPGA load time down to about 4 seconds.
I tested this on `cosmo-hubris-sp` and confirmed that the …
> Speed up FPGA loading on Cosmo / Grapefruit

- app/cosmo/Cargo.toml
- app/cosmo/base.toml
- app/gimlet/Cargo.toml
- app/gimlet/base.toml
- app/gimlet/rev-c.toml
- app/gimlet/rev-d.toml
- app/psc/Cargo.toml
- app/psc/base.toml
- app/sidecar/Cargo.toml
- app/sidecar/base.toml
Follow-up to https://github.com/oxidecomputer/hubris/pull/2138
Opening as a draft so I can test this out on the relevant systems.
> Enable measurement handoff on all production boards

- drv/stm32xx-i2c/src/lib.rs
The I2C code uses the kernel timer to attempt to detect cases where the hardware has "gone away" and stopped generating interrupts.
(What this _actually_ means is that the software state machine has gotten a transition wrong: we've never found evidence of misbehavior in the hardware block, at least so far. I'm including this caveat for people who find this commit online later.)
However, this code has contained two bugs, either of which could crash the driver.
First, the race condition. Under high load (say, when a crash dump is being recorded), the I2C driver may not reliably clear accumulated timer-expired notifications. This can happen as follows:
1. The hardware interrupt arrives. The kernel maps it to the I2C driver's notification mask. The notification bit is immediately set, and the …
> stm32xx-i2c: fix notification-induced crash

- drv/cosmo-seq-server/src/vcore.rs
- drv/gimlet-seq-server/src/main.rs
- drv/gimlet-seq-server/src/vcore.rs
This commit tweaks the field and class naming in the CPU sequencer ereports for VRM PMbus alerts (added in #2184) based on a discussion with @rmustacc on standardizing ereport naming and class hierarchy. In particular, we namespace all "hardware" events under "hw", and emit a different class name string when the POWER_GOOD state has changed. Additionally, we've rename the "status" field for PMBus status registers to "pmbus_status" for clarity, and the "dev_id" to "refdes" --- the idea is that "dev_id" will be used when we want to indicate that the `control-plane-agent` device ID is _different_ from the refdes, but all `hw.` ereports will include a "refdes".
> cpu_seq: standardize ereport naming

- Cargo.lock
- Cargo.toml
- build/toml-patch/src/lib.rs
- build/xtask/src/config.rs
The pinned version of `toml_edit` silently discards heterogeneous (mixed inline / block) tables.
This is unfortunate.
> bump `toml` and `toml_edit`

- drv/stm32xx-i2c/src/lib.rs
I've become convinced that the "LostInterrupt" failures we've intermittently seen in the I2C driver are due to timer notification mismanagement. I recently merged a commit (dd76a4cdea1c97) that reworked timer notification handling to eliminate a case where the driver could crash _itself_ in a narrow race condition window. That also eliminated a way to crashed it from other task, by posting to its timer notification bit (bit 31) while it was working -- both cases were fixed by double checking that the timer had actually gone off before responding.
With that fixed, there's only one way remaining to get the LostInterrupt panic, which is: keep i2c_driver from running for 100ms during any I2C transaction. You can do this pretty easily by triggering a large coredump. As a result, the driver …
> stm32xx-i2c: remove soft timeout, LostInterrupt

- build/xtask/src/dist.rs
- rust-toolchain.toml
When we bumped the toolchain, this changed as well.
Keeping the hash correct reduces the length of panic strings.
> Update sparse registry hash for new toolchain

- Cargo.lock
It looks like PR #2250 forgot to remove an updated lockfile after a Git dep on
a development branch was removed. The `Cargo.toml` is pointed at the correct
Git rev, but the lockfile doesn't realize that. This means that any time 
rust-analyzer (or Cargo) runs, it will immediately generate this diff:
```patch
diff --git a/Cargo.lock b/Cargo.lock
index 08fb860d..6fac3b3e 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -4327,7 +4327,7 @@ checksum = "b4596b6d070b27117e987119b4dac604f3c58cfb0b191112e24771b2faeac1a6"
[[package]]
name = "pmbus"
version = "0.1.7"
-source = "git+https://github.com/oxidecomputer/pmbus?branch=aaron%2Fadm1273-support#a029ad704f1be0ffa8030f252776ca4576fa69b0"
+source = "git+https://github.com/oxidecomputer/pmbus#631358a97cf9775c825a2cf726d51f0f243b91a4"
dependencies = [ …
```
> Update lockfile from #2250

- drv/stm32h7-startup/src/lib.rs
@mkeeter noticed nondeterminism in the delay loop for measurement handoff, which caused us to realize that it was being performed _before_ the caches were set up ... which means small alignment changes in flash can have huge impact on the execution time of a tight loop.
While considering fixes, I noticed that the fix for the AXI SRAM read erratum had gradually drifted below other code. This was safe when I initially implemented it, because we weren't using AXI SRAM for kernel stack etc. at the time. We are now!
This commit moves the AXI SRAM erratum fix into pre_init where it runs before most RAM accesses, and moves cache setup earlier in system_init_custom to ensure that caches are on for the rest of the process, including measurement handoff.
> stm32h7-startup: reorder AXI erratum and cache setup

- app/grapefruit/app-mini.toml
- drv/user-leds/src/main.rs
While debugging #2236, I wanted a tiny image that produced compact system dumps – they're faster to load in a debug build of Humility, and we'll eventually want to commit one to the Humility test suite.
This image produces a 421KiB dump, versus 7 MiB for a full Cosmo image.  It's just enough to blink an LED so that you know it's been flashed and is running.
> Add `grapefruit/app-mini.toml`
