oxidecomputer/hubris

.github/workflows/deploy.yml
website/index.html

A little website for Hubris

---

build/xtask/src/check.rs

The docs for xtask state that if --target is not provided then the value
from package.metadata.build.target will be used. This is true when
checking --all packages but not individual packages. This patch
implements this behavior when xtask check is:
- executed from the workspace root with the '-p' option
- executed from a project directory with no params
In both of these cases cargo metadata json is now parsed to extract the
project.metadata.build.target value. If found the target is then added
to the final check command invocation. Otherwise the 'cargo check'
default target (the host architecture) is used.

xtask: Use metadata.build.target when checking individual packages.

---

README.mkdn

Fix OpenOCD link

---

.github/workflows/dist.yml
.github/workflows/documentation.yml

* Rename build -> dist: this mirrors the command run
* Rename deploy -> documentation: this describes what it does in a less
ambiguous way
* use the built-in submodule support of the checkout action rather than
doing it manually

One improvement to CI

---

build/xtask/src/dist.rs
build/xtask/src/main.rs

This supports quick iteration on a single task (or small set of tasks)
without using the standalone build. It is intended to be a step toward
eliminating the standalone build.

xtask build: build a subset of tasks as in an app.

---

doc/interrupts.adoc

doc/interrupts: fix code example typo

---

README.mkdn
drv/lpc55-gpio/README.mkdn
drv/lpc55-syscon/README.mkdn
drv/stm32fx-rcc/README.mkdn
task/jefe/src/external.rs

Added useful details to the root README, based on a first-timer's
experiences.
Removed useless template READMEs. Minor fixes to docs.

Improve READMEs

---

sys/userlib/src/lib.rs

This behavior was always the _intent_ but I broke it earlier this year, it appears.

userlib: preserve 128+ byte panic messages in prefix.

---

app/sidecar/app.toml
drv/stm32h7-spi-server/src/main.rs

This is a quick commit to unblock sequencer development.

Add SPI for VSC7448 and sequencer FPGA

---

doc/syscalls.adoc
sys/abi/src/lib.rs
sys/kern/src/syscalls.rs
sys/kern/src/task.rs
sys/userlib/src/lib.rs
task/jefe/src/main.rs
test/test-runner/src/main.rs
test/test-suite/src/main.rs

Implement REPLY_FAULT.

---

Cargo.lock
app/demo-stm32h7-nucleo/app-h743.toml
app/gimlet/app.toml
drv/stm32h7-spi-server/src/main.rs
drv/stm32h7-spi/src/lib.rs
task/net/src/server.rs

STM32H7: more faster SPI

---

drv/gimlet-hf-server/Cargo.toml
drv/stm32h7-spi-server/Cargo.toml
drv/user-leds/Cargo.toml
task/hiffy/Cargo.toml
task/spd/Cargo.toml

It turns out this crate _has_ no features!

Remove default-features = false from h7-gpio-api deps

---

app/demo-stm32f4-discovery/app-f3.toml
app/demo-stm32f4-discovery/app.toml
app/demo-stm32g0-nucleo/app-g070.toml
app/demo-stm32h7-nucleo/app-h743.toml
app/demo-stm32h7-nucleo/app-h753.toml
app/gemini-bu-rot/app.toml
app/gemini-bu/app.toml
app/gimlet-rot/app.toml
app/gimlet/app.toml
app/gimletlet/app.toml
app/lpc55xpresso/app-a0.toml
app/lpc55xpresso/app.toml
app/psc/app.toml
app/sidecar/app.toml
build/xtask/src/dist.rs
build/xtask/src/main.rs
chips/lpc55.toml
chips/stm32f3.toml
chips/stm32f4.toml
chips/stm32g0.toml
chips/stm32h7.toml

Switch to using named IRQs whenever possible

---

Cargo.lock
Cargo.toml
test/test-idol-api/Cargo.toml
test/test-idol-api/api.idol
test/test-idol-api/build.rs
test/test-idol-api/src/lib.rs
test/test-idol-server/Cargo.toml
test/test-idol-server/build.rs
test/test-idol-server/src/main.rs
test/test-suite/Cargo.toml
test/test-suite/src/main.rs
test/tests-gemini-bu-rot/app.toml
test/tests-gemini-bu/app.toml
test/tests-gimletlet/Cargo.toml
test/tests-gimletlet/app.toml
test/tests-lpc55xpresso/app-a0.toml
test/tests-lpc55xpresso/app.toml
test/tests-stm32fx/app-f3.toml
test/tests-stm32fx/app.toml
test/tests-stm32g0/app-g070.toml
test/tests-stm32h7/app-h743.toml
test/tests-stm32h7/app-h753.toml

I felt bad about adding `bool` arguments without corresponding tests, so here's a bunch of Idol unit tests!
The PR also adds a new test image for Gimletlet, since that's the most common board, and will probably be our CI target (eventually),

Idol test suite

---

drv/vsc7448/src/lib.rs

The tagging is configured on egress, not ingress.

Fix VLAN configuration

---

build/xtask/src/flash.rs

Now that humility has a flash command as of humility commit
5459f01d0b18f4ef8f4505e049302085d6a0d3dd we can use that directly
instead of calling out to {py, Open}OCD.
Note that one of the boards doesn't work out of the box at the
moment with probe-rs.

Flash using `humility flash`

---

lib/gnarle/src/lib.rs

While attempting to decompress a chunked input (a compressed bitstream, sent in blocks between tasks) it was found (thanks @kc8apf!) that run sequences spanning chunks would get mangled and result in an incorrect output. This diff adds two more states to the compressor, allowing it to continue across such chunk boundaries.
This was tested by decompressing a stream using 128 byte buffers for both the input and output.

Allow Gnarle to decompress chunked input data

---

app/demo-stm32h7-nucleo/app-h743.toml
app/demo-stm32h7-nucleo/src/main.rs
sys/kern/src/arch/arm_m.rs
sys/kern/src/lib.rs
sys/kern/src/profiling.rs
sys/kern/src/syscalls.rs

More details in the comments on sys/kern/src/profiling.rs.

Add very basic kernel profiling support.

---

app/gimlet/rev-b.toml
app/sidecar/app.toml
task/net/src/bsp/gimlet_1.rs

Tested and working on the bench!

Enable Gimlet VLAN and Sidecar CS workaround

---

drv/lpc55-swd/src/main.rs

The RoT controls the SP via SWD. This is the same SWD that needs to be
used for external debugging/programming. Delay configuring any pins
until setup is explicitly called to avoid conflicts with the external
debugger.

Delay SWD pin configuration

---

build/xtask/src/dist.rs

This ensures that we rebuild everything if changes are made to the linker scripts.  Previously, changes to `task-rlink.x` would not cause a rebuild of the task.

Add hash of linker scripts to RUSTFLAGS

---

Cargo.lock
app/gimlet/rev-a.toml
app/gimlet/rev-b.toml
app/sidecar/app.toml
drv/gimlet-seq-server/src/seq_spi.rs
drv/i2c-devices/src/isl68224.rs
drv/i2c-devices/src/max31790.rs
task/power/Cargo.toml
task/power/src/main.rs
task/thermal/Cargo.toml
task/thermal/src/bsp.rs
task/thermal/src/bsp/gimlet_a.rs
task/thermal/src/bsp/gimlet_b.rs
task/thermal/src/bsp/sidecar.rs
task/thermal/src/control.rs
task/thermal/src/main.rs

This diff adds a first cut for power and thermal management of a Sidecar mainboard/chassis by adding support for Sidecar to the `power` and `thermal` tasks.

Sidecar Power and Thermal management

---

task/hiffy/src/main.rs

The scratch buffer used by hiffy is now a static and no longer on the stack.
Fixes #473

Expose `HIFFY_SCRATCH` buffer

---

build/xtask/src/dist.rs

This will be checked once [this Humility PR](https://github.com/oxidecomputer/humility/pull/162) is merged

Bump archive version to v2

---

drv/vsc85xx/src/vsc8504.rs

This tweaks the order of VSC8504 bringup to put the chip reset in the right
place. It still doesn't actually _work_ on Sidecar, but that's probably for
other reasons.

Reorganize VSC8504 bringup

---

drv/stm32h7-i2c/src/lib.rs

This rework is focused on handling interrupt flags comprehensively and
at the right times, to try and fix #544 and related issues.
Broad themes you should expect to see here:
1. Enable peripheral interrupt generation _only_ for the cases that are relevant to the target state machine and that we're prepared to handle. This should fix #544 implicitly since that's a case where we spin with a flag we weren't expecting.
2. Make sure all flags that might accumulate during a particular phase are handled in that phase. (In #544 there was a case where the rx loop would fail to dequeue a single byte, leaving RXNE set for the later phases to discover.)
3. Enable kernel-side interrupt only when you want it, which in this case means right before `wfi`.

stm32h7-i2c: rework target state machine

---

drv/i2c-devices/src/at24csw080.rs

The `at24csw080` type breaks some of the I2C auto-generated code since that expects the type to be `At24Csw080`. With this driver not really in use yet renaming seems like the lowest friction path. In addition the `Validate` trait is implemented so this can be used to test presence.

Rename At24csw080 -> At24Csw080, implement Validate

---

drv/gimlet-seq-server/src/main.rs

Untested, since I don't have a Gimlet at home, but seems pretty straightforward!
Closes #606

Turn on chassis LED once we reach A2

---

app/gimletlet/app.toml
idl/net.idol
task/mgmt-gateway/src/main.rs
task/net-api/src/lib.rs
task/net/src/bsp/gimlet_1.rs
task/net/src/bsp/gimletlet_mgmt.rs
task/net/src/bsp/gimletlet_nic.rs
task/net/src/bsp/nucleo_h7.rs
task/net/src/bsp/psc_1.rs
task/net/src/bsp/sidecar_1.rs
task/net/src/main.rs
task/net/src/mgmt.rs
task/net/src/server.rs
task/net/src/server_basic.rs
task/net/src/server_vlan.rs
task/udpecho/src/main.rs

Split `NetError` into `{Phy,Recv,Send}Error`

---

drv/stm32h7-update-server/src/main.rs

After changing flash writes to 64-bit parallelism in #685, I've observed some updates hanging in `poll_flash_done()`. Adding ringbuf traces to log the SR2 register the first 16 iterations through the `poll_flash_done()` loop, I saw:
```
43  174       41        1 WriteStart
44  109       41       16 Bank2Sr(0x10005)
45  120       41        1 Bank2PollDone
46  216       41        1 WriteEnd
47  174       41        1 WriteStart
48  109       41       16 Bank2Sr(0x10005)
49  120       41        1 Bank2PollDone
50  216       41        1 WriteEnd
51  174       41        1 WriteStart
52  109       41       16 Bank2Sr(0x10005)
53  120       41        1 Bank2PollDone
54  216       41        1 WriteEnd
55  174       41        1 WriteStart
56  109       41        1 Bank2Sr(0x10005)
57  109       41 …
```

Fix race on flash write polling

---

drv/vsc7448/src/dev.rs
drv/vsc7448/src/lib.rs
drv/vsc7448/src/port.rs
drv/vsc7448/src/serdes6g.rs
drv/vsc85xx/src/vsc8504.rs
task/monorail-server/src/bsp/sidecar_1.rs

- Enable autonegotiation with the Tofino 2
- Fix SERDES6G XAUI configuration
- Front IO autonegotiation
- Minor tweaks to VSC8504 protocol transfer mode config

More management network bringup

---

task/net/src/bsp/gimletlet_mgmt.rs

Update gimletlet_mgmt net BSP to fix build

---

drv/ksz8463/src/lib.rs
drv/monorail-api/src/lib.rs
drv/vsc7448/src/mac.rs
idl/monorail.idol
task/monorail-server/src/bsp/sidecar_1.rs
task/monorail-server/src/bsp/vsc7448_dev.rs
task/monorail-server/src/server.rs
task/net/src/bsp/gimletlet_mgmt.rs
task/net/src/bsp/gimletlet_nic.rs
task/net/src/mgmt.rs

Another step towards replacing `ringbuf` debugging with proper APIs!

Add Idol API to read Monorail MAC table

---

drv/gimlet-hf-server/src/main.rs

`poll_for_write_complete()` is called by three writers (bulk_erase,
sector_erase, and page_program) that are writing vastly different
amounts of data (32MiB, 64KiB, 256 bytes). This commit adds an argument
to `poll_for_write_complete()` to control how long to sleep between
polls.
Based on experimental data, bulk_erase on an already-erased device (the
fastest scenario) takes about 400 ticks, sector_erase on an
already-erased sector takes about 5 ticks, and page_program takes 0-1
ticks. I added sleep times of 100 ticks, 1 tick, and no sleep (continue
busy waiting) for the three callers respectively, but am open to other
suggestions if folks disagree with those choices.

Add sleeps to gimlet-hf-server's poll_for_write_complete

---

doc/tasks.adoc

removed paragraph that was repeated a few lines (second point of itemization) later on
might need some more prettifying, please let me know!

doc: Update tasks.adoc

---

Cargo.lock
app/sidecar/rev-a.toml
build/xtask/src/auxflash.rs
build/xtask/src/config.rs
build/xtask/src/dist.rs
drv/auxflash-api/Cargo.toml
drv/auxflash-api/src/lib.rs
drv/auxflash-server/Cargo.toml
drv/auxflash-server/src/main.rs
drv/fpga-api/Cargo.toml
drv/fpga-api/src/lib.rs
drv/sidecar-front-io/Cargo.toml
drv/sidecar-front-io/build.rs
drv/sidecar-front-io/src/controller.rs
drv/sidecar-mainboard-controller/Cargo.toml
drv/sidecar-mainboard-controller/build.rs
drv/sidecar-mainboard-controller/src/lib.rs
drv/sidecar-seq-server/src/front_io.rs
drv/sidecar-seq-server/src/main.rs
idl/auxflash.idol

This PR removes the FPGA images from the Sidecar image in favor of using the auxiliary flash!

Use auxiliary flash on Sidecar

---

drv/auxflash-server/src/main.rs

I tried a couple other variants of this, but didn't love either:
* Erase the entire slot before the copy loop: this erases the entire slot, but we may not actually need the entire slot
* Extract the body of `slot_sector_erase()` to a method outside the idl impl and call it: this has some address checks and has to convert an offset within a slot to a raw address, neither of which are necessary here since we've already done both
so settled on copy/pasting the 3 lines that do the raw sector erase.

auxflash: When making a copy, erase target slot before writing.

---

task/thermal/src/main.rs

This fixes a warning in the build.

Add logging of run_control error

---

Cargo.lock
app/sidecar/rev-a.toml
drv/auxflash-api/src/lib.rs
task/mgmt-gateway/Cargo.toml
task/mgmt-gateway/src/update/sp.rs
task/mgmt-gateway/src/update/sp/auxflash.rs
task/mgmt-gateway/src/update/sp/stub_auxflash.rs

This builds on #822 and handles SP updates that have aux flash images.

mgmt-gateway: Handle SP updates that have auxflash images

---

Cargo.lock
task/control-plane-agent/Cargo.toml
task/control-plane-agent/src/main.rs

Picks up minor change to `handle_message()` that makes it infallible.

Pull gateway-messages from new MGS repo

---

.github/workflows/dist.yml
app/gimlet-rot/app-b.toml
app/gimlet-rot/app-c.toml
app/gimlet-rot/stage0-b.toml
app/gimlet-rot/stage0-c.toml
build/xtask/src/flash.rs

Featuring chips with TrustZone

Add files for gimlet-rot RevC

---

build/lpc55pins/src/lib.rs
drv/lpc55-spi-server/src/main.rs

Fixes stuff like [this wall of warnings](https://github.com/oxidecomputer/hubris/pull/861/files#file-drv-lpc55-spi-server-src-main-rs-L11)

Only import Pin when needed

---

lib/multitimer/src/lib.rs

Previously, clearing a timer and handling a timer notification failed to update the cached `self.current_setting` deadline, which could cause future `set_timer()` calls to fail to set the underlying system timer appropriately (if the requested deadline was later than the old, now out-of-date cached value).

Fix `set_timer()` failing to set the system timer

---

drv/lpc55-swd/src/main.rs

This was just silently not getting updated but based on existing use cases it was never noticed.

Actually update transaction state

---

task/thermal/src/bsp/gimlet_bc.rs

Uses new offset parameter to avoid overshoot.

thermal: revised Gimlet PID parameters

---

Cargo.lock
app/gimlet/rev-b.toml
app/gimlet/rev-c.toml
app/gimletlet/app.toml
app/psc/rev-a.toml
app/psc/rev-b.toml
idl/control-plane-agent.idol
idl/host-sp-comms.idol
lib/host-sp-messages/Cargo.toml
lib/host-sp-messages/src/lib.rs
task/control-plane-agent-api/Cargo.toml
task/control-plane-agent-api/src/lib.rs
task/control-plane-agent/Cargo.toml
task/control-plane-agent/src/inventory.rs
task/control-plane-agent/src/main.rs
task/control-plane-agent/src/mgs_common.rs
task/control-plane-agent/src/mgs_gimlet.rs
task/control-plane-agent/src/mgs_gimlet/host_phase2.rs
task/control-plane-agent/src/mgs_psc.rs
task/control-plane-agent/src/mgs_sidecar.rs
task/control-plane-agent/src/update/host_flash.rs
task/control-plane-agent/src/update/mod.rs
task/control-plane-agent/src/update/sp.rs
task/control-plane-agent/src/update/sp/auxflash.rs
task/control-plane-agent/src/update/sp/stub_auxflash.rs
task/host-sp-comms-api/src/lib.rs
task/host-sp-comms/Cargo.toml
task/host-sp-comms/src/main.rs

This pulls in the latest `gateway-messages`; not pinging anyone for review because it's almost entirely just type renames and reformatting.
Builds on #902 and should be merged after it.

Bump to SP <-> MGS protocol v2

---

Cargo.lock
lib/host-sp-messages/src/lib.rs
task/control-plane-agent/src/mgs_gimlet.rs

Follows https://github.com/oxidecomputer/management-gateway-service/pull/20

Add new startup option bits

---

drv/vsc7448/src/dev.rs
drv/vsc7448/src/lib.rs
task/monorail-server/src/bsp/sidecar_a.rs
task/monorail-server/src/bsp/sidecar_b.rs

Workaround for the SP side of https://github.com/oxidecomputer/bf_sde/issues/5

Retrigger autonegotiation when the 10G ANEG SM gets stuck

---

build/xtask/src/dist.rs

When building just the kernel, we wind up with a default bogus memory map for the tasks. This would cause an arithmetic underflow when the "find highest address" loop produced 0.
Since we don't care about the contents of the header in the build-kernel case, this substitutes a placeholder.

xtask: fix 'build kernel'

---

Cargo.lock
Cargo.toml
lib/dice/Cargo.toml
lib/dice/src/lib.rs
stage0/Cargo.toml

This resolves a TODO in lib/dice

Upgrade Hmac crate to latest version, use it in CDI derivation.

---

sys/abi/src/lib.rs

I thought I did this in #1046, but apparently not!

Remove unused TASK_ID_INDEX_BITS

---

drv/fpga-server/src/main.rs
drv/gimlet-seq-server/src/main.rs
drv/spi-api/src/lib.rs
drv/stm32h7-sprot-server/src/main.rs
task/monorail-server/src/main.rs
task/net/src/bsp/gimlet_bc.rs
task/net/src/bsp/gimletlet_mgmt.rs
task/net/src/bsp/gimletlet_nic.rs
task/net/src/bsp/psc_a.rs
task/net/src/bsp/psc_b.rs
task/net/src/bsp/sidecar_a.rs
task/net/src/bsp/sidecar_b.rs

This is a building block PR for integrating SPI ownership into tasks.

Add `SpiServer` trait and implement it for `Spi`

---

app/gimletlet/app-dc2024.toml
app/sidecar/rev-b.toml
drv/i2c-devices/src/lib.rs
drv/i2c-devices/src/ltc4282.rs
task/power/Cargo.toml
task/power/src/main.rs

add LTC4282 driver

---

task/udpbroadcast/src/main.rs

Fixes #1087 , requires https://github.com/oxidecomputer/humility/pull/317

Change `udpbroadcast` destination port

---

drv/sidecar-front-io/src/transceivers.rs
drv/transceivers-server/src/main.rs

This code more gracefully handles `Err` conditions when we have an I2C failure with the PCA9956B's rather than just `.unwrap()`-ing and potentially causing the `transceivers` task to panic. Since the LEDs are not critical to function, we will now log a `LEDReadError` or `LEDEnableError` to the `ringbuf` as appropriate.
Fixes #981
Edit: Fix incorrect issue linkage.

Remove transceivers task panic on LED issues, enforce reset pulse

---

sys/kern/src/arch/arm_m.rs

This fixes an unusual but vexing misbehavior in fault handling. If a task ran out of stack as a side effect of executing an SVC instruction, instead of entering the kernel at SVCall, it would enter at MemManageFault. However, _the SVC exception triggered by the SVC instruction is still pending when this happens._
This means that the flow of control goes like this:
1. Task faults.
2. Kernel does bookkeeping.
3. Kernel notifies supervisor and switches to supervisor task.
4. Kernel attempts to return to taskyland.
5. ARM M-profile tail chaining kicks in, converting the return-from-interrupt operation into a branch to SVCall.
6. Because we've already changed the current task, this simulates a surprise syscall _from the supervisor task._
7. In practice, the syscall is recv, and the supervisor …

arm_m: clear other fault pend bits if task faults.

---

Cargo.lock
Cargo.toml
drv/transceivers-server/src/udp.rs

Paired with https://github.com/oxidecomputer/transceiver-control/pull/58

Add support for reading MAC address in `transceivers`

---

Cargo.lock
Cargo.toml
task/control-plane-agent/src/main.rs
task/control-plane-agent/src/mgs_gimlet.rs
task/control-plane-agent/src/mgs_psc.rs
task/control-plane-agent/src/mgs_sidecar.rs
task/control-plane-agent/src/update/host_flash.rs

Requires https://github.com/oxidecomputer/management-gateway-service/pull/61 to go in first

Bump gateway-messages for host flash persistence

---

Cargo.lock
drv/i2c-api/src/lib.rs
drv/local-vpd/Cargo.toml
drv/local-vpd/src/lib.rs
drv/stm32xx-i2c-server/src/main.rs
drv/stm32xx-i2c/src/lib.rs
task/sensor-api/src/lib.rs
task/validate-api/src/lib.rs
task/vpd-api/src/lib.rs

SP can come up with a self-assigned MAC address

---

drv/stm32h7-sprot-server/src/main.rs

- Retries for all SpRot messages is set to three now.
- There was a bug in the SP SpRot server where a CSn pulse to clear a pending ROT_IRQ (and RoT queued message) was done with ~20ms of CSn asserted and no wait time afterwards for the RoT to react to the CSn deassert. That has been fixed to be ~10ms assert followed by ~10ms delay before checking for ROT_IRQ deassert. Previously this could use up one of the delivery attempts and when attempts was set to 1 would result in message delivery failure.

SP default retries=3, fix CSn pulse to allow RoT to respond in time.

---

drv/gimlet-seq-server/src/main.rs

record V3P3_SYS_A0 Vout when in A2

---

Cargo.lock
Cargo.toml

https://github.com/oxidecomputer/hubris/security/dependabot/4

Bump zip to fix dependabot warning

---

.github/workflows/dist.yml
.github/workflows/documentation.yml
.github/workflows/formatting.yml

Address GitHub Actions deprecations

---

task/net/src/bsp/psc_bc.rs
task/net/src/mgmt.rs

Oops, these changes were unstaged when I merged #1220

Fix PSC GPIO configuration

---

Cargo.lock

Corresponding Humility fix merged.

Pull in new Idol version with Complex error support.

---

drv/vsc7448/src/lib.rs

Don't connect technician ports to each other

---

app/sidecar/src/main.rs

This revision check code was added to sidecar by copy-paste from Gimlet and was wrong. It didn't work correctly on B rev (detected the wrong revision) and wouldn't boot at all on C (detected the same wrong revision).
- Rev pins were added in the B rev of Sidecar, which has rev 001.
- Rev pins are on the C GPIO bank, which needs to be turned on.
- The timing calculation cited in the delay loop was concerned with trace capacitance on Gimlet A/B rev boards, and is irrelevant for Sidecar, which needs to have a delay calculated; I've hardcoded it to a larger conservative number to ensure that pins settle in the absence of this.

Fix Sidecar rev pin GPIO bank and delay.

---

Cargo.lock
Cargo.toml
task/net-api/src/lib.rs
task/net/build.rs
task/net/src/main.rs
task/net/src/server.rs
task/net/src/server_basic.rs
task/net/src/server_vlan.rs

Pending the PR in `gateway-messages`, since otherwise interoperability breaks (we're using the `smoltcp` IPv6 address in our APIs)

Upgrade to `smoltcp` 0.9

---

sys/kern/src/task.rs
sys/kern/src/umem.rs

This will copy from (not to!) DMA-capable memory in a task.
Copying _to_ DMA-capable memory could be added pretty easily, but isn't required for what we're doing right now, so I have omitted it.

kern: add new `safe_copy_dma` operation.

---

app/gimlet/rev-b.toml
app/gimlet/rev-c.toml
app/gimlet/rev-d.toml
app/psc/rev-a.toml
app/psc/rev-b.toml
app/psc/rev-c.toml

This task is crashing at about 1 Hz with a stack overflow. I don't know why, I'm just the release engineer.

Increase Gimlet power task allocation.

---

build/xtask/src/dist.rs

Corresponding humility PR: https://github.com/oxidecomputer/humility/pull/379 (can be merged in either order)

Add `image-name` to the archive

---

Cargo.lock
app/sidecar/rev-b.toml
app/sidecar/rev-c.toml
task/control-plane-agent/Cargo.toml
task/control-plane-agent/src/inventory.rs
task/control-plane-agent/src/mgs_sidecar.rs

Give control of Sidecar's System LED to MGS

---

task/monorail-server/src/bsp/sidecar_bc.rs

See oxidecomputer/bf_sde/issues/27

Add second-level watchdog for Tofino link-down issue

---

Cargo.lock
app/demo-stm32f4-discovery/app-f3.toml
app/demo-stm32f4-discovery/app.toml
app/demo-stm32g0-nucleo/app-g031.toml
app/demo-stm32g0-nucleo/app-g070.toml
app/demo-stm32g0-nucleo/app-g0b1.toml.noworky
app/demo-stm32h7-nucleo/app-h743.toml
app/demo-stm32h7-nucleo/app-h753.toml
app/gemini-bu/app.toml
app/gimlet/rev-b.toml
app/gimlet/rev-c.toml
app/gimlet/rev-d.toml
app/gimletlet/app-meanwell.toml
app/gimletlet/app-mgmt.toml
app/gimletlet/app-sidecar-emulator.toml
app/gimletlet/app.toml
app/lpc55xpresso/app.toml
app/psc/rev-a.toml
app/psc/rev-b.toml
app/psc/rev-c.toml
app/rot-carrier/app.toml
drv/user-leds/Cargo.toml
drv/user-leds/build.rs
drv/user-leds/src/main.rs
idl/user-leds.idol
task/control-plane-agent/src/mgs_gimlet.rs
task/control-plane-agent/src/mgs_psc.rs

Nothing too controversial here, I hope!

Implement LED blinking

---

app/rot-carrier/app.toml

Switch rot-carrier board name to fix flashing.

---

app/rot-carrier/app.toml
app/rot-carrier/src/main.rs

Remove ping from rot-carrier/app.toml

---

Cargo.lock
lib/dice/src/mfg.rs

https://github.com/oxidecomputer/hubris/issues/1383
https://github.com/oxidecomputer/dice-util/pull/83

Supply MessageHash to Ack MfgMessage.

---

app/gimlet/rev-d.toml
task/thermal/src/bsp/gimlet_bcd.rs

properly validate M.2 devices on Rev D

---

task/monorail-server/src/bsp/sidecar_bc.rs

This flag is set when we first initialize the system and when we change link speed, because the VSC7448 and VSC8562 are configured one after the other.  It's spurious and does not reoccur, so it seems reasonable to clear it here.  Otherwise, we see a false error reported in `humility monorail status`, which goes away when you re-run the command.

Clear spurious CGBAD flags on the VSC8562

---

task/monorail-server/src/bsp/sidecar_bc.rs

The Tofino is powered off in power states other than A0; this prevents us from doing a reinitialization every ~20 seconds when the system is in A2.

Only do monorail stuck-link handling when in A0

---

drv/vsc7448/src/lib.rs

"hey you guys are back early"
"technician port's haunted"
(see #1399 for _many_ details)

Fix VSC7448 initialization order

---

drv/vsc7448/src/lib.rs
task/monorail-server/src/bsp/sidecar_bc.rs

See discussion starting [here](https://github.com/oxidecomputer/hubris/issues/1399#issuecomment-1601060429)

Alternate fix for hubris#1399

---

Cargo.lock
Cargo.toml
app/demo-stm32h7-nucleo/app-h743.toml
app/demo-stm32h7-nucleo/app-h753.toml
app/gimlet/rev-b-dev.toml
app/gimlet/rev-b.toml
app/gimlet/rev-c-dev.toml
app/gimlet/rev-c.toml
app/gimlet/rev-d-dev.toml
app/gimlet/rev-d.toml
app/gimletlet/app.toml
app/lpc55xpresso/app.toml
app/psc/rev-a.toml
app/psc/rev-b.toml
app/psc/rev-c-dev.toml
app/psc/rev-c.toml
app/sidecar/rev-b-dev.toml
app/sidecar/rev-b.toml
app/sidecar/rev-c-dev.toml
app/sidecar/rev-c.toml
task/dump-agent/src/udp.rs

Draft comment:
```
This adds dump-agent support for GetImageId, which is necessary to
address humility#395.
```

add GetImageId support to dump-agent

---

drv/lpc55-update-server/src/main.rs

This is an attempt to fix #1450.
I have tested this on my benchtop system (with the PING / PONG / SCRATCH pages all written), and it works there.
Unfortunately, I don't have a sufficiently blank RoT on my bench to test with (see https://github.com/oxidecomputer/hubris/issues/1450#issuecomment-1614746787).

Only read CFPA headers if they are programmed

---

drv/stm32h7-eth/src/ring.rs

See https://github.com/oxidecomputer/hubris/issues/750#issuecomment-1636322073 and later comments.

Add load-bearing delay to DMA read descriptor write

---

drv/lpc55-update-server/src/main.rs

Our other flashing tools pad out page sizes with `0xff` to mimic erased bytes. Match this behavior.

Change default bytes to `0xff`

---

lib/lpc55-rot-startup/src/images.rs

The check for a valid image magic should come before attempting to read any of the image lengths. The image lengths should also be checked for overflows.

Add more robust checks for images

---

drv/gimlet-seq-server/src/main.rs

gimlet-seq-server unwraps (panics) on a lot of external conditions. I'm still pretty sure we want to fix that, but for the time being, if we're going to unwrap everywhere, we can at least unwrap_lite.
Unwrap Debug-formats the error, which pulls in all the Debug-format machinery. That machinery goes largely unused in practice, since we only format the first 128 characters of a panic anyway. Changing all these unwraps to unwrap_lite knocks 16% off the binary size and bumps it into the next smaller size class, freeing 64 kiB of space (which was mostly lost to fragmentation) on Gimlet as of this writing.

gimlet-seq-server: unwrap diet

---

lib/host-sp-messages/src/lib.rs
task/control-plane-agent/src/mgs_gimlet.rs
task/host-sp-comms/src/main.rs

Tracks with the latest changes to [RFD 316](https://rfd.shared.oxide.computer/rfd/0316).

[host-sp-comms] Add `KeySet` message and handler

---

app/lpc55xpresso/app-sprot.toml
app/lpc55xpresso/app.toml
app/oxide-rot-1/app-dev.toml
app/oxide-rot-1/app.toml
app/rot-carrier/app.toml
task/dump-agent-api/src/lib.rs
task/dump-agent/src/main.rs
task/dumper-api/src/lib.rs
task/dumper/src/main.rs

restore RoT's ability to take SP dumps

---

app/gimlet/base.toml
drv/i2c-types/src/lib.rs
drv/stm32xx-i2c/src/lib.rs
task/power-api/src/lib.rs

reading BMR491 PMBus data over Idol hangs bus

---

task/net/README.md

Forgot to actually check this in, whoops.

task/net: import design doc from gist

---

drv/gimlet-seq-server/src/main.rs

As described in #1648, when the NIC fails to come up successfully and is
powered off, it's desirable to capture sequencer register state
associated with the NIC and stick them in the ringbuf before actually
commanding the sequencer to power off the NIC, in order to debug NIC
failures.
This branch changes the `gimlet-seq-server` task to record the values of
the `NIC_CTRL`, `NIC_STATUS`, `OUT_STATUS_NIC1` and `OUT_STATUS_NIC2`
registers in the ringbuf when `NIC_PWREN_L` is asserted high while in
the `A0PlusHP` state. Issue #1648 also requested that the `IFR` and
`AMD_STATUS` registers be recorded in the ringbuf when this occurs, but
those registers should already be present in the `Trace::Status` entry
that's recorded every time the sequencer task handles a notification,
immediately prior …

gimlet-seq: record sequencer T6 state on power off

---

Cargo.lock
app/sidecar/base.toml

This updates the idol deps to pull in this PR: https://github.com/oxidecomputer/idolatry/pull/50

Bump Idol version

---

drv/transceivers-server/src/main.rs

Clippy pointed out that this loop can't, well, loop. At all.
I'm kind of surprised earlier versions missed this.

transceivers-server: remove illusory loop

---

app/demo-stm32h7-nucleo/app-h743.toml
app/demo-stm32h7-nucleo/app-h753.toml
app/gimlet/base.toml
app/gimletlet/app.toml
app/psc/base.toml
app/sidecar/base.toml
drv/gimlet-seq-server/src/main.rs
drv/stm32xx-i2c-server/src/main.rs
task/jefe/src/dump.rs

Gimlet hangs on cold power-on after toolchain update

---

build/toml-patch/src/lib.rs
build/xtask/src/config.rs
build/xtask/src/dist.rs
build/xtask/src/graph.rs
build/xtask/src/lsp.rs
build/xtask/src/sizes.rs

Ran:
`( cd build/xtask; cargo clippy)`

Listen to clippy and do what it says.

---

drv/gimlet-seq-server/src/main.rs

Per discussions in chat and in #1814

Leave `FAULT_PIN_L` low on failure

---

Cargo.lock
app/demo-stm32h7-nucleo/app-h743.toml
app/demo-stm32h7-nucleo/app-h753.toml
app/gimlet/base.toml
app/gimletlet/app-mgmt.toml
app/gimletlet/app.toml
app/grapefruit/app.toml
app/medusa/base.toml
app/psc/base.toml
app/sidecar/base.toml
chips/stm32h7/memory-large.toml
chips/stm32h7/memory.toml
task/dumper/src/main.rs

Can't collect an SP dump

---

.github/workflows/release.yml

It turns out v3 is incompatible with upload-artifact@v4

Switch to download-artifact@v4

---

sys/kern/src/arch/arm_m.rs

Right now, if a task has no non-stack RAM usage and a power-of-two stack, the kernel's stack scribbling code skips it. This causes humility stackmargin to emit bogus values, but has no other implications at the moment.
The cause is a classic off-by-one error, testing the address just above the stack instead of within the bounds of the stack. This hits a valid region if there is at least one byte of non-stack data in RAM, but only then.
This fixes that by testing the top word in the stack.
Fixes #1876.

kern: handle pow2-sized stacks in small tasks

---

bugs/index.html
index.html
style.css

- Move common CSS into `style.css`
- Add a "days since last Hubris kernel bug" page
- Link to it on the main Hubris landing page

Add 'days since last bug' page

---

app/gimletlet/app-mgmt.toml

Building with all app.toml files fails on this one. So, fix it.

Bump stacksize in .../app-mgmt.toml so building all apps works.

---

app/oxcon2023g0/app.toml

🎵I sure hate manual kernel sizing 🎵
🎵Why did I do this to myself 🎵

oxcon2023g0: fix kernel sizing

---

Cargo.lock
app/grapefruit/app.toml
drv/grapefruit-seq-server/Cargo.toml
drv/grapefruit-seq-server/src/main.rs

Load dummy packrat config for grapefruit

---

drv/grapefruit-seq-server/src/main.rs

https://github.com/oxidecomputer/hubris/pull/1990 fails on initial power up (with `FpgaInitFailed(ChipNotListening)
`), because it removes a retry loop; apparently the FPGA needs a little more time to wake up.

Retry Spartan-7 initialization

---

drv/ice40-spi-program/Cargo.toml
drv/ice40-spi-program/src/lib.rs

(Extracted from the larger Cosmo support PR)

Make Ice40 errors countable

---

task/control-plane-agent/src/mgs_compute_sled/host_phase2.rs

`host_phase2::State::port_to_send_packet` had confusing behavior upon timeout: it returned the _original_ port if the timeout had expired, which (eventually) caused the caller to send a packet to the _opposite_ port.
It turns out that we aren't actually using the port; we were immediately calling `is_some()` on the returned `Option<Port>`.  This PR changes `port_to_send_packet() -> Option<Port>` to `wants_to_send_packet() -> bool`.

Simplify checking whether a host phase2 packet is ready

---

task/control-plane-agent/src/mgs_common.rs
task/control-plane-agent/src/mgs_sidecar.rs

Support `ResetComponent` for monorail

---

task/thermal/src/bsp/cosmo_a.rs
task/thermal/src/bsp/gimlet_bcdef.rs
task/thermal/src/bsp/grapefruit.rs
task/thermal/src/bsp/medusa_a.rs
task/thermal/src/bsp/minibar.rs
task/thermal/src/bsp/sidecar_bcd.rs
task/thermal/src/control.rs

Fixes #2062 (pending Aaron's testing!)

Invalidate fan speed readings when removed

---

Cargo.lock
task/cosmo-spd/Cargo.toml
task/cosmo-spd/src/main.rs

Needs validation on actual hardware!

Add SPD temperature sensing

---

task/cosmo-spd/src/main.rs

Remove unused variant

---

app/cosmo/base.toml

Add auxflash to cosmo control-plane-agent

---

drv/cosmo-hf/src/hf.rs
drv/gimlet-hf-server/src/main.rs

The existing hash invalidation can leave slot stuck in `HashInProgress` permanently:
```
pilot -r dublin sp exec -e 'component-active-slot host-boot-flash -s 1 -p' BRM27230037
pilot -r dublin sp exec -e 'start-host-flash-hash 0' BRM27230037
pilot -r dublin sp exec -e 'power-state A2' BRM27230037
sleep 30
pilot -r dublin sp exec -e 'power-state A0' BRM27230037
sleep 120
$ pilot -r dublin sp exec -e 'get-host-flash-hash 0' BRM27230037
Jul 28 19:22:14.066 INFO creating SP handle on interface dublin_sw0tp0, component: faux-mgs
Jul 28 19:22:14.072 INFO initial discovery complete, addr: [fe80::aa40:25ff:fe04:604%5]:11111, interface: dublin_sw0tp0, socket: control-plane-agent, component: faux-mgs
Error: Error response from SP: hf: Hash calcuation in progress
```
Switching the mux (i.e. going …

Fix host flash hash invalidation

---

task/jefe/src/main.rs

We recently taught Jefe to impose a restart delay before standing back up a crashing task. However, the implementation contained a logic error that could manifest in certain corner cases: it would actually restart the task _the first time it considered it,_ but only if the deadline hadn't actually elapsed yet.
Once the deadline elapsed, Jefe would enter an infinite loop of setting its own timer into the past and responding to the notification, never yielding the CPU.
It turns out this is relatively easy to trigger by putting a task into a fast crashloop -- I hit this when forcing the I2C driver to crash while chasing an unrelated bug.
This commit flips the timestamp comparison logic to implement the restart timeout for reals, causing Jefe to tolerate fast crashloops without taking the …

jefe: fix comparison inversion in timeout handling
